### ISSUE TITLE
metadata merge behavior for parallel jobs

### ISSUE THREAD

**Issue by ycjonlin** [screwdriver-cd/screwdriver#1015]
**What happened**:
We encounter a metadata behavior problem when using parallel jobs in our pipeline. If we have 2 jobs, one sets metadata key `prefix.key1` and the other sets metadata key `prefix.key2`. If 2 jobs run sequentially, both keys would be found in meta data. If 2 jobs run in parallel, only one key will be available, depending on which job finished first.

The reason seems to do with the way metadata are merged. Only the first layer of json will be merged when parallel jobs are joined together. Deeper layers will replace each other. It seems to be a bit odd that sequential and parallel execution will produce different results.

**What you expected to happen**:

**How to reproduce it**:
```
jobs:
  set-key1:
    requires: [~pr, ~commit]
    image: buildpack-deps
    steps:
      - test: meta set prefix.key1 value1
  set-key2:
    requires: [~pr, ~commit]
    image: buildpack-deps
    steps:
      - test: meta set prefix.key2 value2
  get:
    requires: [set-key1, set-key2]
    image: buildpack-deps
    steps:
      - get1: echo "prefix.key1=$(meta get prefix.key1)"
      - get2: echo "prefix.key2=$(meta get prefix.key1)"
```
