### ISSUE TITLE
Template to support listing multiple images

### ISSUE THREAD

**Issue by jithin1987** [screwdriver-cd/screwdriver#1040]
## Context
Templates are mapped to a single image via `image` field in [template configuration](https://docs.screwdriver.cd/user-guide/templates#creating-a-template). This forces template owners who wants to support multiple image versions (Eg: node:6, node:8) to create multiple templates with same steps, because they have no other place to list supported images.

## Objective
Support `images` config field for templates.
```
name: template_name
images:
    node6: node:6
    node8: node:8
config:
    image: node6
...
```

This allows template owners to express in template configuration all the supported images and a default image.

1. For template configuration if `images` field is present then value in `image` will be used as an index to the `images` object.
1. A user who is using the template can either specify a docker image or a key from `images` as `image`

```
jobs:
    main:
        template: template_name
        image: node6 or node:6
```
3. If user uses an alias which is not valid, say `nodeX` we should fall back to default `image` configured in template, and figure out a way to surface this error to the pipeline page. See question 6 here https://github.com/screwdriver-cd/screwdriver/issues/937#issuecomment-391448232 it has similar concerns on error bubbling.

**Comment by tkyi** [comment]
After thinking more about this feature, I think it's strange to have the `images` field at the job config level. This means that users will be able to specify `images` themselves and it won't work. It seems like it's a template-specific field and should therefore move one level up in the template config, like this:
```yaml
name: test/template
version: "1.3"
description: Template for testing
maintainer: foo@bar.com
images:
  latest: node:6
  stable: node:5
config:
  image: node:6
  steps:
    - install: npm install
    - test: npm test
    - echo: echo $FOO
```
