### ISSUE TITLE
Support source code checkout based on Repo

### ISSUE THREAD

**Issue by jithin1987** [screwdriver-cd/screwdriver#1041]
## Context

Repo is a Google-built repository management tool that runs on top of Git. Android project which uses Repo will have their dependencies spread across multiple project and uses a Repo manifest file which provides information on where to find these dependencies along with the main application.

## Objective

1. Screwdriver should listen to commit changes on main application code base.
1. Screwdriver should checkout source code based on information from Repo manifest file which can be stored in an external GIT repository outside of the main application.

## References 

1. https://source.android.com/setup/develop/
1. https://source.android.com/setup/develop/repo

**Comment by jithin1987** [comment]
Implementation direction based on feature discussion on 4/27/18

1. Repo manifest file path will be exposed in `job` configuration.
1. Implement a shared command for repo which will be used by https://github.com/screwdriver-cd/scm-github to do source code checkout if job configuration identifies that job uses Repo

**Comment by tkyi** [comment]
With the current design, the config will look like:
```
shared:
    image: node:6
    scm:
      repo: git@github.com:screwdriver-cd/data-schema.git
jobs:
    component:
        steps:
            - install: npm install
        requires:
            - ~commit
            - ~pr
        scm:
          repo: git@github.com:screwdriver-cd/data-schema.git/RepoManifest.xml#branch
```
Not sure why this config isn't under `annotations`. I don't think it makes sense for it to be nested under `scm` when `sourcePaths` is not under `scm`.

Why can't users specify repo configs when they create pipelines in the UI?
