### ISSUE TITLE
Environment variables are not evaluated

### ISSUE THREAD

**Issue by jithin1987** [screwdriver-cd/screwdriver#1070]
**What happened**:

While SD allows configuration of environment variables via [`environment` section](https://docs.screwdriver.cd/user-guide/configuration/environment), they are not evaluated, instead it is taken as it is.

Lets say `$SD_ARTIFACTS_DIR=/tmp`
```
shared:
  environment:
    TEST_PATH: $SD_ARTIFACTS_DIR/test
```

Inside a build 
```
echo $TEST_PATH
$SD_ARTIFACTS_DIR/test
```

**What you expected to happen**:
```
echo $TEST_PATH
/tmp/test
```

**How to reproduce it**:

1. Set an environment variable with refers another one. Eg: `TEST_PATH: $SD_ARTIFACTS_DIR/test`
2. Using that environment variable in a build does not give the expected value.

**Comment by Zhongtang** [comment]
One thing we need to pay attention to is the order of evaluation. e.g. assuming `$SD_SOURCE_DIR` is `/tmp`

```
shared:
  environment:
    PATH1: $PATH2/test
    PATH2: $SD_SOURCE_DIR/sunfire_reports
```

In this case, do we evaluate `$PATH1` as `/test` (evaluate based on the order of definition) or `/tmp/sunfire_reports/test` ? If we do the later, we need to be careful about potential loop in evaluation, e.g.

```
shared:
  environment:
    PATH1: $PATH2/test
    PATH2: $PATH1/sunfire_reports
```
