### ISSUE TITLE
Slack notification doesn't work with private channels

### ISSUE THREAD

**Issue by Zhongtang** [screwdriver-cd/screwdriver#1073]
**What happened**:

It seems the current slack integration only works with public channels, but not the private ones.

**What you expected to happen**:

Slack notification should work with both public and private channels.

**How to reproduce it**:

- Create a private channel, e.g. `ztian-test-slack`, and invite screwdriver-bot to the channel. Then create a pipeline with config like following. After the job fails, the private channel won't be notified

```
version: 4
shared:
    image: node:8
    steps:
        - echo: echo hello
        - print_env: env | sort
        - fail: "false"
    settings:
        slack: ztian-test-slack

jobs:
    main:
        requires: [~pr, ~commit]
```

- Now create a public channel, e.g. `ztian-test-slack2`, and also invite screwdriver-bot. Modify the configuration to notify the new channel. After the job fails, the public channel will be notified
