### ISSUE TITLE
Override environment for PR builds specifically

### ISSUE THREAD

**Issue by anilkumarmyla** [screwdriver-cd/screwdriver#1074]
In current setup, any step that has to be overridden in a PR build can be done by inspecting `SD_PULL_REQUEST` variable like below
```
steps:
  - do_something: |
      if [ ! -z $SD_PULL_REQUEST ] ; then
          ./do_something.sh -dryrun
      else
          ./do_something.sh
      fi
```

The steps become overly complicated and ugly to look at. To overcome this, we can have a `pull-request` profile for `environment` where we override variables and avoid the `SD_PULL_REQUEST` inspection as below
```
environment:
  EXTRA_ARGS: ""
  pull-request:
    EXTRA_ARGS: "-dryrun"
    
steps:
  - do_something: |
      ./do_something.sh ${EXTRA_ARGS} 
```
