### ISSUE TITLE
feature request: trigger job on a failed build

### ISSUE THREAD

**Issue by drewfish** [screwdriver-cd/screwdriver#1080]
**What happened**:
no existing feature

**What you expected to happen**:
Some way for job B to run if job A fails. This would be especially useful for template pipelines, where I (as template author) would want to setup some negative tests (make sure template fails build correctly) for the newly-created template version.

As a random idea, perhaps specify this in `requires` somewhere, e.g. `requires: [ validate-pass, !validate-fail ]`.

**How to reproduce it**:

**Comment by tk3fftk** [comment]
I want to rollback automatically when a deploy job or some functional test is failed.

an example sd.yaml is like below:
```
shared:
  image: kubectl-available-image

jobs:
  deploy:
    requires: [~commit]
    steps:
      - deploy: kubectl apply -f foo-deployment.yaml
  functional-test:
    requires: [deploy]
    steps:
      - test: some test
  rollback:
    requires: [failed@functional-test]
    steps:
      - rollback: kubectl rollout undo deploy/foo-deployment
```

Related: 
- `on_failure` step hook is available in Concourse
[on_failure step hook - Concourse CI](https://concourse-ci.org/on-failure-step-hook.html)
