### ISSUE TITLE
Allow and respect sourcePaths on dependent jobs

### ISSUE THREAD

**Issue by edudar** [screwdriver-cd/screwdriver#1086]
**What happened**:
`sourcePaths` can only be used in a job that requires `~pr` or `~commit`. It's ignored otherwise.
```
jobs:
  main:
    requires: [~pr, ~commit]
  client:
    requires: [main]
    sourcePaths: ["common/", "client/"]
  service:
    requires: [main]
    sourcePaths: ["common/", "service/"]
```
This scenario is particularly useful when each job may require some heavy-lifting done, like long-time compilation so you don't want to do it more than once for a particular run. So you do heavy-lifting in `main` and then split into where changes are specifically and, for example, run tests for a particular module only or publish binaries for that module only and do nothing for a module that has no changes occurred.

**What you expected to happen**:
A commit to `"client/"` path should trigger `main` then `client` jobs.

Alternatively, it might be useful to have steps that would respect `sourcePaths`. Then heavy-lifting can be done in step 1 and steps 2 and 3 would alternate based on a point of change. This might be a little too crazy though.

**Comment by petey** [comment]
I think this doesn't work because of what `sourcePaths` ultimately does. The point of sourcePaths is to filter webhooks from a SCM based on the list of changed files. So this really only applies for `~pr` and `~commit` hooks. When jobs are triggered by their interdependencies, they do not pass or process a list of file changes.

Your pipeline might look a little different to handle this case:
```
jobs:
  mainCommon:
    requires: [~pr, ~commit]
    sourcePaths: ["common/"]
  mainClient:
    requires: [~pr, ~commit, mainCommon]
    sourcePaths: ["client/"]
  mainServer:
    requires: [~pr, ~commit, mainCommon]
    sourcePaths: ["server/"]
  client:
    requires: [mainClient]
  server:
    requires: [mainServer]
  client:
    requires: [mainClient]
  server:
    requires: [mainServer]
```

**Comment by dwmarshall** [comment]
It would be nice if generic triggers included any source path information that accompanied the original `~commit` or `~pr` event, but it would be reasonable to determine that too much re-architecture would be needed for this.

Here's my use case: I have a a pipeline that runs a `main` job for any `~commit`. I want another job to run only if a particular file has changed; however, it is essential that this job runs after main. Here's what I want to do:

```
jobs:
  main:
    requires: [~commit]

  special:
    requires: [main]
    sourcePaths: ["special.txt"]
```

It's my understanding that I cannot change `special` to be triggered by `~commit` but `blockedBy` `main` because there's no guarantee that `main` would start before `special` and thus block it.

Here's what I think will work:
```
jobs:
  main:
    requires: [~commit]

  special-check:
    requires: [~commit]
    sourcePaths: ["special.txt"]

  special:
    requires: [main, special-check]
```
