### ISSUE TITLE
Unable to access artifacts that include $ character

### ISSUE THREAD

**Issue by catto** [screwdriver-cd/screwdriver#1088]
**What happened**:
I put files that include `$` character in its name into `artifacts` directory in my build.
For example: `PublishTest$TestString.xml`
I accessed to the artifact via the UI after the build, and store API returned 404 error.
```json
{
  "statusCode": 404,
  "error": "Not Found",
  "message": "Not Found"
}
```
Any other file such as `environment.json` is fine.

**What you expected to happen**:
I can access any artifacts even if artifacts includes `$` in its filename.

**How to reproduce it**:
* Put `PublishTest$TestString.xml` file in your artifacts directory.
* Run new build
* Access the file via web UI

example:
```
  steps:
      - mkdir: mkdir $SD_ARTIFACTS_DIR/test
      - touch: echo abcde > $SD_ARTIFACTS_DIR/test/PublishTest\$TestString.xml
      - ls: ls -l $SD_ARTIFACTS_DIR/test
```
