### ISSUE TITLE
Indentation in default.yaml file isn't consistent.

### ISSUE THREAD

**Issue by elyzion** [screwdriver-cd/screwdriver#1223]
**What you found**:

The `config/default.yaml` file features both 4 and 2 space indentation. 

Example:
```
executor:
    # Default executor
    plugin: k8s
    k8s:
      enabled: true
      options:
        kubernetes:
            # The host or IP of the kubernetes cluster
            host: kubernetes.default
```

**What you expected**:

Indentation should be consistent for all files of the same type across the screwdriver project namespace.
