### ISSUE TITLE
Not enough to check duplicate steps

### ISSUE THREAD

**Issue by wdstar** [screwdriver-cd/screwdriver#1253]
**What happened**:

Currently, we can create a pipeline which job includes duplicate steps.
Screwdriver Validator does not check this duplicate steps. But its pipeline can never be started (Setting up build...).

**What you expected to happen**:

Screwdriver Validator should check duplicate steps appropriately.

**How to reproduce it**:

- create the following pipeline.
```
jobs:
  test:
    requires: [~commit]
    image: node:8
    steps:
      - echo: echo dummy
      - echo: echo dummy
```
- start that pipeline.
