### ISSUE TITLE
Build cache

### ISSUE THREAD

**Issue by jithin1987** [screwdriver-cd/screwdriver#1257]
## Context

Improve build performance by providing caching support natively in Screwdriver infrastructure.

Builds do lots of repetitive downloads of artifacts, from various sources - npm, maven, bintray, also intermediary results of a build can be cached for the duration of the event it is part of. 

Design Proposal - https://github.com/screwdriver-cd/screwdriver/blob/master/design/build-cache.md 

## Objective

1. [Implement](https://github.com/screwdriver-cd/screwdriver/issues/1281) [cache service](https://github.com/screwdriver-cd/screwdriver/blob/master/design/build-cache.md#build-cache-service)
    1. Should support a pluggable interface like Screwdriver store such that cluster admins can choose and build an implementation which suits specifics of the cluster implementation.
1. config-parser [to support ](https://github.com/screwdriver-cd/screwdriver/issues/1280)`cache` [config](https://github.com/screwdriver-cd/screwdriver/blob/master/design/build-cache.md#yaml-specification) in `screwdriver.yaml`
1. [bookends](https://github.com/screwdriver-cd/screwdriver/issues/1284) to download and update cached artifacts as per [execution flow](https://github.com/screwdriver-cd/screwdriver/blob/master/design/build-cache.md#execution-flow)
1. [Implement](https://github.com/screwdriver-cd/screwdriver/issues/1282) `cache`  cli which a build can invoke to put/get/delete cached artifacts from cache service

## References

1. [Proposal](https://github.com/screwdriver-cd/screwdriver/blob/master/design/build-cache.md)

**Comment by elyzion** [comment]
I'm still not 100% on the proposed syntax for the defining caches in the Yaml file. The current proposal gives the following example definition:

```
shared:
  # Caches defined in the shared section can be pipeline or exection scoped.
  cache:
    # A pipeline scoped cache.
    pipeline: ["node_modules/", "~/.sbt"]
    # An event scoped cache
    event: ["target/generated-intermediate-resouce/*"]
    # A job scoped cache 
    my-cache-1:  ["target/some-artifact.zip"]
```

On close observation it begins to stand out that `pipeline` and `event` are effectively scopes, while `my-cache-1` is the name of a job scoped cache. It would be more consistent if the same layer container only the same class of definition, ie. if the definition section looked a bit more like this:

```
shared:
  # Caches defined in the shared section can be pipeline or exection scoped.
  cache:
    # A pipeline scoped cache.
    pipeline: ["node_modules/", "~/.sbt"]
    # An event scoped cache
    event: ["target/generated-intermediate-resouce/*"]
    # A job scoped cache 
    job:
      - my-cache-1:  ["target/some-artifact.zip"]
```

This does however result in a visual difference between the pipeline and event scoped caches and job caches.

I would like to make sure that everyone is ok with the current proposed syntax. Does the second format seem more logical, or does anyone have a more natural solution?
