### ISSUE TITLE
Email notifications for gmail

### ISSUE THREAD

**Issue by arunp7080** [screwdriver-cd/screwdriver#1259]
Notifications can be configured for slack and email, I am not sure if it is configurable for gmail accounts as there are no documents for that. General settings like below doesn't work for gmail.

```
notifications:
    email:
        host: smtp.yourhost.com
        port: 25
        from: example@email.com

```

**Comment by tkyi** [comment]
Google strictly enforces Email Sender authorization before it does any spam analysis or whitelist checking. If you have a process that sends mail that isn't properly authorized, it will not get delivered.

So some things to consider when sending mail depends on what host you're using:

1. Sending from a host in a datacenter: You will want to adjust your code/script/configuration to make sure that you're sending from a valid email address (`@gmail.com`, etc). If you're setting both the Envelope Sender and the From: header, you want to make sure those domains match. If they don't align, they will fail DMARC as well. (example: If your code uses sendmail, for instance, you probably want to use the `-f` option.)

2. Sending from AWS SES: You will want to use the [EasyDKIM option](https://docs.aws.amazon.com/ses/latest/DeveloperGuide/easy-dkim.html). You'll need to add a `username` and `password` in your email notifications configuration. 
```
notifications:
    email:
        host: smtp.yourhost.com
        username: AKIA1234567ABCD
        password: AbCdEfGHi123456
        port: 25
        from: example@email.com
```

I notice that these fields are missing from our docs. I'll update the missing documentation with those fields, too.
