### ISSUE TITLE
[feature] disable notification on PR builds

### ISSUE THREAD

**Issue by minzcmu** [screwdriver-cd/screwdriver#1274]
Now notification config is tied to a job. If the job has `requires: [~pr, ~commit]` then it will send notification for both pr jobs and commits. But people probably don't care about PR status that much. We should allow them to disable that. e.g.
```
        settings:
            slack:
                channels:
                     - 'mychannel'
                     - 'my-other-channel'
                disablePR: true
```
