### ISSUE TITLE
Matrix Jobs

### ISSUE THREAD

**Issue by jithin1987** [screwdriver-cd/screwdriver#1309]
## Context

Support building in multiple build containers with minimal job config. For example a library which needs to be built for both 7.4 & 7.5 versions of CentOS, rather than user defining 2 separate jobs for this, SD can abstract it out in a single job config, with multiple jobs fanning out for that single job configuration

Example conifguration

```
jobs:
   matrix-job:
      builds: [centos:7.4, centos:7.5]
      steps:
        build: ./build.sh
```

Above `builds` config should also take keys from, template  `images` filed which is used to hold multiple supported `images` https://docs.screwdriver.cd/user-guide/templates#creating-a-template

With above config Screwdriver execution system should create 2 jobs which runs in parallel 

## Objective

1. Support matrix jobs.

**Comment by jithin1987** [comment]
Also if we can model passing different environment variables for each of the matrix job, then we can achieving composition of jobs at a pipeline scale.

**Comment by scr-oath** [comment]
I wonder if this could be be implemented something like a yaml preprocessor that could just connect a before and after job. Possibly giving option to create sd/noop jobs before and after or use existing ones by amending the joining job’s requires

**Comment by dwmarshall** [comment]
FWIW, I don't think there should be any processing of YAML.

Where this would have greater utility would be to be part of a template so that the template's users don't need to do anything particularly special. It's trivially easy to create separate jobs to achieve the matrix effect, so we should be aiming for something more expansive.

Instead of having to write this:

```
jobs:
  main-default:
    requires: [~pr, ~commit]
    template: ruby/gem
    image: default
    environment:
      FOO: alpha
  main-ruby26:
    requires: [~pr, ~commit]
    template: ruby/gem
    image: ruby26
    environment:
      BAR: beta
  main-ruby27:
    requires: [~pr, ~commit]
    template: ruby/gem
    image: ruby27
    environment:
      BAZ: gamma
```

I might prefer to write something like this (with an example of how I might get the same environment affect):

```
jobs:
  main:
    requires: [~pr, ~commit]
    template: ruby/gem
    images:
      - default
      - ruby26
      - ruby27
  main-default:
    environment:
      FOO: alpha
  main-ruby26:
      BAR: beta
  main-ruby27:
      BAZ: gamma
```

The environment setting part needs to be thought out more, not quite sure my off-the-cuff idea is a good one.
