### ISSUE TITLE
[Moar] New Feature Request: Build Image If Absent

### ISSUE THREAD

**Issue by renaud-vmg** [screwdriver-cd/screwdriver#1313]
Just a so-far-deep-in-the-backlog suggestion.

```
jobs:
  a_job:
    image: some_docker_registry:443/a_namespace/a_docker_image:a_tag
    dockerfile: Dockerfile
    steps:
        - build: ./build_me
```

Per this configuration, a given job could look for a given image, and if none have been found per the configuration, using the Dockerfile, the job (or an external builder job) could use the Dockerfile to build the container, then ship it to the "current" build (that's been waiting all this time) for consumption.
