### ISSUE TITLE
Templates are validated with duplicate steps

### ISSUE THREAD

**Issue by Filbird** [screwdriver-cd/screwdriver#1317]
**What happened**:
A template was successfully validated via the `screwdriver-template-main` module despite having duplicate steps:

```
namespace: test
name: test
version: "1.0.0"
description: Test
maintainer: test@test.com
config:
  image: node:8
  steps:
    - hello: echo hello
    - hello: echo hello2
```

**What you expected to happen**:
The template should not be validated and the command should have thrown an error.

**How to reproduce it**:
Create a template with duplicate step values, see above^.

**Context**
The template is validated since we do not check for duplicates in our schema.
https://github.com/screwdriver-cd/data-schema/blob/52aba2d1a6ad195926c2f3d4b86b6eaf8c498f4b/config/job.js#L110

The fix is probably not as simple as using `Joi.array().unique()` since this method will attempt to do a deep copy of each object in the array rather than compare the names of the keys themselves.

Any job attempting to use a template containing duplicate steps will never start and throw a `Validaton error`. This is because our validator uses `screwdriver-config-parser` to handle the validation. This module will check for duplicate steps.
https://github.com/screwdriver-cd/config-parser/blob/ee84e486fdf50b768cae2cee6c5f41e92dda8ced/lib/phase/structural.js#L28
