### ISSUE TITLE
Manual trigger to continue a pipeline

### ISSUE THREAD

**Issue by yuichi10** [screwdriver-cd/screwdriver#1323]
**What happened**:
In some project, I want to deploy services after passed the test job and human check. Now when I try to create such pipeline, I need to put job require [], just for click trigger. 
That makes my pipeline complex. 

**What you expected to happen**:
I want another require component which is triggered by human click or I want to some human approval system to trigger next job.   

**How to reproduce it**:
Nothing.

**Comment by jithin1987** [comment]
@yuichi10 how do you propose human click to be captured ? Click trigger for Detached jobs is the human click/approval in my opinion.

**Comment by yuichi10** [comment]
In my image, I want to make the pipeline like below.
```
jobs:
  test:
    require: [ ~commit ]
    steps:
       - test: do test
  deploy:
    require: [ test, manual ]
    steps:
      - deploy: do deploy
``` 
In this pipeline,  it's deploy service after pass test job and human click.

Now If I try to do same thing. I need to create a pipeline like below
```
jobs:
  test:
    require: [ ~commit ]
    steps:
       - test: do test
  human-trigger:
    steps:
      - click: do click
  deploy:
    require: [ human-tigger, manual ]
    steps:
      - deploy: do deploy
```

If I require some human trigger, I need to put some detached job. This makes my pipeline look complex.

**Comment by yuichi10** [comment]
@jithin1987  sorry for my late response
In my image, I want to make the pipeline like below. (just example)
```
jobs:
  test:
    require: [ ~commit ]
    steps:
       - test: do test
  deploy:
    require: [ test, manual ]
    steps:
      - deploy: do deploy
``` 
In this pipeline,  it's deploy service after pass test job and human click.

Now If I try to do same thing. I need to create a pipeline like below
```
jobs:
  test:
    require: [ ~commit ]
    steps:
       - test: do test
  human-trigger:
    steps:
      - click: do click
  deploy:
    require: [ human-tigger, manual ]
    steps:
      - deploy: do deploy
```

If I require some human trigger, I need to put some detached job. This makes my pipeline look complex.

**Comment by yuichi10** [comment]
Also if, possible, I want approval system.
For example, when trigger `deploy job`, an Email is sent to the Product Owner or someone, and after the person is approve, the `deploy job` is start.

**Comment by tk3fftk** [comment]
I think it's like `input step` on Jenkins.
https://jenkins.io/doc/tutorials/create-a-pipeline-in-blue-ocean/#add-a-final-deliver-stage-to-your-pipeline
https://jenkins.io/doc/pipeline/steps/pipeline-input-step/

**Comment by jithin1987** [comment]
We can use existing functionality of "Start pipeline from here" for manually starting a job. 

The example in https://github.com/screwdriver-cd/screwdriver/issues/1323#issuecomment-428783954 will become like this

```
jobs:
  test:
    require: [ ~commit ]
    steps:
       - test: do test
  deploy:
    humanTrigger: true
    require: [ test ]
    steps:
      - deploy: do deploy
```

When Screwdriver executor sees `humanTrigger: true` config for a job, it does not start the job in a regular pipeline flow and marks it's status as `PAUSED`. When user clicks on the pipeline graph UI should show Continue message (refer screen

<img width="348" alt="screen shot 2018-10-14 at 3 14 42 pm" src="https://user-images.githubusercontent.com/193126/46922862-00dfb280-cfc4-11e8-9380-180cc2269481.png">
shot) 

Unlike "Start pipeline from here message" Continue pipeline should resume the same event, rather than creating a new event.
