### ISSUE TITLE
Always show pr and commit trigger

### ISSUE THREAD

**Issue by yuichi10** [screwdriver-cd/screwdriver#1344]
**What happened**:
Even there are no jobs which triggered from `~commit` or `~pr`, ui always show these two triggers. 

ex.)
```
jobs:
  main:
    image: node:6
    steps:
      - one_minitus: sleep 60
```
This screwdriver yaml's ui looks like below.
<img width="387" alt="2018-10-16 14 48 05" src="https://user-images.githubusercontent.com/4645011/46995180-86916880-d152-11e8-8364-76ba70b34e62.png">

**What you expected to happen**:
If there are no jobs triggered by `~commit` or `~pr`, do not need to show these two triggers.

**How to reproduce it**:
create pipeline which does not use `~commit` and `~pr` requires.
