### ISSUE TITLE
Feature to comment back to Git Pull Request from PR build

### ISSUE THREAD

**Issue by tijuj** [screwdriver-cd/screwdriver#1355]
**meta_set summary.{key} doesn't automatically add PR comments**:

**Earlier**:

setting meta.summary.{key} as below would add a PR comment 

```
pull-request:
        settings:
            DEPLOY: k8s
            sd_pr_comments: 'true'
        steps:
            postdeploy:
              description: "add instance to PR"
              command: |
                meta_set meta.summary.Instance `meta_get meta.instances.k8s`
                meta_set meta.summary.Build `meta_get meta.build`
                meta_set meta.summary.SHA "$_pull_request_sha"
```

would automatically add PR comments like -
<img width="786" alt="screen shot 2018-10-18 at 3 21 48 pm" src="https://user-images.githubusercontent.com/3414143/47187599-a73ff680-d2e9-11e8-99df-55dccbcbbdec.png">

It doesn't work anymore. 
Is there another way to do this? This feature was really helpful for code reviews and QA.
