### ISSUE TITLE
Branch filtering does not work for master branch

### ISSUE THREAD

**Issue by yoshwata** [screwdriver-cd/screwdriver#1364]
**What happened**:
In branch filtering pipline, PR job is not triggered when the pr is branched from `master`.

**What you expected to happen**:
Branch filtering works for `master` branch.

**How to reproduce it**:
1. Create pipeline like below
```
shared:
  image: node
  steps:
    - preinit: |
        echo "job: $SD_JOB_NAME"
  
jobs:
  build-pr:
    requires: [~pr:/^(master)$/]
  test-pr:
    requires: [~pr:/^(master)$/]

  build-pr2:
    requires: [~pr:master]
  test-pr2:
    requires: [~pr:master]
```
2. Create PR that the branch is from `master`

then the PR job is not triggered. Response from SD is `No jobs to start`.

**What I guessed**
- If a pipeline branch and filter result was same, `eventConfig.startFrom` is overwritten [here](https://github.com/screwdriver-cd/screwdriver/blob/99bd11fe16aa7c80bce75cdad5ef5d737ea573ed/plugins/webhooks/index.js#L178) with `~pr`.
- [getNextJobs](https://github.com/screwdriver-cd/workflow-parser/blob/7f001b2a30cb8ef86000b64e8abb245e15e08472/lib/getNextJobs.js#L28) return empty array
- [getJobsFromPR](https://github.com/screwdriver-cd/models/blob/a4369df3d71f9bb5a7fae9f278f4e2070d17d873/lib/eventFactory.js#L86) returns empty array
- [Promise](https://github.com/screwdriver-cd/models/blob/a4369df3d71f9bb5a7fae9f278f4e2070d17d873/lib/eventFactory.js#L206) returns empty array and throw `No jobs to start`
