### ISSUE TITLE
Build cache for PR jobs

### ISSUE THREAD

**Issue by d2lam** [screwdriver-cd/screwdriver#1382]
Currently, cache permission ties to pipeline/event/job ID. However, we need to treat PR jobs differently. 

For pipeline scoped cache: PR jobs should not have the ability to modify the pipeline cache, but they should still be able to `get` the cache. 
For job scoped cache: it does not matter since PR has its own job
For event scoped cache: it does not make sense to have event scoped cache in PRs, since each PR event is only 1 job

Related: https://github.com/screwdriver-cd/screwdriver/issues/1257

**Comment by catto** [comment]
I think PR jobs should pull in a cache from non-PR job so that each PR job will be faster.
For instance, non-PR test job (described below) stores npm cache every time. It is great if PR test jobs would get the cache from non-PR test job.
```yaml
cache:
  job:
    test: [ "~/.npm", "./node_modules" ]
jobs:
  test:
    template: nodejs/test
    requires: [ ~pr, ~commit ]
```

We're working on implementing triggering subsequent jobs for pull request (#1010), so there can be multiple jobs in a single event for pull request.
