### ISSUE TITLE
[feature request] User teadown works on template

### ISSUE THREAD

**Issue by yoshwata** [screwdriver-cd/screwdriver#1394]
**What happened**:
`teardown-*` step is not permitted when the pipeline uses template. user-teardown is very useful feature so I think it should be used  on many situation.

**What you expected to happen**:
use-teardown works on templates like below.
```
jobs:
  main:
    requires: [ ~pr, ~commit ]
    template: nodejs/test
    steps:
      - teardown-build: mkdir -p $SD_ARTIFACTS_DIR/logs/ && cp -r /root/.npm/_logs $SD_ARTIFACTS_DIR/logs
```

**How to reproduce it**:
Define use-teardown on pipeline that uses template.

**Comment by d2lam** [comment]
### Update 3/21/2019
Made a PR to address this issue. `config-parser` will consider user teardown steps and merge appropriately.

**Comment by d2lam** [comment]
This should be working now. 
Example screwdriver.yaml:
```
shared:
    image: node:6
jobs:
    main:
        template: template_namespace/nodejs_main@1.2.0
        steps:
            - teardown-write: echo hello
        requires: [~pr, ~commit]
```
<img width="604" alt="Screen Shot 2019-03-22 at 1 25 40 PM" src="https://user-images.githubusercontent.com/3401924/54851064-101b0880-4ca6-11e9-9359-cc32baef43fc.png">

Please let me know if there are any issues.
