### ISSUE TITLE
Badges are not computed properly if there are separate workflows for pipeline

### ISSUE THREAD

**Issue by jithin1987** [screwdriver-cd/screwdriver#1429]
## Context

Current badges logic assumes `pr` and `commit` workflow starts at same node and incorrectly assumes total workflow length to be [count of all workflow nodes](https://github.com/screwdriver-cd/screwdriver/blob/master/plugins/pipelines/badge.js#L89).  

Example

```
jobs:
  pull-request:
    requires: [~pr]
    steps:
      - build: echo "skip build"
  component:
    requires: [~commit]
    steps:
      - build: echo "build"

```

Above config will always result in the following URI path for badges `1 success, 1 unknown/lightgrey` because it incorrectly assumes that both the jobs will run for all event workflows.

## Objective

1. Compute correct workflow length by traversing the graph from `startFrom` node.
