### ISSUE TITLE
buildPeriodically affects PR builds

### ISSUE THREAD

**Issue by jeffreytolar** [screwdriver-cd/screwdriver#1441]
**What happened**:
This `screwdriver.yaml`:
```yaml
---
version: 4

shared:
  annotations:
    screwdriver.cd/buildPeriodically: H * * * *

jobs:
  main:
    image: centos:7
    requires: [~commit, ~pr]
    steps:
      - init: echo First steps
```
results in PRs building hourly, in addition to the regular build.

**What you expected to happen**:
PR builds ignore the `buildPeriodically` annotation

Note that this can be worked around by defining two jobs (using YAML anchors as needed), one with the annotation and one without.
