### ISSUE TITLE
screwdriver yaml for mono repo can grow big and hard to maintain

### ISSUE THREAD

**Issue by jithin1987** [screwdriver-cd/screwdriver#1455]
**What happened**:

`sourcePaths` feature which  is used to construct monorepo based workflow can result in a large `screwdriver.yaml` file depending on the number of sub projects in the repository. In order to better manage workflow of individual sub projects in a monorepo, separating out `screwdriver.yaml` configurations for the sub projects will result in smaller and maintainable workflow configuration files

**What you expected to happen**:

**How to reproduce it**:

**Comment by tkyi** [comment]
Would this feature basically be a way to specify where source code is?
Currently, `screwdriver.yaml` and all other files are relative to root. We could allow users to specify `root` in their screwdriver.yaml file. All files and things would be taken relative to that root.

```
jobs:
    main:
        image: node:6
        requires: [~pr, ~commit]
        root: "src/app/"
        steps:
            - echo: echo hi
```
