### ISSUE TITLE
Some users want to disable independent jobs

### ISSUE THREAD

**Issue by yokawara** [screwdriver-cd/screwdriver#1523]
## Context
Independent jobs would cause accidents by allowing users to run releasing builds without passing tests.
It would be better that users can choose to enable independent jobs or not.

 relates to: https://github.com/screwdriver-cd/screwdriver/issues/1497

### 2019/03/01 updated

We can reduce accidents caused by independent jobs by adding setting  (e.g. `
screwdriver.cd/restrictJobStart`) which controls independent jobs under pipeline-level annotation.
I assume specifications of the setting as below:
* put under a pipeline-level annotation like below
  ```
  annotations:
    screwdriver.cd/restrictJobStart: true
  jobs:
    test:
      requires: [~pr ~commit]
    deploy:
      requires: [ test ]
  ```
* if set to **`true`** or **not specified** (by default), all independent jobs in the pipeline are **disabled**
* if set to **`false`**, all independent jobs in the pipeline are **enabled**

**Comment by yokawara** [comment]
@jithin1987 What do you think of this feature? Please tell me if you have any concerns.

**Comment by tkyi** [comment]
I'm worried we're adding too many settings at the pipeline-level. Can we put the setting under a pipeline-level annotation? Something like:
```
annotations:
   screwdriver.cd/restrictJobStart: true
jobs:
   test:
       requires: [~pr, ~commit]
   deploy:
       requires: [test]
```
