### ISSUE TITLE
Pipeline page is broken by invalid YAML in PR with a template which uses image name templating

### ISSUE THREAD

**Issue by tk3fftk** [screwdriver-cd/screwdriver#1542]
**What happened**:
Pipeline page is broken and returns white page with 500.
This is caused by invalid YAML in PR  with a template which uses image name templating like a following snippet:

- template
```
name: nodejs/test
version: 0.1
description: This is the template for testing Node.js app. It executes npm install, build and test.
maintainer: hoge@fuga
config:
  Image: our.docker-registry.com:4443/node/node{{NODEJS_IMAGE_TAG}}:latest
  steps:
    - install: |
(snip)
```

- screwdriver.yaml
```
(snip)
    environment:
      NODEJS_IMAGE_TAG: {{NODE_VERSION}}
```

API log shows the below log when these settings are pushed.
```
[request,server,error] data: Error: "List of jobs" at position 3 fails because [child "List of job permutations" fails because ["List of job permutations" at position 0 fails because [child "image" fails because ["image" with value "our.docker-registry.com:4443/node/node{"[object Object]":null}:latest" fails to match the required pattern: /^[^;&|><*?`$()!#'" ]+$/]]]]
```

**What you expected to happen**:
Pipeline page should not be broken and only the PR job should be `parser-error`.

**How to reproduce it**:
- Create a template which uses image name templating.
- Use the template.
- Push an invalid YAML to any branch and open PR with the branch.
