### ISSUE TITLE
Validator does not validate notification plugin config

### ISSUE THREAD

**Issue by rafan** [screwdriver-cd/screwdriver#1549]
**What happened**:
Related to #1502, the validator says config like this:
```
shared:
    settings:
        email:
            addresses: [test@email.com, test2@email.com]
            statuses: [SUCCESS, FAILURE, UNSTABLE, AAA, BBB]

jobs:
    main:
       image: node
       steps:
          - a: b
```
is valid. While in reality, there are invalid statuses for the notification plugin. In my case, the notification plugin falls back to its default settings which does not notify me when build failed.

**What you expected to happen**:
Two things should happen: validator and screwdriver itself should reject the config, instead of failing silently.

**How to reproduce it**:
Put some invalid statuses to the notification plugin config.
