### ISSUE TITLE
[feature request] "shared" filtered by branch name or job name

### ISSUE THREAD

**Issue by yush1ga** [screwdriver-cd/screwdriver#1553]
I think it is useful to set "shared" value by branch or job name matching.

In our case, we want to get job failure notifications only when it is a deploy job.
Our `screwdriver.yaml` is like below now.

```yaml
shared:
  settings:
    slack:
      rooms: [ '#team-channel' ]

jobs:
  test:
    requires: [~pr, ~commit]
    template: some/test
    settings:
      slack: [] # this notification is unnecessary
  cluster1-deploy:
    requires: [ test ]
    template: some/deploy
  cluster2-deploy:
    requires: [ test ]
    template: some/deploy
```

I would be happy if I could set "shared" like below.

filtered by branch name
```yaml
shared:
  branch:
    master:
      settings:
        slack: [ '#team-channnel' ]
```

filtered by job name
```yaml
shared:
  job:
    '*-deploy':
      settings:
        slack: [ '#team-channel' ]
```
