### ISSUE TITLE
Validator does not validate invalid settings

### ISSUE THREAD

**Issue by anilkumarmyla** [screwdriver-cd/screwdriver#1574]
**What happened**:
Validator does not validate invalid `settings`

**What you expected to happen**:
Warning about invalid `settings`

**How to reproduce it**:
Plug this in into the validator 
```
shared:
  settings:
    email: [foo@bar.com]
    slack: [foo-bar]
    foo: bar

jobs:
  main:
    image: node
    steps:
      - step1: echo "step1"
```

Validator should ideally warn about `foo: bar` setting which doesn't do anything
<img width="550" alt="Screen Shot 2019-04-03 at 1 19 16 PM" src="https://user-images.githubusercontent.com/1934205/55510460-30868380-5613-11e9-90aa-8e1685999afe.png">
