### ISSUE TITLE
[Feature Request] Required/Optional environment feature for template

### ISSUE THREAD

**Issue by yoshwata** [screwdriver-cd/screwdriver#1644]
**What happened**:

Templates that we maintain has environments that must be set otherwise the jobs use the template will fail.
We set the default value like `REPLACE_ME` on `sd-template.yaml` to show users why the job fails.

```
environment:
  I_AM_REQUIRED: REPLACE_ME
```

The error message when a user not set required env is like below.
```
Request error: Get https://api.system.REPLACE_ME/v2/info: dial tcp: lookup api.system.REPLACE_ME on xxx.xxx.xxx.xxx:xx: no such host
```

**What you expected to happen**:

However, that is not essential measures.
My proposal is to enables to set whether the environment is reqiured or not.

It is just an idea of sd-template.yaml
```
environment:
  I_AM_REQUIRED:
    default:  ""
    required: true
  I_AM_OPTIONAL:
    default: ""
    required: false
```

Then, the error will be validation error, so users notice the fault at early stage.

**How to reproduce it**:
It is feature request and not bug.
