### ISSUE TITLE
Conditionally retry a step on failure

### ISSUE THREAD

**Issue by jithine** [screwdriver-cd/screwdriver#1645]
**What happened**:

Sometimes a step can fail because of external dependencies. There is no option to retry the command under different circumstances without restarting a new build or code changes. 

**What you expected to happen**:

Provide an option to conditionally retry failed steps.

1. Screwdriver workflow to provide a step config to specify that step must be retried.
1. Retry should support setting different environment variables.
1. Optionally provide a condition which should determine whether retry should happen or not.
1. For Screwdriver provided setup & teardown steps. cluster admins should be able to define the retry condition.
   1. User's can optionally specific `retry` condition without ability to override `command`
1. Provide means to easily add retry configuration to multiple steps

For example

```
steps:
 sd-setup-scm:
    command: git clone foo bar....
    retry: # object below or just `true`
      condition: $GIT_SHALLOW_CLONE == true # optional
      maxRetry: 3 # optional, default 1
      interval: 3 # optional, default 0 (second)
      environment: # optional
         GIT_SHALLOW_CLONE: false
```

**How to reproduce it**:

N/A

**Comment by jithin1987** [comment]
This is also related to https://github.com/screwdriver-cd/screwdriver/issues/1208 When making model changes we should keep both features in mind

**Comment by catto** [comment]
I really want this feature 👍  How about adding some useful keys and changing indentation?
```yaml
steps:
 sd-setup-scm:
    command: git clone foo bar....
    retry: # object below or just `true`
      condition: $GIT_SHALLOW_CLONE == true # optional
      maxRetry: 3 # optional, default 1
      interval: 3 # optional, default 0 (second)
      environment: # optional
         GIT_SHALLOW_CLONE: false
```
