### ISSUE TITLE
Shared steps are ignored if job steps are used

### ISSUE THREAD

**Issue by hk-vmg** [screwdriver-cd/screwdriver#1660]
**What happened**:
I added a wrap step in a shared block and in a job block. The shared wrap step was ignored.

**What you expected to happen**:
Both should be honored. This can be worked around with extra cut and paste (copy the shared steps into every job); it's not a blocker but does lead to unexpected behavior.

**How to reproduce it**:
Fails: (only "bar" is printed)
```
shared:
  template: FOO-with-init-and-build
  steps:
    - preinit: echo "foo"
jobs:
  component:
    requires: [ ~commit ]
    steps:
      - prebuild: echo "bar"
```

Works:
```
shared:
  template: FOO-with-init-and-build
  steps:
    - preinit: echo "foo"
    - prebuild: echo "bar"
jobs:
  component:
    requires: [ ~commit ]
```

Works:
```
shared:
  template: FOO-with-init-and-build
jobs:
  component:
    requires: [ ~commit ]
    steps:
      - preinit: echo "foo"
      - prebuild: echo "bar"
```
