### ISSUE TITLE
[Feature Request] Join trigger UI is not user friendly

### ISSUE THREAD

**Issue by yoshwata** [screwdriver-cd/screwdriver#1673]
## What happened
It is difficult to find why builds proceeds to next on join.

In the situation to use a pipeline like below:
```
shared:
  image: node:8
jobs:
  job1:
    requires: [ "~pr", "~commit" ]
    steps:
      - echo: echo 1
  job2:
    requires: [ "~pr", "~commit" ]
    steps:
      - echo: echo 2
  job3:
    requires: [ "job1", "job2", "detach"]
    steps:
      - echo: echo 3
  job4:
    requires: [ "job3" ]
    steps:
      - echo: echo 4
  detach:
    requires: []
    steps:
      - echo: echo detach
```

![Screen Shot 2019-06-10 at 13 29 14](https://user-images.githubusercontent.com/32473622/59180476-0962aa00-8ba0-11e9-810c-2425d7ab4a27.jpg)

### Procedure1: Trigger from ~commit

![Screen Shot 2019-06-10 at 13 00 50](https://user-images.githubusercontent.com/32473622/59180512-1d0e1080-8ba0-11e9-94de-5bf4ee6ce530.jpg)

Users cannot find why job3 is not trigger from UI.

### Procedure2: Trigger detached job

![Screen Shot 2019-06-10 at 13 17 06](https://user-images.githubusercontent.com/32473622/59180544-31eaa400-8ba0-11e9-87ba-d10ab7a18443.jpg)

![Screen Shot 2019-06-10 at 13 17 13](https://user-images.githubusercontent.com/32473622/59180565-3dd66600-8ba0-11e9-8f6d-adf41c8597ca.jpg)

It is surprising for users that the detached job triggers `job3` of the previous event created on `Procedure1`.

### Procedure3: Trigger detached job again

![Screen Shot 2019-06-10 at 13 36 30](https://user-images.githubusercontent.com/32473622/59180627-6199ac00-8ba0-11e9-98af-4b2741878137.jpg)

It is strange that nothing is triggered as following jobs for users (It triggered job3 previously)

## What you expected to happen
- UI shows why the job is not triggered or what is lacking as following jobs.
- UI shows what will happen after trigger actions by users' hand.

## Related
https://github.com/screwdriver-cd/screwdriver/issues/1358
