### ISSUE TITLE
Image override is awkward

### ISSUE THREAD

**Issue by hk-vmg** [screwdriver-cd/screwdriver#1686]
**What happened**:
The `shared` block is used for any un-set value in each job. However, `image` is both a top-level `shared` variable as well as a value contained within each `template`. This implies that:

works:
```
shared:
  template: A
jobs:
  a:
    # do A things, with A image
  b:
    template: B
    # do B things, with B image
```

doesn't work
```
shared:
  template: A
  image: A2
jobs:
  a:
    # do A things, with A2 image
  b:
    template: B
    # do B things - fails because image is A2
```
**What you expected to happen**:
`template` should be an object with sub-settings `name` and `image`, rather than a variable.
