### ISSUE TITLE
Steps override is awkward

### ISSUE THREAD

**Issue by hk-vmg** [screwdriver-cd/screwdriver#1693]
**What happened**:
A value defined in `jobs` will override a value defined in `shared`. However, `template` contains its own "steps" which are not overridden by `jobs`. This implies that a pipeline will work differently depending on whether the steps are defined in a template or not.

```
shared:
  steps:
    - foo: echo "foo"
jobs:
  a:
    steps:
      - foo: echo "Different foo"
```

```
shared:
  template: foo # contains steps: foo:
jobs:
  a:
    steps:
      - foo: echo "Different foo doesn't run"
```

**What you expected to happen**:
`jobs: XX: steps:` should behave consistently w.r.t. overrides, regardless of how steps are defined earlier. Specifically, either `template` steps should be overridden by `jobs` steps, or `shared` steps should not.

**How to reproduce it**:
