### ISSUE TITLE
Feature Request: Trigger build after pull request is closed

### ISSUE THREAD

**Issue by catto** [screwdriver-cd/screwdriver#1707]
**What happened**:
Some users deploy their apps every open pull request with `~pr` trigger and the apps would be named with each pull request number.
Once a pull request is merged or closed, no one takes care of temporarily deployed apps from pull request build. Then unused/abandoned apps retain on their infrastructure.

**What you expected to happen**:
Screwdriver triggers a build after each pull request is closed so that users can run teardown build and keep their compute cluster clean.

For example,
```
jobs:
    pullrequest:
        requires: ~pr
        image: node:8
        steps:
        - test: build and test
        - deploy: <deploy app using SD_PULL_REQUEST environment variable as its name>
        - check: <test against http://endpoint-pr-$SD_PULL_REQUEST.example.com>
    pr-teardown:
        # triggers after pr is closed
        requires: ~prclosed
        image: node:8
        steps:
        - teardown: <remove endpoint-pr-$SD_PULL_REQUEST.example.com app>
```
