### ISSUE TITLE
[Feature Request] Disable build cache with specific job

### ISSUE THREAD

**Issue by kumada626** [screwdriver-cd/screwdriver#1748]
**What happened**:
Currently, build cache scopes are event, pipeline and job.
I'd be nice if download build cache step can be skipped in the specific job for build speed up.

**What you expected to happen**:
Users can disable build cache in the specific job.

**Comment by yoshwata** [comment]
There are some solutions to fix this issue.

# Solutions1

This idea is to add new object `disable` or `enable` in `cache`.

## example1
```
cache:
  event:
    - $SD_SOURCE_DIR/node_modules
  pipeline:
    - ~/.npm
    - test.txt
  job:
    test: [/tmp/test-dir, /tmp/test.txt]
    publish: [publish.txt]
  disable:
    - job1
    - job2
```
All jobs other than job1 and job2 caches file at this case.

## example2

```
cache:
  event:
    - $SD_SOURCE_DIR/node_modules
  pipeline:
    - ~/.npm
    - test.txt
  job:
    test: [/tmp/test-dir, /tmp/test.txt]
    publish: [publish.txt]
  enable:
    - job3
```
Only job3 caches files at this case.

# Solutions2:

This idea enables cache level indication.

```
cache:
  event:
    - $SD_SOURCE_DIR/node_modules
  pipeline:
    - ~/.npm
    - test.txt
  job:
    test: [/tmp/test-dir, /tmp/test.txt]
    publish: [publish.txt]
  disable:
    event:
      - job2
  enable:
    pipeline:
      - job1
      - job3
```

And we have to handle it as an error; event should not to be put both `disable` and `enable`.

```
disable:
  event:
    - job2
enable:
  event:
    - job1
```

# Solution3:

example:
```
cache:
  event:
    - filename: $SD_SOURCE_DIR/node_modules
      enable:
        job1
        job3
  pipeline:
    - filename: ~/.npm
      enable:
        job2
    - filename: test.txt
      disable:
        job3
  job:
    test: [/tmp/test-dir, /tmp/test.txt]
    publish: [publish.txt]
```

This one is more flexible like:
- enable/disable setting for each files
- enambe/disable coexistence in a cache level

This solution breaks present specification, so users have to migrate their cache settings.

**Comment by yoshwata** [comment]
What do you prefer? I think solution1 is sufficient.

**Comment by wahapo** [comment]
I think it would be easier if I could control it in the job definition part.
```
cache:
  event:
    - $SD_SOURCE_DIR/node_modules

jobs:
  main:
    cache: false
    image: node:12
    steps:
      - ls $SD_SOURCE_DIR/
```

Even if users can control each cache level indication finely, I think that the impact on speed will be small. This is to speed up the build, so I don't think users need detailed control.
