### ISSUE TITLE
Branch filtering job clones code with default branch

### ISSUE THREAD

**Issue by kumada626** [screwdriver-cd/screwdriver#1755]
**What happened**:
There is a pipeline defined by below screwdriver.yaml
```
jobs:
  first:
    requires: ~commit:release
    image: foo
    steps:
      - bar: foo
  second:
    requires: first
    image: foo
    steps:
      - bar: foo
```
The `first` job is triggered by commit on release branch.
Then, the `first` job's build is executed with release branch source code.
After `first` job's build success, the `second` job is triggered.
However, the `second` job's build is executed with pipeline branch source code.
Because both builds are reset to same SHA, they are executed with same code.
But they are executed with different branch.

Because of this, if `mvn release:prepare` is executed in the `second` job, mvn commits to the pipeline branch not to the release branch.
**What you expected to happen**:
The `second` job also executed with release branch.

**How to reproduce it**:
1. Make pipeline by master branch.
2. Define branch filtering job and following job.
3. Execute branch filtered job with filtered branch (not master).
4.  Following job is triggered by branch filtered job.
5. Following job is executed with master branch.
