### ISSUE TITLE
Job chain do not work normally when job name start with trigger name.

### ISSUE THREAD

**Issue by sugarnaoming** [screwdriver-cd/screwdriver#1765]
**What happened**:
Job chain do not work normally when job name start with trigger name.
e.g.
``` yaml
# screwdriver.yaml
shared:
  image: centos/centos7:latest
jobs:
    commita:
        requires: [~commit]
        steps:
        - echo: echo 'commit'
    pra:
        requires: [~pr]
        steps:
        - echo: echo 'hoge'
    tag-a:
        requires: [ ~tag ]
        steps:
        - echo: echo "tag start"
    releasedriven:
        requires: [ ~release ]
        steps:
        - echo: echo "release start"
    main:
        requires: [ ~commita, ~pra, ~releasedriven, ~tag-a]
        steps:
        - echo: echo "main"
    aft:
        requires: [ ~main ]
        steps:
        - echo: echo 'after'
```
Validate image
![image](https://user-images.githubusercontent.com/10112441/65733937-b6d7da00-e10b-11e9-9d62-030d93e29be4.png)

**What you expected to happen**:
Job chain work normally even in a case job name start with trigger name.

**How to reproduce it**:
