### ISSUE TITLE
Looks like you can start with a job that exists only in require, but you can't actually

### ISSUE THREAD

**Issue by wahapo** [screwdriver-cd/screwdriver#1766]
**What happened**:
In the following yaml case, non-existent `dummy` job is displayed, and `No jobs to start.` is displayed when trying to start job.
```
jobs:
  main:
    requires: [ dummy ]
```

**What you expected to happen**:
I want to start from a `dummy` job. For example, use this when I want to start multiple detached jobs in one operation.
```
jobs:
  detached_1:
    requires: [ dummy ]
  detached_2:
    requires: [ dummy ]
```

Or, in order not to make useless expectations, it is necessary to remove that makes it seem that the job can be started from `dummy` job.

**How to reproduce it**:
1. Prepare the following screwdriver.yaml
    ```
    jobs:
      main:
        requires: [ dummy ]
        image: node:10
        steps:
          - ls: ls
    ```
1. Start pipeline from `dummy` job
![pipeline](https://user-images.githubusercontent.com/24538326/65742630-f1516f00-e12b-11e9-8e54-6fb90cd62030.png)
1. A modal window will appear, click `Yes`
![mordal](https://user-images.githubusercontent.com/24538326/65742662-1645e200-e12c-11e9-983f-221702655f46.png)
1. `No jobs to start.` is displayed
