### ISSUE TITLE
Pipelines that start with ~pr cannot trigger ~sd

### ISSUE THREAD

**Issue by wahapo** [screwdriver-cd/screwdriver#1780]
**What happened**:
Pipelines that start with `~pr` cannot trigger `~sd`.

**What you expected to happen**:
If there is no security problem, we want to trigger to `~sd` job.

**How to reproduce it**:
Create yaml like below.
```
annotations:
  screwdriver.cd/chainPR: true
jobs:
  main:
    requires: [ ~pr ]
```
```
annotations:
  screwdriver.cd/chainPR: true
jobs:
  test:
    requires: [ ~sd@1:main ]
```
