### ISSUE TITLE
feature request: Teardown Job

### ISSUE THREAD

**Issue by wahapo** [screwdriver-cd/screwdriver#1834]
Even if it fails in the middle of the pipeline, there are cases where I want to run a job at the end. If a job whose name starts with `teardown-` seems to run at the end of the pipeline, that is what I want.

For example, Screwdriver.cd temporarily stops notifications at the beginning of the pipeline and resumes when the pipeline ends regardless of success or failure.
```
jobs:
  main:
    requires: [ ~commit ]
    steps:
      - stop-mon: sd-cmd exec wahapo/monctl stop     // stop notifications
  deploy:
    requires: [ main ]
    ...

  teardown-myjob1:
    steps:
      - start-mon: sd-cmd exec wahapo/monctl start   // start notifications
```
