### ISSUE TITLE
Feature Request: ability to alias requires

### ISSUE THREAD

**Issue by dwmarshall** [screwdriver-cd/screwdriver#1843]
If I have a `requires` section such as:

``` 
requires:
      - ~pr
      - ~commit
      - ~sd@100:component 
      - ~sd@200:component
```

The pipeline will be  displayed with events labeled `sd@100:component` and `~sd@200:component`. I would like to be able to have those displayed with names of my choice, so that I don't necessarily need to remember what pipelines 100 and 200 are.

Maybe it could be something like this:

```
requires:
    - ~pr
    - ~commit
    - ~sd@100:component=foo
    - ~sd@200:component=bar
```

and then the events are displayed as `foo` and `bar`.

**Comment by dwmarshall** [comment]
An alternative might be to specify this as pipeline-level annotations:

```
annotations: 
  labels: 
    - 
      job: "~sd@100:component"
      label: foo
    - 
      job: "~sd@200:component"
      label: bar
```
