### ISSUE TITLE
PR comments are sent multiple times when using chainPR.

### ISSUE THREAD

**Issue by kumada626** [screwdriver-cd/screwdriver#1858]
**What happened**:
When using chain PR, the same PR comments are sent multiple times.
Add PR comments in the PR build, that PR comments are sent after that build finish, and after builds which is triggered by that build finish.

**What you expected to happen**:
The same PR comments are only sent once in one event. 

**How to reproduce it**:
1. prepare screwdriver.yaml like bellow.
```
annotations:
  screwdriver.cd/chainPR: true
jobs:
  pr-1:
    requires: ~pr
    image: node:10
    steps:
      - add-comment: meta set meta.summary.comment "Pull Request Comment"
  pr-2:
    requires: pr-1
    ...
```
2. Start `pr-1` build triggered by PR.
3. `pr-1` build finishes, pull request comment `Pull Request Comment` is sent to PR page and `pr-2` build is triggered.
4. `pr-2` build finishes, pull request comment `Pull Request Comment` is sent to PR page again.
