### ISSUE TITLE
Support custom secret management solutions

### ISSUE THREAD

**Issue by jithine** [screwdriver-cd/screwdriver#1863]
**What happened**:

Various organizations use their own centralized Secret Management tools. Certain Screwdriver steps, example - `sd-setup-scm` requires secrets to be stored via [Pipeline Secrets](https://docs.screwdriver.cd/user-guide/configuration/secrets)

It would be beneficial to users to complement native Secret management with custom solutions.

**What you expected to happen**:
Expose a mechanism to provide secrets using third party strategies.

For Example
```
jobs:
  main:
    requires: [~pr, ~commit]
    image: node:8
    steps:
      - echo: echo hi
    environment:
      SCM_CLONE_TYPE: https
    secretProvider: /bin/ckms-cli
    secrets:
      - SCM_USER
      - SCM_ACCESS_TOKEN
```

Behind the scenes `launcher` will execute `/bin/ckms-cli SCM_USER` to retrieve the secret

_This is just an example to demonstrate usage, we can fine tune actual configuration details._

**How to reproduce it**:

N/A
