### ISSUE TITLE
SD store memory eviction policy 

### ISSUE THREAD

**Issue by djerraballi** [screwdriver-cd/screwdriver#1875]
Using strategy memory, after a period of time the sd store becomes unresponsive. This appears to be due to the cache size limit reached. 

Using default parameters here: 
https://github.com/screwdriver-cd/store/blob/master/config/default.yaml#L34-L42

It appears i can configure an eviction policy (how long i want data to be kept in the cache), but could a LRU strategy allow this to fail more gracefully? Right now when build hit this issue they get stuck until i restart the store pod. 

```
2019/12/07 01:44:44 ERROR saving logfile: posting file "/sd/log.0507920881" to sd-setup-scm/log.0 after 6 retries: response code 503

2019/12/07 01:44:44 Uploading /sd/log.0507920881

2019/12/07 01:44:44 (Try 1 of 6) error received from file upload: response code 503

2019/12/07 01:44:45 (Try 2 of 6) error received from file upload: response code 503
...
```
```
data: Saving aptible-login/log.0 with headers {"x-request-id":"ab33e435a3b1cf3f979e8d63abcd50c9","content-type":"application/x-ndjson"}
data: Failed to store in cache: Error: Cache size limit reached
<store_url>: put /v1/builds/11570/aptible-login/log.0 {} 503 (2ms)
```

**Comment by djerraballi** [comment]
This actually causes a lot of wierd build behaviours too, the builds that are running in the cluster will get stuck sometimes, and a deletion of the store pod will recover things.

**Comment by jithine** [comment]
Is this when SD-in-a-box is used ?

**Comment by djerraballi** [comment]
No, this is running w/ a modified screwdriver helm chart: 

relavant values: 

```
store:
  image: screwdrivercd/store:v3.10.0
  replicas: 1
  # if s3 is not enabled, will use pod's memory to store logs, artifacts and that't non-persistent
  s3:
    enabled: false
    bucketName: <placeholder>
    region: us-west-2
    useAccessKey: true
```

and the store template:

```
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.env }}-sdstore
  namespace: {{ .Values.namespace }}
  labels:
    app: store
    env: {{ .Values.env }}
    tier: svc
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: store
    env: {{ .Values.env }}
    tier: app
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Values.env }}-sdstore
  namespace: {{ .Values.namespace }}
  labels:
    app: store
    env: {{ .Values.env }}
    tier: app
spec:
  replicas: {{ .Values.store.replicas }}
  selector:
    matchLabels:
      app: store
      env: {{ .Values.env }}
      tier: app
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: store
        env: {{ .Values.env }}
        tier: app
    spec:
      {{- if .Values.nodeselector.enabled }}
      nodeSelector:
        kops.k8s.io/instancegroup: {{ .Values.nodeselector.sdlabel }}
      {{- end }}
      containers:
      - env:
        - name: SECRET_JWT_PUBLIC_KEY
          valueFrom:
            secretKeyRef:
              key: jwtpublickey
              name: screwdriver-api-{{ .Values.env }}-secrets
        {{- if .Values.store.s3.useAccessKey }}
        - name: S3_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              key: keyid
              name: screwdriver-store-{{ .Values.env }}-secrets
        - name: S3_ACCESS_KEY_SECRET
          valueFrom:
            secretKeyRef:
              key: accesskey
              name: screwdriver-store-{{ .Values.env }}-secrets
        {{- end }}
        - name: S3_REGION
          value: {{ .Values.store.s3.region }}
        - name: S3_BUCKET
          value: {{ .Values.store.s3.bucketName }}
        - name: STRATEGY
          {{- if .Values.store.s3.enabled }}
          value: s3
          {{- else }}
          value: memory
          {{- end }}
        - name: BUILDS_EXPIRE_TIME
          value: "7776000000"
        - name: URI
          value: {{ template "store.uri" . }}
        - name: ECOSYSTEM_UI
          value: {{ template "ui.uri" . }}
        - name: S3_SIG_VER
          value: "v4"
        # Currently uses a private docker image because the updated version wasn't published yet
        image: {{ .Values.store.image }}
        imagePullPolicy: IfNotPresent
        name: screwdriver-store
        ports:
        - containerPort: 80
          protocol: TCP

```
