### ISSUE TITLE
screwdriver should cd back to source root after each step

### ISSUE THREAD

**Issue by jacobtolar** [screwdriver-cd/screwdriver#1889]
**What happened**:

With this configuration:
```
jobs:

  component:
    image: some-rhel-image
    steps:
      - test-cwd: mkdir -p foo && cd foo
      - test-pwd: pwd
```

the `test-pwd` step shows that the second step is executing inside `foo`. To me, this is counterintuitive (and also doesn't match the behavior of v3). 

**What you expected to happen**:

The working directory should be reset to the original root directory before each step.

IMO this is a bug. Would you accept a pull request to change this behavior in https://github.com/screwdriver-cd/launcher/blob/master/executor/executor.go ?
