### ISSUE TITLE
Validator results is not same with the /events

### ISSUE THREAD

**Issue by yoshwata** [screwdriver-cd/screwdriver#1900]
**What happened**:
The graph made by validator page does not match with the graph of UI(/events).
More specifically, the graph generated by validator has difference by each time.

**What you expected to happen**:
The graph generated by validator should be same with the graph of /events UI.

**How to reproduce it**:

Validate sd.yaml like below.
```
jobs:
  main:
    requires: [~pr, ~commit, ~sd@12345:publish]
    template: python/validate_type
  publish:
    requires: [main]
    template: python/validate_type
  deploy-dev:
    requires: [publish]
    template: python/validate_type
  deploy-tst01:
    template: python/validate_type
  deploy-tst02:
    requires: [deploy-tst01]
    template: python/validate_type
  deploy-stg01:
    template: python/validate_type
  deploy-stg02:
    requires: [deploy-stg01]
    template: python/validate_type
  deploy-prod01:
    template: python/validate_type
  deploy-prod02:
    requires: [deploy-prod01]
    template: python/validate_type
```

Sometime

![Screen Shot 2020-01-08 at 12 50 24](https://user-images.githubusercontent.com/32473622/71949112-a6a8be00-3215-11ea-9ffc-94f556d6cba2.jpg)

Another time

![Screen Shot 2020-01-08 at 12 50 51](https://user-images.githubusercontent.com/32473622/71949121-ae686280-3215-11ea-9ad9-f285bd97e8e7.jpg)

** Something related **

https://github.com/screwdriver-cd/screwdriver/issues/1604
https://github.com/screwdriver-cd/screwdriver/issues/1359
https://github.com/screwdriver-cd/ui/pull/399
