### ISSUE TITLE
[Feature Request] Disable "Start pipeline from here" for specific jobs

### ISSUE THREAD

**Issue by yoshwata** [screwdriver-cd/screwdriver#1901]
**What happened**:
Some users want to disable "Start pipeline from here button" for safety.

![Screen Shot 2020-01-08 at 16 51 15](https://user-images.githubusercontent.com/32473622/71959928-2eeb8b00-3237-11ea-87b9-ebd15aa04252.jpg)

**What you expected to happen**:
This is just an idea.

```
jobs:
  main:
    requires: [ pr, commit ]
    manualtrigger: disable
    steps:
        - steps: echo some important command
```
Then /event UI does not provide the button "Start pipeline from here" for `main` job.

**Comment by yoshwata** [comment]
Before getting into full swing, I revisited the naming.
How about idea below.

```
jobs:
  main:
    requires: [ pr, commit ]
    triggerWithUI: false
    steps:
        - steps: echo some important command
```

**Comment by wahapo** [comment]
Somehow, I have a feeling annotations of `screwdriver.cd/***` is more appropriate.
Our plan would be to make it impossible to not only start from the UI, but also from the API? If so, `startFromUI` would be a bit strange.

**Comment by yoshwata** [comment]
@wahapo Thank you.

> Somehow, I have a feeling annotations of screwdriver.cd/*** is more appropriate.

Actually, I was concerning from the same point of view as you. I add it as proposal 2. 

I think it's a trivial matter, but why did you think the idea was better?

# Proposal 2

```
jobs:
  main:
    requires: [ pr, commit ]
    annotations:
        startFromUI: false
    steps:
        - steps: echo some important command
```

**Comment by yoshwata** [comment]
> Our plan would be to make it impossible to not only start from the UI, but also from the API? If so, startFromUI would be a bit strange.

This is only for UI. Even if we do API matter, I think they should be able to be set individually.

**Comment by wahapo** [comment]
> I think it's a trivial matter, but why did you think the idea was better?

I believe that the settings of a job should only be related to the basic behavior. Users will find it easier to understand if the settings can be set in annotations, such as fine feature on/off and control of minor features, where the settings do not affect the outcome of the job.

**Comment by yoshwata** [comment]
> I believe that the settings of a job should only be related to the basic behavior. Users will find it easier to understand if the settings can be set in annotations, such as fine feature on/off and control of minor features, where the settings do not affect the outcome of the job.

I understood. Thanks.

**Comment by wahapo** [comment]
Users will have to do the following if they want to operate completely safely. Will the user need such delicate control?
```
jobs:
  main:
    requires: [ pr, commit ]
    annotations:
        screwdriver.cd/startFromUI: false
        screwdriver.cd/startFromAPI: false
    steps:
        - steps: echo some important command
```

**Comment by yoshwata** [comment]
> Users will have to do the following if they want to operate completely safely. Will the user need such delicate control?


In fact, I don't know. I haven't received any API requests from my users. So now I think it's enough to tackle the question of what name is appropriate when disabling it from the UI.

**Comment by tk3fftk** [comment]
> I think they should be able to be set individually.

@yoshwata what do you think it should be set individually for? I also think identifying a API call is from UI is a little complicated.

**Comment by yoshwata** [comment]
@tk3fftk 

> what do you think it should be set individually for? 

So far there is nothing but api and ui.

**Comment by yoshwata** [comment]
> I also think identifying a API call is from UI is a little complicated.

I hope the user knows that the annotation removes the item from the menu from the UI.

**Comment by yoshwata** [comment]
# Proposal 3

This idea disables both API and UI. The UI exists to call the API, so if it can be called by the UI, it should be operable by the API.

```
jobs:
  main:
    requires: [ pr, commit ]
    annotations:
        screwdriver.cd/startManually: false
    steps:
        - steps: echo some important command
```

For this case, other candidates of annotations:
`manualTrigger`
`triggerOnly`

**Comment by yoshwata** [comment]
# Proposal 4

This idea is come from GitLab's `when`. The default setting is:
```
jobs:
  main:
    requires: [ pr, commit ]
    annotations:
        screwdriver.cd/when:
            - on_success
            - manual
    steps:
        - steps: echo some important command
```
User can overwrite it to disable manual starting.
