### ISSUE TITLE
Jobs that wait for the join condition to be satisfied cannot be stopped

### ISSUE THREAD

**Issue by wahapo** [screwdriver-cd/screwdriver#1915]
**What happened**:
Jobs that do not meet the join condition cannot be stopped and remain created status.
<img width="400" src="https://user-images.githubusercontent.com/24538326/72578046-3803e880-3918-11ea-838d-aa3df1682cc4.png">

**What you expected to happen**:
I want to stop the jobs that are waiting to be join.

**How to reproduce it**:
```
shared:
  image: node:10

jobs:
  job1:
    requires: ~commit
    steps:
      - ls
  job2:
    requires: ~commit
    sourcePaths: [ foo.txt ]
    steps:
      - ls
  job3:
    requires: [ job1, job2 ]
    steps:
      - ls
```
(Notes: File `foo.txt` does not exist)

If you build with the above yaml, it will look like the following figure.
<img width="1000" src="https://user-images.githubusercontent.com/24538326/72577885-9a101e00-3917-11ea-975b-fd82914fec63.png">

Show the details page of job3.
