### ISSUE TITLE
Screwdriver Store w/ S3 strategy fails to start

### ISSUE THREAD

**Issue by djerraballi** [screwdriver-cd/screwdriver#1934]
Running into issues when attempting to setup the store w/ s3:
```
> screwdriver-store@3.10.0 start /usr/src/app/node_modules/screwdriver-store
> ./bin/server
[winston] Attempt to write logs with no transports {"level":"error"}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! screwdriver-store@3.10.0 start: `./bin/server`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the screwdriver-store@3.10.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?
```
Is there anything special that needs to be done w/ the S3 bucket configuration to make s3 strategy work? 
Based on the error its notclear that the failure is happening w/ aws.js or the s3 setup, however the store comes up fine when using the memory strategy

The variables i am using for configuration are the following:
```
store:
  image: screwdrivercd/store:v3.10.0
  replicas: 1
  # if s3 is not enabled, will use pod's memory to store logs, artifacts and that't non-persistent
  s3:
    enabled: true
    bucketName: <my_bucket_name>
    region: us-west-2
    useAccessKey: true
```

and the deployment describe results: 
```
Containers:
   screwdriver-store:
    Image:      screwdrivercd/store:v3.10.0
    Port:       80/TCP
    Host Port:  0/TCP
    Environment:
      SECRET_JWT_PUBLIC_KEY:  <set to the key 'jwtpublickey' in secret 'screwdriver-api-prod-secrets'>  Optional: false
      S3_ACCESS_KEY_ID:       <set to the key 'keyid' in secret 'screwdriver-store-prod-secrets'>       Optional: false
      S3_ACCESS_KEY_SECRET:   <set to the key 'accesskey' in secret 'screwdriver-store-prod-secrets'>   Optional: false
      S3_REGION:              us-west-2
      S3_BUCKET:              <my_bucket_name> 
      STRATEGY:               s3
      BUILDS_EXPIRE_TIME:     7776000000
      URI:                    <my uri>
      ECOSYSTEM_UI:           <my_uri>
      S3_SIG_VER:             v4
    Mounts:                   <none>
```
