### ISSUE TITLE
Underscore disappears when storing number with underscore in meta

### ISSUE THREAD

**Issue by wahapo** [screwdriver-cd/screwdriver#1993]
**What happened**:
Underscore disappears when storing number with underscore in meta. There is a possibility that [this specification change](https://go.googlesource.com/go/+/b97ec8e57f7a27eea76814bad5c74aa8f0617bb6) is affecting.
<img width="200" src="https://user-images.githubusercontent.com/24538326/75646888-7cf89a00-5c8e-11ea-8118-f02761b41f52.png">
<img width="200" src="https://user-images.githubusercontent.com/24538326/75646866-6c482400-5c8e-11ea-8366-0f33058b6971.png">

**What you expected to happen**:
```
$ meta set MYKEY 0_1_2
$ echo `meta get MYKEY`
0_1_2
```

**How to reproduce it**:
Create this `screwdriver.yaml` and run pipeline.
```
jobs:
  main:
    requires: [ ~pr, ~commit ]
    image: node:10
    steps:
      - meta set MYKEY 0_1_2
      - echo `meta get MYKEY`
```
