### ISSUE TITLE
Filtering for ~release and ~tag triggers

### ISSUE THREAD

**Issue by edudar** [screwdriver-cd/screwdriver#1994]
**What happened**:
Both triggers fire on any release or tag being pushed. This creates an issue with repositories and pipelines where modules have different release 'schedule' and one may want to release one module but skip that for the other one.

**What you expected to happen**:
Introduce release and tag id filtering similar to branch filtering:
```
  release-one:
    requires: [~release:/^release-one-/]
    steps:
      - echo: release-one
  release-two:
    requires: [~release:/^release-two-/]
    steps:
      - echo: release-two
  tag-one:
    requires: [~tag:/^tag-one-/]
    steps:
      - echo: tag-one
```
