### ISSUE TITLE
Jobs triggered by ~release and ~tag should honor sourcePaths changes in commit

### ISSUE THREAD

**Issue by edudar** [screwdriver-cd/screwdriver#1995]
**What happened**:
In the following configuration, a build job is triggered upon a commit but when release is created afterward, trigger fires but no jobs start as a result.
```
jobs:
  client:
    requires: [~pr, ~commit]
    sourcePaths: ['commons/', 'client/']
    steps:
      - compile: ...
      - test: ...
  client-release:
    requires: [~release]
    sourcePaths: ['commons/', 'client/']
    steps:
      - publish: ...
```

<img width="451" alt="Screen Shot 2020-03-02 at 9 47 47 AM" src="https://user-images.githubusercontent.com/584181/75702810-0ac28e00-5c6b-11ea-96cf-776f09179ba8.png">

**What you expected to happen**:
Pipeline triggered on release should honor the same config and take `sourcePaths` on commit and start appropriate jobs
