### ISSUE TITLE
chainPR does not trigger next job when restarts PR build

### ISSUE THREAD

**Issue by kumada626** [screwdriver-cd/screwdriver#2029]
**What happened**:
We made a pipeline that uses chainPR feature like following.
```
annotations:
  screwdriver.cd/chainPR: true
shared:
  image: node:12
jobs:
  job1:
    requires: [ ~pr ]
    steps:
    ....
  job2:
    requires: [ job1 ]
    steps:
    ...
```
The `job1` is triggered by making PR and fails.
After that, we restart the `job1` manually.
The `job2` is not triggered even if the `job1` success.

**What you expected to happen**:
The `job2` is triggered when the `job1` success.

**How to reproduce it**:
1. Make a pipeline that uses chainPR feature.
2. Triggers PR build and fails its build.
3. Manually restart that build.
4. Build is not triggered that requires restarted build.
