### ISSUE TITLE
Jobs that can not start should not show `start pipeline from here`

### ISSUE THREAD

**Issue by yoshwata** [screwdriver-cd/screwdriver#2038]
**What happened**:

Jobs that can not start is shown as if it seems to be able to start.

**What you expected to happen**:

Jobs that can not start should not show `start pipeline from here`

**How to reproduce it**:

1. Make pipline using `detached job` and `chain PR` like below
```
annotations:
  screwdriver.cd/chainPR: true
shared:
  image: node:10
jobs:
  main:
    requires: [ "~pr", "~commit" ]
    steps:
      - echo: echo 'foo'
  detached:
    requires: []
    steps:
      - echo: echo 'bar'
```
2. Make PR event
3. `start pipeline from here` shown on bubble of job `detached` on the PR event.
4. Click `start pipeline from here`, but it becomes `no jobs to start`

**relevant issue**
https://github.com/screwdriver-cd/screwdriver/issues/1766
