### ISSUE TITLE
Re-considering local config in  sd-local

### ISSUE THREAD

**Issue by kkokufud** [screwdriver-cd/screwdriver#2050]
**What happened**:
We had feedback for [local config](https://github.com/screwdriver-cd/screwdriver/blob/master/design/sd-local.md#options-1) in sd-local.
- It's hard for users to understand the use case.
  - Originally, we thought that `local` option is needed in the environment which has some clusters. 
- The name of `local` option is not good because it's the same as `sd-local`.

**What you expected to happen**:
We would like to re-consider the design of a new feature instead of `local` config.

**Comment by kkokufud** [comment]
## design

In order to support multiple clusters, we propose a concept like kubectl context.
To do this, we need to change the config file as follows.

### config file
```
configs:
  default:
    api-url: 
    store-url: 
    token: 
    launcher:
      version: latest
      image: screwdrivercd/launcher
  abc:
    api-url: https://api-cd.sample.com
    store-url: https://store-cd.sample.com
    token: hoge
    launcher:
      version: latest
      image: screwdrivercd/launcher
  def:
    api-url: https://api-cd.sandbox.com
    store-url: https://store-cd.sandbox.com
    token: fuga
    launcher:
      version: latest
      image: screwdrivercd/launcher
current: abc
```
- `configs` is a map. The key is name of config, the value is specific config.
- `current` is current config name.
- `default` config is created  automatically.

### command usage
- To create a new config,  we use `sd-local config create ghe`.
- To change a current config, we use `sd-local config use abc`
- To set a config parameter, we use `sd-local config set` as before.
- `sd-local config view` outputs all of config, and `sd-local config view abc` outputs specific config.

**Comment by yoshwata** [comment]
I agree that it is hard to understand what sd-local's `local` option for

**Comment by sugarnaoming** [comment]
I have two questions.
- When is the `default` created?
- What will happen if the name is the same as the existing config name when the `create` command is executed?

**Comment by kkokufud** [comment]
> When is the default created?

This is the timing when .sdlocal/config is created.

> What will happen if the name is the same as the existing config name when the create command is executed?

It returns an error.
If you have any other things, please comment.

**Comment by sugarnaoming** [comment]
> >What will happen if the name is the same as the existing config name when the create command is executed?
>
> It returns an error.

Ok.
I think that's fine with me too.

> > When is the default created?
>
> This is the timing when .sdlocal/config is created.

I think it's redundant to create `default` even if the user runs `sd-local config create hoge` first.

An additional question, do you create a command to delete the config?

**Comment by kkokufud** [comment]
> I think it's redundant to create default even if the user runs sd-local config create hoge first.
I think so. 
> An additional question, do you create a command to delete the config?
Yes.

We fixed it.

**Comment by sugarnaoming** [comment]
> > I think it's redundant to create default even if the user runs sd-local config create hoge first.
> 
> I think so.
> 
> > An additional question, do you create a command to delete the config?
> 
> Yes.
> 
> We fixed it.

Thank you.

I have the following questions about the behavior of `delete`:
- What happens if I delete a config that is set to `current`?
- Would it be acceptable to remove all the configs?
- Is it okay with the behavior that returns an error if you delete a non-existent config? (I'm thinking it's okay.)

I'm sorry for asking so many questions.

**Comment by s-yoshika** [comment]
I think the current config should not be deleted. What if it can be deleted, `current` will point undefined config and the config file will be corrupted.

**Comment by sugarnaoming** [comment]
> I think the current config should not be deleted. What if it can be deleted, `current` will point undefined config and the config file will be corrupted.

Thank you.
So it looks good.

The following are suggestions.
- In the current configuration commands, tokens and other settings are assumed to be inputted sequentially from the command line.
This way, the token will be recorded in the shell's command history.
Add an interactive mode to avoid being recorded in the command history. (I'm assuming it's like entering a password in MySQL.)

- There is an "XDG Base Directory" specification for config files and other directories, so you might want to try and re-examine the location of your config files. 

Ref
- [XDG Base Directory](https://specifications.freedesktop.org/basedir-spec/latest/index.html#introduction)
- [Archlinux wiki](https://wiki.archlinux.org/index.php/XDG_Base_Directory)

**Comment by s-yoshika** [comment]
We might have to consider the case that users already used sd-local and the format of their config file will be out of date. It is more better to support migrating from old one, and if we do it, `default` config might be useful for the place to migrate.

**Comment by s-yoshika** [comment]
config viewの形式はどうするか？
- kubectl config view形式
  - 全情報をcatのように表示するだけ
  - デフォルトではcurrentだけ出して, -aオプションで全だしとかの方法もある
- kubectl config get-contexts形式 <- 現在のsd-local config viewはこっち
  - URL系が長くなるので全部出すとフォーマットが崩れそう
  - tokenとかは常に出さなくても良いのでオプションでだし分けとかの方法もある
- kubectl config view & kubectl config get-contexts（こっちはcurrentとnameだけになりそう）
- ifconfig的な表示にしてcurrentのconfigには*をつける

ifconfig案
```
$ sd-local config view
*  default:
    api-url: 
    store-url: 
    token: 
    launcher:
      version: latest
      image: screwdrivercd/launcher
  abc:
    api-url: https://api-cd.sample.com
    store-url: https://store-cd.sample.com
    token: hoge
    launcher:
      version: latest
      image: screwdrivercd/launcher
  def:
    api-url: https://api-cd.sandbox.com
    store-url: https://store-cd.sandbox.com
    token: fuga
    launcher:
      version: latest
      image: screwdrivercd/launcher
$ sd-local config view abc
  abc:
    api-url: https://api-cd.sample.com
    store-url: https://store-cd.sample.com
    token: hoge
    launcher:
      version: latest
      image: screwdrivercd/launcher
$ sd-local config view default
*  default:
    api-url: 
    store-url: 
    token: 
    launcher:
      version: latest
      image: screwdrivercd/launcher
```

sd-local config view <config-key>はいる？
=> まずは最小の機能だけ考えて不要,全表示だけ

sd-local config setにconfig名を指定できるようにしたい
```
* $ sd-local config set <key> <value>
$ sd-local config set <config-name> <key> <value>
$ sd-local config set [--name=<config-name>] <key> <value>
```
上はcurrentに対してsetする（currentにuse configしてから書き換える）
=> 現在のコマンドとの互換性もあるし、後からnameオプションを増やすこともできる
=> いったんこっちでやる
下の案の場合はconfig-nameはデフォルトでcurrentのconfig


tokenは秘匿しなくて大丈夫か？mysql -pみたいにinteractiveな形式で渡せると良いかも

この機会にconfigディレクトリをxdg形式に合わせたい

**Comment by s-yoshika** [comment]
# 2020/04/06

## background
Users who use multple clusters in their environment would like to switch the configs of sd-local in each clusters. 

## Objective
So we have to re-consider the config command to support multiple configs.

## design

### The format of the config file
We have to scratch the format of the config file to support multiple configs.
We are going to update the format like following.

**Before**:
```
api-url: https://your-api-screwdriver.com
store-url: https://your-store-screwdriver.com
token: yourtoken
launcher:
  version: latest
  image: screwdrivercd/launcher
```
**After**:
```
configs:
  default:
    api-url: 
    store-url: 
    token: 
    launcher:
      version: latest
      image: screwdrivercd/launcher
  yourConfigName:
    api-url: https://your-api-screwdriver.com
    store-url: https://your-store-screwdriver.com
    token: yourtoken
    launcher:
      version: latest
      image: screwdrivercd/launcher
....
current: default
```

- `configs` has some entries which represent the map which has a config name as key and a config itself as value. The format of each config is same as before.
- `current` points to the current config with which the user are using.
- `default` config is a special config which are created automatically when the first time the user use sd-local
  - but `default` is not created if the user create a config explicitly with `sd-local config create <config-name>` in the first time, and, the specified name is used instead of `default`.
- `current` points to `default` (or first created config) in the first time

### The list of sub command in config command
- `sd-local config create <config-name>`
  - Creates a new config
- `sd-local config delete <config-name>`
  - Deletes a existing config
- `sd-local config use <config-name>`
  - Switch `current` to specified config
- `sd-local config set <key> <value>`
  - Update the settings of the current config with key and value
- `sd-local config view`
  - Output the whole config, the format is described later

### The format of output in `sd-local config view`
The output format in `sd-local config view` looks like this:
```
*  cluster1:
      api-url: https://cluster1-api-screwdriver.com
      store-url: https://cluster1-store-screwdriver.com
      token: hoge
      launcher:
        version: latest
        image: screwdrivercd/launcher
   cluster2:
     api-url: https://cluster2-another-api-screwdriver.com
     store-url: https://cluster2-another-store-screwdriver.com
     token: fuga
     launcher:
       version: latest
       image: screwdrivercd/launcher
```
In above example, you can see you have 2 configs, cluster1 and cluster2,  and the `cluster1` is set as `current`.
