### ISSUE TITLE
Users cannot notice statuses errors in notification settings.

### ISSUE THREAD

**Issue by ibu1224** [screwdriver-cd/screwdriver#2051]
**What happened**:
Currently, I can not notice the setting mistake of the notification of screwdriver.yaml.

**What you expected to happen**:
Users need to be aware of any mis-configuration in some way.
**How to reproduce it**:
Wrong settings, screwdriver.yaml
e.g.
```yaml
  shared:
    image: node:10
    settings:
      slack:
        channels:
          - ibu1224-test-channel
        statuses:
          - SUCCCESS <---  typo
          - FAILURE
```
