### ISSUE TITLE
[Feature request] Mistake of annotations is hardly noticeable

### ISSUE THREAD

**Issue by yoshwata** [screwdriver-cd/screwdriver#2053]
# What happened

An example of screwdriver.yaml is below.

```yaml
shared:
  annotations:
    screwdriver.cd/chainPR: true
    screwdriver.cd/cpu: MICRO

jobs:
  job01:
    image: node:10
    requires: [ ~pr, ~commit ]
    steps:
      - echo: echo hoge
  job02:
    image: node:10
    requires: [ job01 ]
    steps:
      - echo: echo hoge
```

`chainPR` is Pipeline-Level Annotations, so chainPR is not configured to the pipeline becaseu it is the `shared` setting.
The user can find it after pipeline starts because `annotation` is free format object, and validator does not warn it as invalid.

# What you expected to happen

The user can find annotation's mistake from feedback of UI.

# How to reproduce it

Starts the pipeline of which screwdriver.yaml is below

```yaml
shared:
  annotations:
    screwdriver.cd/chainPR: true
    screwdriver.cd/cpu: MICRO

jobs:
  job01:
    image: node:10
    requires: [ ~pr, ~commit ]
    steps:
      - echo: echo hoge
  job02:
    image: node:10
    requires: [ job01 ]
    steps:
      - echo: echo hoge
```

`chainPR` is not configured, but no one warns about it.

# relevant
[Validator should validate buildPeriodically syntax · Issue #1611 · screwdriver-cd/screwdriver](https://github.com/screwdriver-cd/screwdriver/issues/1611)
[Settings should be namespaced · Issue #534 · screwdriver-cd/screwdriver](https://github.com/screwdriver-cd/screwdriver/issues/534)
[Support Annotations for Feature Configuration · Issue #580 · screwdriver-cd/screwdriver](https://github.com/screwdriver-cd/screwdriver/issues/580)
