### ISSUE TITLE
[Feature request] Select input values for build parameters

### ISSUE THREAD

**Issue by wahapo** [screwdriver-cd/screwdriver#2057]
**What happened**:
This is a request from users in YJ.
- I want to be able to select frequently used values.
- If want to use the same parameters as in the past build, copy and paste is cumbersome, so I want to be able to select the parameters used in the past.

**What you expected to happen**:
I think it can be solved by the following two features.

_feature 1_
I want to be able to define multiple default values and select them when using them.
```
parameters:
  - region: "us-west-1"
    az:
      value: "1"
      description: "default availability zone"
  - region: "us-east-1"
    az: "2"
```

_feature 2_
It is cumbersome to copy and paste each parameter one by one, so we can solve it by making it possible to copy and paste all at once. So, I want to be able to easily reuse build parameters used in the past.
<img width="800" src="https://user-images.githubusercontent.com/24538326/78539258-379b2f80-782d-11ea-800a-0841b6b28ae2.png">
