### ISSUE TITLE
Validator not reflects external join workflow graph

### ISSUE THREAD

**Issue by kumada626** [screwdriver-cd/screwdriver#2091]
**What happened**:
Validator and pipeline workflow graphs are different when using the external join function.

**What you expected to happen**:
Validator and pipeline show same workflow graph.

**How to reproduce it**:
1. Make screwdriver.yaml like below.
```
jobs:
  main:
    requires: [~commit, ~pr]
  internal_fork:
    requires: [main]
  join_job:
    requires: [internal_fork, sd@9:external_fork, sd@10:external_fork]
```

2. Pipeline's workflow graph like below.
<img width="480" alt="スクリーンショット 2020-05-20 10 56 09" src="https://user-images.githubusercontent.com/8113204/82396329-9983c180-9a88-11ea-8ddd-c9e7392a7d22.png">

3. Validator's workflow graph like below
<img width="517" alt="スクリーンショット 2020-05-20 10 57 05" src="https://user-images.githubusercontent.com/8113204/82396364-aef8eb80-9a88-11ea-9017-f881019acdb5.png">
