### ISSUE TITLE
[Feature Request] Drop-down values in parameters

### ISSUE THREAD

**Issue by dwmarshall** [screwdriver-cd/screwdriver#2092]
I'd like to define discrete values that are available for parameters such that they are selected by a drop-down list.

I have parameters to define which command or template to promote, so I'd like something such as:

```
parameters:
  resource: ["commands/publish", "templates/mock", "templates/tito"]
  from: ["latest", "test"]
  to: ["test", "stable"]
```
