### ISSUE TITLE
Remote trigger does not create new event.

### ISSUE THREAD

**Issue by yoshwata** [screwdriver-cd/screwdriver#2131]
# What happened
Remote trigger triggering the pipeline itself does not create new event when trigger source has 2 chained jobs.

# What you expected to happen
New event is created for remote trigger's destination.

# How to reproduce it

Create pipeline with sd.yaml like below.
```
shared:
  image: node10:latest
jobs:
  job1:
    requires: [ ~pr, ~commit ]
    steps:
      - echo: echo hoge
  job2:
    requires: [ job1 ]
    steps:
      - echo: echo hoge
  self-remote:
    requires: [ ~sd@130673:job2 ]
    steps:
      - echo: echo fuga
```

Then, run build but every jobs are started on single event.
![Screen Shot 2020-06-29 at 14 03 50](https://user-images.githubusercontent.com/32473622/85974807-66cad280-ba11-11ea-95ea-72bcd2018e7a.jpg)

There is no problem if remote trigger is triggered from `job1`.  In that case events are divided into 2 events of source and destination like below.

Source event:
![Screen Shot 2020-06-29 at 14 27 39](https://user-images.githubusercontent.com/32473622/85976166-d9897d00-ba14-11ea-91a0-33c6f847d375.jpg)

Dest event:
![Screen Shot 2020-06-29 at 14 27 48](https://user-images.githubusercontent.com/32473622/85976187-e27a4e80-ba14-11ea-8148-761fec030045.jpg)

This behavior is important when publishing and testing templates. Test job does not load the newest template if everything is put together into single event.
