### ISSUE TITLE
Self remote trigger is not triggered on the first commit.

### ISSUE THREAD

**Issue by yoshwata** [screwdriver-cd/screwdriver#2132]
**What happened**:
The commit to add a job which is triggered from self remote trigger does not trigger the new remote trigger.

**What you expected to happen**:
Remote trigger is triggered from the commit to add the job as another event.

**How to reproduce it**:
Create pipeline(id: 1030673) with sd.yaml below
```
shared:
  image: node10:latest
jobs:
  job1:
    requires: [ ~pr, ~commit ]
    steps:
      - echo: echo hoge
```

Then fix like this, add a job triggered from self remote trigger
```
shared:
  image: node10:latest
jobs:
  job1:
    requires: [ ~pr, ~commit ]
    steps:
      - echo: echo hoge
  self-remote:
    requires: [ ~sd@130673:job1 ]
    steps:
      - echo: echo fuga
```

The commit do not start self-remote job.

**Supplements**
There is no problem if it was started by `Start` button UI.
