### ISSUE TITLE
Inconsistent Event Cache

### ISSUE THREAD

**Issue by dwmarshall** [screwdriver-cd/screwdriver#2136]
**What happened**:

If jobs running in parallel modify the event cache, the resulting cache will be overwritten by the job that finishes last.

**What you expected to happen**:

I expect each job's changes to the event cache to be merged with parallel jobs' changes to the event cache. For the pipeline below, I expect `$SD_ROOT_DIR/cache` to have `one` and `two` when `three` lists the files.

Suggested mechanism:

Use a read/write lock. When a job starts, it waits for a read lock, reads any caches, and releases the read lock. When it is done (possibly only the cache is dirty), it gets a write lock, reads the cache, overlays its changes to the cache, writes the new cache contents, and then releases the write lock.

**How to reproduce it**:

Use this `screwdriver.yaml`:

```
shared:
  image: screwdrivercd/noop-container

cache:
  event: [$SD_ROOT_DIR/cache]

jobs:
  one:
    requires: [~commit]
    steps:
      - one: |
          sleep 30
          mkdir -p $SD_ROOT_DIR/cache
          echo "I am one" > $SD_ROOT_DIR/cache/one
  two:
    requires: [~commit]
    steps:
      - two: |
          sleep 300
          mkdir -p $SD_ROOT_DIR/cache
          echo "I am two" > $SD_ROOT_DIR/cache/two
  three:
    requires: [one, two]
    steps:
      - three: |
          ls -l $SD_ROOT_DIR/cache
```

In almost every run, job `three` will have file `two` but not `one`.

**Comment by tanoda** [comment]
I think a build cache should not be as stateful storage beyond builds.
When we use the build cache, I think we want to speed our builds up. If we need to download twice and overlay, it can make builds slower than no cache.
(And I didn't agree "overlay" the cache. because we can't delete any files.)

I think your problem should be resolved by adding the fourth job: it joins all three jobs and retrieves artifacts from them.

**Comment by dwmarshall** [comment]
In this instance, I am using it to share information between jobs and not to speed anything up. I agree that such is not the typical use case for a cache.

Note that the cache would need to be downloaded twice only if the cache has been modified, which is under the control of the the pipeline.

Perhaps better documentation is indicated to specify whether it's a valid use case to create a file in one job that becomes available to another job via the event cache. We should produce a better description of the exact operation of the various caches and what are its envisioned use cases.

**Comment by jithine** [comment]
cc @parthasl

**Comment by parthasl** [comment]
@dwmarshall Sorry for the delayed reply. It should work as expected if the cache is stored at leaf level.

```yaml
shared:
  image: screwdrivercd/noop-container

cache:
  event:
    - $SD_ROOT_DIR/cache/one
    - $SD_ROOT_DIR/cache/two

jobs:
  one:
    requires: [~commit]
    steps:
      - one: |
          sleep 30
          mkdir -p $SD_ROOT_DIR/cache/one
          echo "I am one" > $SD_ROOT_DIR/cache/one/one
  two:
    requires: [~commit]
    steps:
      - two: |
          sleep 300
          mkdir -p $SD_ROOT_DIR/cache/two
          echo "I am two" > $SD_ROOT_DIR/cache/two/two
  three:
    requires: [one, two]
    steps:
      - three: |
          ls -l $SD_ROOT_DIR/cache
          ls -l $SD_ROOT_DIR/cache/one
          ls -l $SD_ROOT_DIR/cache/two
          cat $SD_ROOT_DIR/cache/one/one
          cat $SD_ROOT_DIR/cache/two/two
```

output from job `three`
```
drwxr-xr-x    2 root     root          4096 Jan  6 03:48 one
drwxr-xr-x    2 root     root          4096 Jan  6 03:53 two
-rw-r--r--    1 root     root             9 Jan  6 03:48 one
-rw-r--r--    1 root     root             9 Jan  6 03:53 two
I am one
I am two
```
