### ISSUE TITLE
Dynamic/Derived screwdriver.yaml

### ISSUE THREAD

**Issue by ysaakpr** [screwdriver-cd/screwdriver#2145]
Is there a way to dynamically create scredriver.yaml based on another file in the repo, by leveraging a external api

**More details**
I am new to screwdriver cd. And first glance, which has lots of promising features. We are trying to use the screwdriver cd for org-wide standard build system. Most of the build systems are made in such a way that it can be configured by a developer who responsible for ensuring the build pipeline. Which is good for small teams and teams know how to use screwdriver configs.

We are looking at an alternative way to the abstract screwdriver and provide a custom-tuned layer on top of screwdriver which restricts/enforces users to follow a certain process while adding the application to ci/cd pipeline.

Let's say we have certain steps in the ci/cd of an application
1. Prepare the build env
2. version the build
3. build the app
4. containerise the application - (in case of deployable application 95% cases are this),
5. upload the container
6. promote the application to various environments depending on attributes.

Out of all these steps, the only step that varies per application is the build steps, remaining all stay the same and can be abstracted.

We need all the users to maintain their build steps and artefacts generated in each build step to the following 
build.yaml
```
app:
   name: xyz
   team: infra
build:
  - image: nodejs:10
     order: 1
    artifacts: 
    - dist/
     steps:
     - npm install
     - npm build
  - image: go
     order: 2
     steps:
      - go build
     artifacts:
     - bin/
```

I want screwdriver to call an API with the above content, and the response of that API will be a scredriver.yaml which scredriver can understand.

In this way, the scredriver user can do many abstractions and use more capabilities and tune the scredriver for every org as per the need.

Note:
1. the Deriving API can be at screwdriver instance level or per repo
2. If a screwdriver.yaml present in the repo it will use scredriver.yaml to start the execution.
3. In case, in screwdriver.yaml if someone configures 
```
loadfrom: 
   URL: https://api.org.com/generateScredriverconfig
   addtoPostBody: 
   - build.yaml
   - anotherfile.yaml
   #- commit and other repo details can be included automatically 
```
this will be used to extend the config
4. If repo level screwdriver yaml  doesn't present, instance level `load` configurations used to generate the scredriver.yaml
