### ISSUE TITLE
Remote trigger to child pipelines do not work

### ISSUE THREAD

**Issue by yoshwata** [screwdriver-cd/screwdriver#2148]
**What happened**:
When remote trigger is defined in external config, the trigger is not work for the child pipelines.

Like below, a trigger appears but do nothing.
![Screen Shot 2020-07-14 at 16 42 37](https://user-images.githubusercontent.com/32473622/87398606-121e7e80-c5f1-11ea-9351-a0de52dfebb2.jpg)

**What you expected to happen**:
Every child pipelines triggered by remote trigger

**How to reproduce it**:
- Make external config
```
childPipelines:
  scmUrls:
    - git@my.github.co.jp:yoshwata-test/child-pipeline-test.git
    - git@my.github.co.jp:yoshwata-test/child-pipeline-test02.git
shared:
  image: node:8
jobs:
  main:
    requires: [ "~pr", "~commit" ]
    steps:
      - echo 'bar'
  test:
    requires: [ ~sd@129356:job2 ]
    steps:
      - echo foo
```
- sync the parent pipeline and child pipelines.
- start pipeline `129356`
