### ISSUE TITLE
[Feature Request] It's hard to notice which steps definition is adopted.

### ISSUE THREAD

**Issue by yoshwata** [screwdriver-cd/screwdriver#2174]
## What happened
Create pipeline like below:
```yaml
shared:
  steps:
    - prebuild_image: echo foo
jobs:
  docker-build:
    requires: [ ~pr, ~commit ]
    template: docker/build@stable
  docker-publish:
    requires: [ docker-build ]
    template: docker/publish@stable
    steps:
      - init: echo bar
```

In `docker-build` job, `prebuild_image` step is adopted, but in `docker-publish` job there is no `prebuild_image` step. That is because it has a priority of `jobs > shared > template`.

## What you expected to happen
This specification might not be intuitive, so merging mechanism for `steps` is one of solution. In the example above, both `prebuild_image` and `docker-publish` is adopted unless those step names have no conflict. Priority calculation is brought 
only by the situation that steps have same name.

It is another idea that validator shows which definition, jobs, shared or template, is adopted. We have a workaround to use [yaml technique](https://blog.screwdriver.cd/post/189301069397/yaml-tip-using-anchors-for-shared-steps-jobs) for sharing step's definition, so it might be sufficient if users can notice what or why their definition is drowned out.

## How to reproduce it
Give the yaml above to validator.

**Comment by taisukeh** [comment]
I too agree that this specification is confusing. I think the prebuild_image step should be applied to both jobs.

**Comment by jithine** [comment]
We will have to change spec if merging is desired behavior. But that means it will bring unintended behavior to existing pipelines. We could introduce this as an new feature with annotations.

**Comment by kumada626** [comment]
I think this feature only enable if template is used in jobs. Because not using template and no conflicting in shared and jobs steps, we cannot determine the order of steps.
For example, shared and job define steps like below.
```
shared:
  steps:
    - step1: echo step1
    - step2: echo step2
jobs:
  main:
    steps:
      - mainstep1: echo main1
      - mainstep2: echo main2
```
In such case, we cannot determine the order of steps in main job.
If template is used in job, the order of steps can be determined based on template.
