### ISSUE TITLE
Incorrect cache config in job  breaks pipeline dispay

### ISSUE THREAD

**Issue by jithine** [screwdriver-cd/screwdriver#2211]
**What happened**:

A pipeline with following config will result in 404 in UI. This is because `/jobs` end point returns 500 with validation error

```
jobs:
  staging-trigger:
    requires: [~commit:develop]
    cache: false
    image: ruby:2.7.1
    sourcePaths: ["screwdriver.yaml", "Dockerfile"]
    steps:
      - noop: echo "noop"
```

**What you expected to happen**:

GET to `/jobs` should not have failed. Screwdriver should not have created the incorrect job in first place or made it in a way that not having global cache config does not break `/jobs/` end point

**How to reproduce it**:

Create a pipeline with above yaml config.
