### ISSUE TITLE
The layout of pipeline description is broken.

### ISSUE THREAD

**Issue by ibu1224** [screwdriver-cd/screwdriver#2235]
**What happened**:
A single-line pipeline description will break the layout.
<img width="412" alt="pipeline-broken-layout" src="https://user-images.githubusercontent.com/17828065/94660301-76272800-0340-11eb-8663-a771ad082e97.png">

**What you expected to happen**:
It is displayed as shown in the following image.
<img width="373" alt="pipeline-description" src="https://user-images.githubusercontent.com/17828065/94660610-d6b66500-0340-11eb-9338-6101041d2635.png">

**How to reproduce it**:
Set a single-line pipeline description.
For example, create a pipeline with the following `screwdriver.yaml`
```
annotations:
  screwdriver.cd/pipelineDescription: Hi.
 
jobs:
  build1:
    image: node:12
    requires: [ ~commit, ~pr ]
    steps:
      - echo "Hi"
```
