### ISSUE TITLE
sd-local - ability to run steps inside build container

### ISSUE THREAD

**Issue by jithine** [screwdriver-cd/screwdriver#2238]
**What happened**:

Currently `sd-local` allows developers to run an entire job in build container. It will be beneficial to development workflow to get into the  environment of `sd-local `so that they can run steps and commands inside the container and debug any failures.

**What you expected to happen**:

1. `sd-local` to support an `exec` mode into the build container where they can run any steps they want.
1. Similar to `docker run -it container sh` 
1. Developers gets an interactive shell inside the environment setup by `sd-local`

**How to reproduce it**:

N/A

**Reference**

 - https://github.com/screwdriver-cd/screwdriver/issues/1314

**Comment by jithine** [comment]
cc @ibu1224 @kkisic @MysticDoll

**Comment by ibu1224** [comment]
@jithine 
Hello.
Let me ask you a question for the this feature.

In order to debug, the user execute an arbitrary command or script.

We need to think when that command will be executed.
In the case of sd-local, the following cases are possible.

Cases
1. Before executing steps of screwdriver.yaml
1. After executing all steps of screwdriver.yaml

About 1. 
In this case, user command executing  before executing the steps of screwdriver.yaml.
Maybe we can check the operation in the environment before the steps is executed.

About 2.
In this case, the user's command is executed after steps of screwdriver.yaml is executed.
Maybe able to see the results after the steps of screwdriver.yaml are executed

Which of the above cases would you need to solve this issue? Or both? Or not?

Tell me what you think 🙏

**Comment by yuichi10** [comment]
I want some function that makes it easy to run step commands.
For example, all step commands are preserved as alias and user can exec a step command by using the alias.

If there is a YAML as shown below
```
jobs:
  main:
    requires: [ ~commit ]
    image: cd.docker-registry.corp.yahoo.co.jp:4443/node/node10:latest
    steps:
      - test: npm test
      - echo: echo 'success'
```

user can exec steps as shown below
```
$ sd-echo
success
$ sd-test 
...
```

**Comment by jithine** [comment]
@ibu1224 intention is to keep it separate from running of steps, which will be a separate feature than this. 

I echo what @yuichi10 has mentioned. Ability to to run individual build step once inside the container, and also run any command once inside the container.

**Comment by ibu1224** [comment]
@jithine  Thank you for the reply.
The implementation direction seems to be (About 1).
Allows any commands to be executed in the build container.

@jithine , @yj-members 
I have thought about how to implement it.
Please comment if you have any ideas.

If there is a `screwdriver.yaml` as shown below

```
jobs:
  build1:
    requires: [ ~commit ]
    image: node10:latest
    steps:
      - echo: echo 'Hello'
      - echo 'bar'

  build2:
    requires: [ ~commit ]
    image: node10:latest
    steps:
      - echo: echo 'World'

```
User can exec steps as shown below

```
-------------------------------------
commands
$ sd-local build -s <jobName>:<stepName>
 or
$ sd-local build --step <jobName>:<stepName>
-------------------------------------

$ sd-local build -s build1:echo
=> Hello

$ sd-local build -s build1:step-2
=> bar

$ sd-local build -s build2:echo
=> World
```
At this time, use the build image defined in the build.
Deletes the build container after executing the sd-local command.

Add a new step option to the build command.
