### ISSUE TITLE
Simplify the job names displayed in pipeline graph

### ISSUE THREAD

**Issue by wahapo** [screwdriver-cd/screwdriver#2243]
**What happened**:
When users deploy and subsequently test on several clusters, it is obvious which cluster the test jobs will be run on by looking at the connections displayed in the pipeline graph. However, they need to be named differently, and they will appear under different names in the pipeline graph.
<img width="297" src="https://user-images.githubusercontent.com/24538326/95655284-14856b80-0b41-11eb-8a2f-fc608ba32792.png">

**What you expected to happen**:
It is obvious that the two test jobs are tests for each cluster if users look at the pipeline graph. Both test jobs are easier to see if they are only called test.
<img width="298" src="https://user-images.githubusercontent.com/24538326/95655290-1b13e300-0b41-11eb-9b86-1fb994c0c5b4.png">

It would be nice to be able to set the displayName in `screwdriver.yaml`.
```
jobs:
  test-cluster01:
    annotations:
      screwdriver.cd/displayName: test

  test-cluster02:
    annotations:
      screwdriver.cd/displayName: test
```

**How to reproduce it**:
