### ISSUE TITLE
notification status cannot be shared

### ISSUE THREAD

**Issue by jithine** [screwdriver-cd/screwdriver#2275]
**What happened**:
For a configuration like this

```
    settings:
        email: [status@email.com]
        slack: status
        statuses: [ SUCCESS, FAILURE ]
```

user is only getting notification for `FAILURE`. This is because the `statuses` has be inside each notification plugin.

**What you expected to happen**:

We can provide either of the following solutions

1. Validator must want that `statuses` is not proper.
2. Or `statuses` under `settings` should be carried over by individual notification plugins

**How to reproduce it**:
