### ISSUE TITLE
sd-local interactive mode with environment variables that contain spaces

### ISSUE THREAD

**Issue by wahapo** [screwdriver-cd/screwdriver#2280]
**What happened**:
Defined an environment variable in `screwdriver.yaml` that contains a space, that environment variable is not set in interactive mode.

**What you expected to happen**:
Currently it output `MY_MSG=this is test` in `/tmp/sd-local.env`. Expected `MY_MSG="this is test"`.

**How to reproduce it**:
1. Create `screwdriver.yaml`.
    ```yaml
    jobs:
      test:
        image: node:12
        steps:
          - ls
        environment:
          MY_MSG: this is test
          MY_FOO: foo
    ```
2. Run sd-local with interactive mode.
    ```
    $ sd-local version
    1.0.13
    $ sd-local build -i test --sudo
    sd-local# echo $MY_MSG

    sd-local# echo $MY_FOO
    foo
    ```
