### ISSUE TITLE
[Feature request] Support mentioning users

### ISSUE THREAD

**Issue by jweingarten** [screwdriver-cd/screwdriver#2293]
https://api.slack.com/reference/surfaces/formatting#mentioning-users has examples for how this is done. 

Currently we don't allow setting the type of the message, which means we send messages as `just text` and not formatted. 

Example: https://app.slack.com/block-kit-builder/T025DU6HX#%7B%22blocks%22:%5B%7B%22type%22:%22section%22,%22text%22:%7B%22type%22:%22mrkdwn%22,%22text%22:%22Hey%20%3C@U024BE7LH%3E,%20thanks%20for%20submitting%20your%20report!%22%7D%7D%5D%7D

**Comment by jithine** [comment]
Based on https://github.com/screwdriver-cd/notifications-slack/pull/19#issuecomment-497193855 this was supposed to work.

**Comment by jweingarten** [comment]
This works. Tested in a new pipeline that had various jobs posting a channel that notifies me. Example yaml:

```
shared:
  environment:
  settings:
    slack:
        channels:
            - 'temp_joerg'
        statuses:
            - SUCCESS
            - FAILURE
            - ABORTED
            - QUEUED
            - RUNNING
            - CREATED
            - BLOCKED
            - UNSTABLE

jobs: 
  start: 
    annotations:
      screwdriver.cd/buildPeriodically: H * * * *
    image: docker.ouroath.com:4443/paas.ynodejs.images/node10-ylinux7-slim-sd:1-CURRENT
    template: dhrainbow/empty@0.1.10
    steps:
      - nothing: |
            echo "Hello First"
            
  generic_success:
    requires: [start]
    image: docker.ouroath.com:4443/paas.ynodejs.images/node10-ylinux7-slim-sd:1-CURRENT
    template: dhrainbow/empty@0.1.10
    steps:
      - nothing: |
            echo "Hello First"
            
  generic_failure:
    requires: [start]
    image: docker.ouroath.com:4443/paas.ynodejs.images/node10-ylinux7-slim-sd:1-CURRENT
    template: dhrainbow/empty@0.1.10
    steps:
      - nothing: |
            echo "Hello Failure"
            exit -1
            
  notify_me:
    requires: [start]
    image: docker.ouroath.com:4443/paas.ynodejs.images/node10-ylinux7-slim-sd:1-CURRENT
    steps:
      - meta: |
            meta set notification.slack.message "<@joerg> Hello hello!"
      - nothing: |
            echo "Hello notify_me" 

  notify_me_job_specific:
    requires: [notify_me]
    image: docker.ouroath.com:4443/paas.ynodejs.images/node10-ylinux7-slim-sd:1-CURRENT
    steps:
      - meta: |
          meta set notification.slack.notify_me_job_specific.message "<@joerg> job specific!"
      - nothing: |
          echo "Hello notify_me_job_specific"

```
