### ISSUE TITLE
UI failed to render workflow when it contains similar job name

### ISSUE THREAD

**Issue by tanoda** [screwdriver-cd/screwdriver#2306]
**What happened**:
UI shows 404 error with console: `vendor-d25689da53495058515415531632900d.js:formatted:18205 Uncaught TypeError: (e || "").localeCompare is not a function`.

**What you expected to happen**:
UI should show the pipeline page correctly.

**How to reproduce it**:
Visit pipeline configured with the following screwdriver.yaml:
```yaml
shared:
  image: node:12
  steps: [echo test]
jobs:
  build-013-test:
    requires: test
  build-13-test:
    requires: test
  test: {}
```

This line fallback to id `compare` if a similar name is found.
https://github.com/screwdriver-cd/ui/blob/4ed874bb1799ad2b1e0c99504926975c84ee3ed6/app/event/serializer.js#L26
Unfortunately, `compare` is string-based compare, and id is not String, but Number. so it failed to call localeCompare.
https://github.com/screwdriver-cd/ui/blob/4ed874bb1799ad2b1e0c99504926975c84ee3ed6/app/event/serializer.js#L5

It can break other pipelines by creating a remote trigger, too.
