### ISSUE TITLE
meta cannot be set to a string of common logarithm

### ISSUE THREAD

**Issue by wahapo** [screwdriver-cd/screwdriver#2309]
**What happened**:
A string in common logarithm format is set to meta, then it will be converted as a number.

```
$ meta set foo 50876e6
$ meta get foo
50876000000
```

This is probably caused by the following code.
https://github.com/screwdriver-cd/meta-cli/blob/5bf554b5964ae938ff0b91c827c838799290f014/meta.go#L456

**What you expected to happen**:
I want it to be recognized as a string.

```
$ meta set foo 50876e6
$ meta get foo
50876e6
```

**How to reproduce it**:
https://cd.screwdriver.cd/pipelines/4862/builds/670037/steps/step2

```
jobs:
  main:
    requires: [ ~pr, ~commit ]
    image: node:10
    steps:
      - step1: meta set foo 50876e6
      - step2: meta get foo
```
