### ISSUE TITLE
Template Composition

### ISSUE THREAD

**Issue by jithine** [screwdriver-cd/screwdriver#2319]
**What happened**:

There is no option to share template configuration among different templates. Users are forced to duplicate template configuration for related templates but differs only in few builds steps.

**What you expected to happen**:

Screwdriver should provide a mechanism which allows templates to inherit configuration from another template, which allows
1. add more configurations like steps
2. override existing configurations like steps/image

**How to reproduce it**:

N/A

**Comment by tkyi** [comment]
### Proposal
1. Support using a template in a template (just as template usage works in a normal screwdriver.yaml today)
2. Add new key `order` as an array for template owners to pick and choose steps (and specify order) from both the external template config and its own config; templates will only run steps specified in the `order` field in that order; all other fields will be merged as usual, with current template taking precedence over the external one

Notes:
- The current config will take precedence over the external one.
- `images` field will also be merged
-  *Question*: should wrap(`pre`/`post`) and user teardown (`teardown-`) steps be supported for template composition?


template/external@1:
```
name: template/external
version: 1.2.3
description: this is the external template
maintainer: external@domain.org
images:
    latest-image: node:12
    stable-image: node:10
config:
  image: stable-image
  steps:
    - install: npm install
    - test: npm test
  environment:
    FOO: bar
  secrets:
     - EXTERNAL_SECRET
```

current template:
```
name: template/current
version: 2.0.1
description: this is the current template
maintainer: current@domain.org
images:
    test-image: node:18
config:
  template: template_namespace/external@1
  image: stable-image
  order: [init, install, test, end]
  steps:
    - init: echo Starting
    - install: ./run_script.sh
    - end: echo Finished
  environment:
    BAR: baz
  secrets:
     - CURRENT_SECRET
```

result:
```
name: template/current
version: 2.0.1
description: this is the current template
maintainer: current@domain.org
images:
    test-image: node:18
    latest-image: node:12
    stable-image: node:10
config:
  image: node:10
  steps:
    - init: echo Starting
    - install: ./run_script.sh
    - test: npm test
    - end: echo Finished
  environment:
    BAR: baz
    FOO: bar
  secrets:
     - CURRENT_SECRET
     - EXTERNAL_SECRET
```
