### ISSUE TITLE
Don't require jobs just to have something to run

### ISSUE THREAD

**Issue by dwmarshall** [screwdriver-cd/screwdriver#2323]
**What happened**:

I have a repository of files that is used to affect configuration files in other repositories. When a commit occurs, nothing needs to happen other than the downstream jobs to be triggered. What I have now in the "source" repository:

```
jobs:
  main:
    requires: [~commit]
    image: screwdrivercd/noop-container
    steps:
      - nothing: echo nothing
```

and then in another repository's `screwdriver.yaml`:

```
jobs:
  merge:
    requires: [~sd@12345:main, ~commit]
    ...
```
It's low overhead for the first repository to run a do-nothing job, but that's still overhead.  

**What you expected to happen**:

I would like to to create a pipeline for a repository that doesn't have a `screwdriver.yaml` file (see #2104) but does have events. To wit, I'd like my `screwdriver.yaml` be:

```
jobs:
  merge:
    requires: [~sd@12345:commit, ~commit]
    ...
```

I thought about approaches that would permit multiple repositories generating the `~commit` event for a pipeline, but I think this use case is not sufficiently common to add that capability.

**How to reproduce it**:
