### ISSUE TITLE
Not able to turn off notification settings for a job

### ISSUE THREAD

**Issue by jithine** [screwdriver-cd/screwdriver#2328]
**What happened**:

If `screwdriver.yaml` has `settings` in `shared` user is not able to turn it off for specific jobs. 

**What you expected to happen**:
jobs should have way to opt out of shared notification settings
**How to reproduce it**:

`screwdriver.yaml`

```
version: 4
shared:
  settings:
    email:
      addresses: [notify@email.com]
      statuses: [FAILURE]
    slack: 'alert'

jobs:
  pull-request:
    requires: [~pr]
    image: node:12
    steps:
      - build: mvn clean # clean-up
    settings: {}
```

Job `pull-request` still has settings config from `shared`
