### ISSUE TITLE
UI - Workflow graph should place nodes at maximum possible depth

### ISSUE THREAD

**Issue by jithine** [screwdriver-cd/screwdriver#2330]
**What happened**:

Nodes in workflow graph are placed at minimum possible depth which can cause graph rendering constricted.
 

**What you expected to happen**:
Each node in workflow graph should be placed in maximum possible depth

**How to reproduce it**:

`screwdriver.yaml`

```
shared:
    image: node:12
jobs:
    A:
        requires: [~pr, B]
        steps:
            - runA
    B:       
        requires: [~pr, ~commit]
        steps:
            - runB
```

<img width="225" alt="Screen Shot 2021-01-27 at 10 23 02 AM" src="https://user-images.githubusercontent.com/193126/106036073-afbb3600-6089-11eb-951e-73e81064ff2c.png">

Node B should be placed in the workflow graph in 3rd column rather than 2nd column like how it's rendered today.

**Comment by jithine** [comment]
cc @adong @OronNadiv

**Comment by y-oksaku** [comment]
If we set `template` to job A, then the workflow graph on validator page will be the following.
But this behavior does not occur on pipeline pages.

```yaml
shared:
    image: node:12
jobs:
    A:
        requires: [~pr, B]
        template: nodejs/test@latest
        steps:
            - runA
    B:
        requires: [~pr, ~commit]
        steps:
            - runB
```

![validator-template](https://user-images.githubusercontent.com/43719835/161202179-d528d170-15d3-42c1-ae1c-4098f2f4e733.png)
