### ISSUE TITLE
Run steps in parallel

### ISSUE THREAD

**Issue by jithine** [screwdriver-cd/screwdriver#2344]
**What happened**:

Build steps which can run in parallel should have a mechanism to do so.

**What you expected to happen**:
 
 Provide a way for Pipeline authors to run steps in parallel.

Example configuration 

```
steps:
 A: ./runA
 B:
    command: ./runB
    group: X
 C:
     command: ./runC
    group: X
 D:  ./runD

```

In the above configuration after Step `A` runs, steps `B` & `C` runs in parallel and then Step `D` runs after both steps `B` & `C` completes successfully 

**How to reproduce it**:
