### ISSUE TITLE
When using chainPR, PR_BRANCH_NAME set undefined

### ISSUE THREAD

**Issue by wahapo** [screwdriver-cd/screwdriver#2404]
**What happened**:
In a PR build started with set `chainPR: rue` and chained, if the branch name includes a slash, `$PR_BRANCH_NAME` will be `origin/undefined`.

**What you expected to happen**:
`$PR_BRANCH_NAME` should be something like `origin/foo/bar`.

**How to reproduce it**:
1. Create screwdriver.yaml with `chainPR: true`.
    ```
    annotations:
      screwdriver.cd/chainPR: true

    jobs:
      job-1:
        requires: ~pr
        image: node:14
        steps:
          - echo ${PR_BRANCH_NAME}
      job-2:
        requires: job-1
        image: node:14
        steps:
          - echo ${PR_BRANCH_NAME}
    ```
2. Create a branch including a slash (e.g. `foo/bar`)
3. Run the PR build.
4. In [job-1](https://cd.screwdriver.cd/pipelines/6923/builds/693580/steps/step-1), `${PR_BRANCH_NAME}` is set to the correct value of `origin/foo/bar`.
5. Looking at the log of [job-2](https://cd.screwdriver.cd/pipelines/6923/builds/693581/steps/step-1), `${PR_BRANCH_NAME}` is `origin/undefined`.
