### ISSUE TITLE
Reference another environment variable in an environment variable

### ISSUE THREAD

**Issue by samuel-phan** [screwdriver-cd/screwdriver#2411]
**What happened**:

```
shared:
  environment:
    CF_BUCKET: "my-cloudformation-bucket"

jobs:
  upload-cloudformation-templates:
    requires: [~commit]
    steps:
      - upload-templates-to-s3:
          aws s3 sync --sse aws:kms cloudformation s3://${CF_BUCKET}

  deploy-us-east-1:
    requires: [upload-cloudformation-templates]
    environment:
      REGION: "us-east-1"
      CF_TEMPLATE: https://${CF_BUCKET}.s3.amazonaws.com/my-app/cloudformation-us-east-1.json
      PARAMETERS_FILE: "cloudformation/my-app/dev/parameters-us-east-1.json"
    template: cf/cf-deploy@latest

  deploy-us-west-2:
    requires: [upload-cloudformation-templates]
    environment:
      REGION: "us-west-2"
      CF_TEMPLATE: https://${CF_BUCKET}.s3.amazonaws.com/my-app/cloudformation-us-west-2.json
      PARAMETERS_FILE: "cloudformation/my-app/dev/parameters-us-west-2.json"
    template: cf/cf-deploy@latest
```

When I run this Screwdriver (SD) file:

```
CF_TEMPLATE=https://.s3.amazonaws.com/my-app/cloudformation-us-east-1.json
```

**What you expected to happen**:

```
CF_TEMPLATE=https://my-cloudformation-bucket.s3.amazonaws.com/my-app/cloudformation-us-east-1.json
```

**How to reproduce it**:

Use the SD file above, replace the `    template: cf/cf-deploy@latest` by something like:

```
steps:
  - echo: echo $CF_TEMPLATE
```
