### ISSUE TITLE
Failed builds should remove join builds in `CREATED` status.

### ISSUE THREAD

**Issue by jithine** [screwdriver-cd/screwdriver#2425]
**What happened**:

For a join build in `CREATED` status, only a successful parent build can delete it. This leads to a situation that if the last build in join relation ship fails, then it's not cleaned up. 

```
jobs:
   A: requires[~commit]
   B: requires[~commit]
   C: requires[A, B]
```

Join build for C stays in `CREATED` status under the following conditions.
1. A fails and runs for 20s.
1. B is successful and runs for 10s.

Only on cases where A fails and completes first, then the join build for C is deleted or doesn't exist.
**What you expected to happen**:

In the above scenario, join build C should not exist when A fails.

**How to reproduce it**:
