### ISSUE TITLE
The order of evaluation of environments is not consistent in sd-local

### ISSUE THREAD

**Issue by itleigns** [screwdriver-cd/screwdriver#2446]
**What happened**:
The order of evaluation of environment variables is not consistent in sd-local.
So the result of the evaluation of an environment variable is not constant when another environment variable is used in the environment variable.

**What you expected to happen**:
Environment variables are evaluated in the order in which they are defined in `screwdriver.yaml`.

**References**:
https://docs.screwdriver.cd/user-guide/configuration/environment

**How to reproduce it**:
Use the following YAML.
```
jobs:
  foo:
    image: node12
    steps:
    - echo $BEFORE
    - echo $AFTER
    environment:
      BEFORE: YYY${X}YYY
      X: XXX
      AFTER: ZZZ${X}ZZZ
```
`BEFORE` can be evaluated to either `YYYXXXYYY` or `YYYYYY` and `AFTER` can be evaluated to either `ZZZXXXZZZ` or `ZZZ`.
