### ISSUE TITLE
When using template composition, omitting steps will cause a validation error

### ISSUE THREAD

**Issue by wahapo** [screwdriver-cd/screwdriver#2457]
**What happened**:
When using the [Template Composition](https://docs.screwdriver.cd/user-guide/templates#template-composition), `/v4/validator/template` API will return 400 error if the step section is omitted.

The error message is `{"statusCode":400,"error":"Bad Request","message":"TypeError: Cannot read property 'reduce' of undefined"}`.
<img width="400" src="https://user-images.githubusercontent.com/24538326/119290532-a16fd600-bc87-11eb-9ad0-c6545a699044.png">

Add the steps section and it works fine.
<img width="300" src="https://user-images.githubusercontent.com/24538326/119290663-f57aba80-bc87-11eb-8df2-debf35f2ed00.png">

**What you expected to happen**:
It should work even if we omit the steps section.

**How to reproduce it**:
Enter the following yaml in [validator](https://cd.screwdriver.cd/validator).
```
namespace: wahapo
name: wahapo-template
version: '1.0'
description: "my template"
maintainer: foo@bar.com
config:
  template: nodejs/test
  order: [test]
```
