### ISSUE TITLE
Fix the pipeline ID of "Remote Trigger", the first behavior will be wrong

### ISSUE THREAD

**Issue by wahapo** [screwdriver-cd/screwdriver#2466]
**What happened**:
Triggers that are removed from the pipeline will only fire on the first commit after they are removed.
https://cd.screwdriver.cd/pipelines/7412/events/632946
<img width="200" src="https://user-images.githubusercontent.com/24538326/120276882-39a43580-c2ee-11eb-9177-ef79d0d67023.png">
Also, if we revert fix, the build will not start.
<img width="650" src="https://user-images.githubusercontent.com/24538326/120280876-38293c00-c2f3-11eb-923e-8f863c58327d.png">

**What you expected to happen**:

**How to reproduce it**:
1. Create a pipeline. ( https://cd.screwdriver.cd/pipelines/7412 )
    ```
    jobs:
      main:
        requires: [ ~commit ]
        image: node:14
        steps:
          - ls
      sub:
        requires: [ ~sd@7412:main ]
        image: node:14
        steps:
          - ls
    ```
2. Create another pipeline. ( https://cd.screwdriver.cd/pipelines/7413 )
    ```
    jobs:
      main:
        requires: [ ~sd@7412:main ]
        image: node:14
        steps:
          - ls
    ```
3. Fix first pipeline and merge. ( [Diff](https://github.com/wahapo/wahapo-sdsample/pull/6/files) )
    ```
    jobs:
      main:
        requires: [ ~commit ]
        image: node:14
        steps:
          - ls
      sub:
    -   requires: [ ~sd@7412:main ]
    +   requires: [ ~sd@7413:main ]
        image: node:14
        steps:
          - ls
    ```
4.  The build is executed successfully. ( https://cd.screwdriver.cd/pipelines/7412/events/632945 )
    <img width="300" src="https://user-images.githubusercontent.com/24538326/120273523-93eec780-c2e9-11eb-98a5-75a16a10819e.png">
5. Apart from that, there is one more unnecessary event. ( https://cd.screwdriver.cd/pipelines/7412/events/632946 )
    <img width="200" src="https://user-images.githubusercontent.com/24538326/120276882-39a43580-c2ee-11eb-9177-ef79d0d67023.png">
6. If we start the pipeline again, the problem will not occur. ( https://cd.screwdriver.cd/pipelines/7412/events/632951 )
7. Make the undo fix and merge. ( [Diff](https://github.com/wahapo/wahapo-sdsample/commit/58f0a33b551e63505ddb554addd0bbaebf6bfd4f) )
    ```
    jobs:
      main:
        requires: [ ~commit ]
        image: node:14
        steps:
          - ls
      sub:
    -   requires: [ ~sd@7413:main ]
    +   requires: [ ~sd@7412:main ]
        image: node:14
        steps:
          - ls
    ```
8. `sub` job does not start. ( https://cd.screwdriver.cd/pipelines/7412/events/632927 )
    <img width="600" src="https://user-images.githubusercontent.com/24538326/120277804-7b81ab80-c2ef-11eb-8074-37b17e4d4d2a.png">
9. When we turn on the toggle switch for show trigger, something is wrong.
    <img width="600" src="https://user-images.githubusercontent.com/24538326/120277800-7a507e80-c2ef-11eb-894b-dbba6a71521d.png">
10. If we start the pipeline again, the problem will not occur. ( https://cd.screwdriver.cd/pipelines/7412/events/632930 , https://cd.screwdriver.cd/pipelines/7412/events/632930 )
