### ISSUE TITLE
Description of job is null if we use the templates

### ISSUE THREAD

**Issue by itleigns** [screwdriver-cd/screwdriver#2478]
**What happened**:
If we use the templates, the description of the job will be displayed as blank in the validator even if it is set.

**What you expected to happen**:
Description is displayed as it is set in `screwdriver.yaml`

**How to reproduce it**:
Use the following `screwdriver.yaml`.
```
jobs:
  templated-job:
    description: templated job
    template: screwdriver-cd/semantic-release-node8@1.0.0
```
<img width="667" alt="description-blank-template" src="https://user-images.githubusercontent.com/22903716/121327221-35ab8f80-c94e-11eb-8a84-6c15058caaca.png">
