### ISSUE TITLE
A commit job is blocked by PR jobs

### ISSUE THREAD

**Issue by wahapo** [screwdriver-cd/screwdriver#2499]
**What happened**:
In the case that the user is using [blockedBy](https://docs.screwdriver.cd/user-guide/configuration/workflow#blocked-by), the commit job will be blocked not only by commit jobs specified in blockedBy but also by PR jobs. Similarly, the PR job will be blocked by commit jobs specified in blockedBy.

**What you expected to happen**:
I think that commit events and PR events should not be involved in each other's blocks.

**How to reproduce it**:
1. Create `screwdriver.yaml`
    ```
    jobs:
      job1:
        requires: [ ~commit, ~pr ]
        image: node:14
         steps:
          - ls
      job2:
        requires: [ ~job1 ]
        image: node:14
        blockedBy: [ ~job1 ]
        steps:
          - ls
      ```
2. Create PR and exec `job1` in PR event.
3. Exec `job2` manually.
4. You will see that the manually exec `job2` is blocked by `job1` which is running in the PR event.

**Relates to**:
https://github.com/screwdriver-cd/models/pull/508#issuecomment-868158173

However, in the case of the same job, it may be that both commit and PR events should be blocked without distinction.
https://github.com/screwdriver-cd/screwdriver/issues/1984
