### ISSUE TITLE
Some environment variables should not be overridden.

### ISSUE THREAD

**Issue by wahapo** [screwdriver-cd/screwdriver#2504]
**What happened**:
For example, if the `SD_ARTIFACTS_DIR` [environment variable](https://docs.screwdriver.cd/user-guide/environment-variables) is overwritten, the build will fail to work.
https://cd.screwdriver.cd/pipelines/7309/builds/720197/steps/sd-teardown-screwdriver-artifact-bookend

**What you expected to happen**:
Environment variables that fail when overwritten should not be able to be overwritten.

**How to reproduce it**:
```
jobs:
  main:
    requires: [~commit,~pr]
    image: node:14
    environment:
      SD_ARTIFACTS_DIR: my_artifacts/
```
