### ISSUE TITLE
image defined in shared section is overriding template image

### ISSUE THREAD

**Issue by jithine** [screwdriver-cd/screwdriver#2522]
**What happened**:

```
shared:
    image: node:12
    steps:
        - echo: hello

jobs:
    docker-publish:
        requires: publish
        template: sd/dind@latest
```
in the above config, `image` for the job is `node:12` it should have been template `image`. Steps already behave this way, `image` seems to have inconsistent behavior when compare to steps 

**What you expected to happen**:

`image` is template definition should take precedence just like how steps are.

One potential problem is that if users are already used to this behavior, fixing this will case backward incompatibility.

**How to reproduce it**:

Run in https://cd.screwdriver.cd/validator the above `screwdriver.yaml`
