### ISSUE TITLE
sd-local accidently leaks specified environment value, if template or screwdriver.yaml refers it without definition.

### ISSUE THREAD

**Issue by tanoda** [screwdriver-cd/screwdriver#2540]
**What happened**:
Create screwdriver.yaml with any environment reference without explicit definition:
```yaml
jobs:
  test:
    image: ubuntu:latest
    steps:
      - get: |
          echo "$PATH"
    environment:
      PATH: $PATH:/whatever
```

and run with `sd-local build -v test`, it shows:
```
/Users/tanoda/.sdkman/candidates/maven/current/bin:/Users/tanoda/.sdkman/candidates/kotlin/current/bin:/Users/tanoda/.sdkman/candidates/java/current/bin:/Users/tanoda/.sdkman/candidates/groovy/current/bin:/Users/tanoda/.sdkman/candidates/gradle/current/bin:/Users/tanoda/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/usr/local/sbin:/whatever:/opt/sd
```

However, this is not the same as the screwdriver build's behavior.

**What you expected to happen**:
`ubuntu:latest` container's PATH is `/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin`.
So in screwdriver build, it resolved as `/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/whatever:/opt/sd`

**How to reproduce it**:
see above.
