### ISSUE TITLE
Update schema for aws integration compatibility in screwdriver.yaml

### ISSUE THREAD

**Issue by pritamstyz4ever** [screwdriver-cd/screwdriver#2561]
**What happened**:
Update screwdrivercd/data-schema (update schema for aws integration compatibility in screwdriver.yaml)
https://github.com/screwdriver-cd/screwdriver/issues/2550
**What you expected to happen**:

**How to reproduce it**:

**Comment by tkyi** [comment]
Example config:
```
provider:
    name: aws
    region: us-west-2
    accountId: 1111111111111
    vpc: # Optional VPC. But if you use VPC then both subproperties (securityGroupIds and subnetIds) are required
        vpcId: vpc-xxxxx
        securityGroupIds:
            - securityGroupId1
            - securityGroupId2
        subnetIds:
            - subnetId1
            - subnetId2
    role: arn:aws:iam::XXXXXX:role/role
```
