### ISSUE TITLE
Chain PR does not trigger the downstream job when one of the parallel job fails in the PR build

### ISSUE THREAD

**Issue by AlameluSubbiah** [screwdriver-cd/screwdriver#2581]
**What happened**:
We created a pipeline which uses chain PR to merge two parallel jobs in the PR builds 
```
annotations:
  screwdriver.cd/chainPR: true
shared:
  image: <img>
jobs:
  job1:
    requires: [ ~pr ]
    steps:
    ....
  job2:
    requires: [ ~pr ]
    steps:
    ...
  job3:
   requires: [ job1, job2]
   steps:
    ....
```
The job1 and job2 are triggered by making PR and one of the parallel jobs - `job1` fails . After manually restarting `job1` , `job3` is not getting triggered if `job1` succeeds.

**What you expected to happen**:
The `job3` should get triggered when the `job1` passes.

**How to reproduce it**:
 1. Make a pipeline that uses chainPR feature to join two parallel jobs.
 2. Trigger PR build and fail one of the parallel jobs.
 3. Manually restart the failed parallel job.
 4. Downstream job is not triggered that requires the restarted parallel build.
