### ISSUE TITLE
Unable to publish latest tag to template in another namespace if template with the same name exists

### ISSUE THREAD

**Issue by yoshwata** [screwdriver-cd/screwdriver#2596]
I created the following template:

```
namespace: yoshwata
name: yoshwata-test-template
version: "0.0"
description: |
  Test Template
maintainer: yoshwata@gmail.com
config:
  image: node:12
  steps:
    - echo: echo hi
    - echo2: echo hello
```

Then try to create a template like this:

```
namespace: yoshwata-another
name: yoshwata-test-template
version: "0.0"
description: |
  Test Template
maintainer: yoshwata@gmail.com
config:
  image: node:12
  steps:
    - echo: echo hi
    - echo2: echo hello
```

Then I get the following error:
```
Error: 500 Reason "Validation error"
```

**What you expected to happen**:

The latest tag can be published even if the template with the same name exists.

**Example**:

https://cd.screwdriver.cd/pipelines/8102/builds/747563/steps/publish
