### ISSUE TITLE
A build in state SUCCESS becomes state QUEUED

### ISSUE THREAD

**Issue by itleigns** [screwdriver-cd/screwdriver#2612]
**What happened**:
A build which finishes with status `SUCCESS` becomes `QUEUED` status and remains unchanged.
**What you expected to happen**:
The build remains in `SUCCESS` status.
**How to reproduce it**:
[Pipeline](https://cd.screwdriver.cd/pipelines/8203/events/660917)
```
jobs:
  A:
    requires: [ ~commit ]
    steps:
      - show: echo 'A'
  B:
    requires: [ ~commit ]
    steps:
      - sleep: sleep 300
  C:
    requires: [ ~commit ]
    steps:
      - show: echo 'C'
  D:
    requires: [ ~A, B, C]
    steps:
      - sleep: sleep 100
```
