### ISSUE TITLE
Option for users to externalize provider configuration

### ISSUE THREAD

**Issue by tkyi** [screwdriver-cd/screwdriver#2676]
**What happened**:
Currently users need to provide the entire AWS provider config as part of screwdriver.yaml. 
https://docs.screwdriver.cd/cluster-management/aws-integration#job-provider-configuration

However this can lead to lots of config duplication, if same account is used in multiple pipelines and any changes will need updates to multiple git repositories.

**What you expected to happen**:
Give users an easy way to mention a references to provider configuration in screwdriver.yaml so that users can maintain config in a central place.

```
jobs:
  main:
    requires: [~pr, ~commit]
    image: aws/test/image-x86_64-standard:3.0
    provider: git_organization/repo:path
```

Screwdriver must fetch the provider from the given git path and apply to job configuration.
