### ISSUE TITLE
[feature req] Group remote triggers from pipeline by event

### ISSUE THREAD

**Issue by dwmarshall** [screwdriver-cd/screwdriver#2785]
For some pipeline 11111:
```
jobA:
  requires: [~commit]
  sourcePaths: ["jobA/"]

jobB:
  requires: [~commit]
  sourcePaths: ["jobB/"]
```

in another pipeline, I have
```
main:
  requires: [~commit, ~sd@11111:jobA, ~sd@11111:jobB]
```

According to @jithine today, if there's an event on the first pipeline that causes both `jobA` and `jobB` to run, then the second pipeline's `main` will run twice.

It's a little bit counter-intuitive that the same event on 11111 could cause a downstream job to start twice, even though that's the literal meaning of the second pipeline's `requires`.

It would be nice to be able to specify the `requires` for `main` such that for a single event in 11111, job `main` only starts once.

Some possible ideas to make intent explicit:
```
requires: [~commit, ~sd@11111:jobA+jobB]
requires: [~commit, ~sd@11111:jobA|jobB]
```
