### ISSUE TITLE
[Config] No validator for all allowed annotations and their values

### ISSUE THREAD

**Issue by adong** [screwdriver-cd/screwdriver#2845]
**What happened**:
We have a list of [annotations](https://docs.screwdriver.cd/user-guide/configuration/annotations), however, we dont have validators for them. 

Take this sd.yaml as an example.
```
jobs:
  main:
    requires: [~job1, ~job2]
    image: node:18
    steps:
      - noop: echo "NOOP"
    annotations:
      screwdriver.cd/ram: HIGH
      screwdriver.cd/timeout: 14400a
```

**What you expected to happen**:
1) should check if annotation `screwdriver.cd/timeout` exists or not
2) should check annotation `screwdriver.cd/timeout`'s value 14400a` is valid or not

![image](https://user-images.githubusercontent.com/15989893/227002530-396150d6-893c-40aa-9cb7-a16711f514b0.png)

**How to reproduce it**:
Copy above sd.yaml to `https://cd.screwdriver.cd/validator` to validate
