### ISSUE TITLE
Setup build cluster logical group and key mapping for bookend set

### ISSUE THREAD

**Issue by pritamstyz4ever** [screwdriver-cd/screwdriver#2852]
**What happened**:

Screwdriver bookend is not mapped for build executor and build architecture. If we have build cluster and executor combination we should be able to pick specific bookends.

```
screwdriver.cd/buildCluster: buildcluster1
screwdriver.cd/executor: k8s
```
Existing screwdriver bookend structure https://github.com/screwdriver-cd/screwdriver/blob/master/config/default.yaml#L287

**What you expected to happen**:

Proposed structure while maintaining backward compatibility
```
bookends:
  # Plugins for build setup
  default:
    setup:
      - scm
      - screwdriver-cache-bookend
    teardown:
      - screwdriver-artifact-bookend
      - screwdriver-cache-bookend
    
 [cluster_name]:
   default: [default_env]
   [env_name]:
        default: [default_executor]
        [executor_name]:
           setup:
              - scm
              - screwdriver-cache-bookend
           teardown:
              - screwdriver-artifact-bookend
              - screwdriver-cache-bookend
```

This will allow the system to pick the bookends based on different environments and executor configurations giving more flexibility to run muti-arch builds

Bookends should be selected based on a new bookend key comprising of `cluster_name.env_name.executor_name`, which defaults to the existing build cluster name.
