### ISSUE TITLE
Fan-In Job logic with blockedBy is not blocking anymore

### ISSUE THREAD

**Issue by jithine** [screwdriver-cd/screwdriver#2909]
**What happened**:

Consider the following workflow

```
deploy-fan-in:
    requires: [~build-dh-forwarder-prod, ~build-filter-router-prod, ~build-ingress-service-prod, ~build-splunk-forwarder-prod, ~build-transformer-prod, ~build-ingress-service-prod ]
    blockedBy: [~build-dh-forwarder-prod, ~build-filter-router-prod, ~build-ingress-service-prod, ~build-splunk-forwarder-prod, ~build-transformer-prod, ~build-ingress-service-prod]
    image:  node:18
    steps:
        - hello: echo hello
```
One user is using BlockedBy to simulate AND conditions in an otherwise OR workflow. Use is to let the fan-in job run in a scenario where not all upstream jobs might run. This used to work, before with some recent update it's behaving like a true OR without blocking. 

**What you expected to happen**:

`deploy-fan-in` in above config should continue to block if any upstream is still running. 
 

**How to reproduce it**:
