### ISSUE TITLE
Parser does not validate template cache settings

### ISSUE THREAD

**Issue by adong** [screwdriver-cd/screwdriver#2929]
**What happened**:
SD is not validating the cache setting before publishing, only complains after job is created 

Say, one template uses  [build-cache](https://docs.screwdriver.cd/user-guide/templates#using-the-build-cache) feature, and has some typos, like 

```
namespace: python-2304
name: rpm_publish
version: 2023.4.1
description: Template to publish packages
maintainer: some@email.com
config:
    template: python-2304/base@pre
    cache: true
```

If a pipeline uses that template, after starting an event, the pipeline will fail with the following errors:

```
"\"[0].permutations[0].cache\" must be of type object"
```

![image](https://github.com/screwdriver-cd/screwdriver/assets/15989893/da787831-388f-4b3e-abb8-2bdcf20d2748)

**What you expected to happen**:
SD ought to catch it at the config parser level, rather than after job creation.

**How to reproduce it**:

Create a template that has wrong cache settings, and start a pipeline that uses such a template.
