### ISSUE TITLE
Sometimes Remote Join build is executed twice when both remote trigger and remote join from the same job in the external pipeline are set in the pipeline.

### ISSUE THREAD

**Issue by kumada626** [screwdriver-cd/screwdriver#2935]
**What happened**:
Remote Join build is executed twice.

**What you expected to happen**:
Remote Join build is executed once.

**How to reproduce it**:
1. There are two pipelines like below.

pipeline1
```yaml
jobs:
  first:
    requires: [ ~commit ]
  and-join:
    requires: [ sd@2:job1, sd@2:job2 ]
  or-trigger:
    requires: [ ~sd@2:job1, ~sd@2:job2 ]
```
pipeline2
```yaml
jobs:
  job1:
    requires: [ ~sd@1:first ]
  job2:
    requires: [ ~sd@1:first ]
```

2. Start pipeline from pipeline1(start `first` job).
3. `and-join` and `or-trigger` jobs are executed twice.

![スクリーンショット 2023-09-15 9 27 59](https://github.com/screwdriver-cd/screwdriver/assets/8113204/099b28a8-f3ac-4c40-8050-8967de4ef398)
![スクリーンショット 2023-09-15 9 29 08](https://github.com/screwdriver-cd/screwdriver/assets/8113204/7b1458cf-a299-4e71-b21d-f2d784321f0a)

The user expects the `and-join` job to be executed only once.
Users may expect the `or-trigger` job to be executed only once as well, but that is up to the specification.
