### ISSUE TITLE
Validator page is overflowing when the workflow graph is long

### ISSUE THREAD

**Issue by y-oksaku** [screwdriver-cd/screwdriver#2971]
**What happened**:

Validator page is overflowing as below when the workflow graph is long.

![validator](https://github.com/screwdriver-cd/screwdriver/assets/43719835/079d5661-4fa1-444a-8ef6-95860c1c8454)

**What you expected to happen**:

It will be prevent overflow, such as by displaying horizontally scrollable content.

**How to reproduce it**:

1. Open validator page
2. Input `screwdriver.yaml` that has very long workflow graph

Example:

```yaml
jobs:
  long-long-job-name-1:
    image: node:18
    requires: [ ~commit, ~pr ]
    steps:
      - test: echo 'test'
  long-long-job-name-2:
    image: node:18
    requires: [ long-long-job-name-1 ]
    steps:
      - test: echo 'test'
  long-long-job-name-3:
    image: node:18
    requires: [ long-long-job-name-2 ]
    steps:
      - test: echo 'test'
  long-long-job-name-4:
    image: node:18
    requires: [ long-long-job-name-3 ]
    steps:
      - test: echo 'test'
  long-long-job-name-5:
    image: node:18
    requires: [ long-long-job-name-4 ]
    steps:
      - test: echo 'test'
  long-long-job-name-6:
    image: node:18
    requires: [ long-long-job-name-5 ]
    steps:
      - test: echo 'test'
  long-long-job-name-7:
    image: node:18
    requires: [ long-long-job-name-6 ]
    steps:
      - test: echo 'test'

```
