### ISSUE TITLE
Composing templates doesn't seem to compose parameters

### ISSUE THREAD

**Issue by QubitPi** [screwdriver-cd/screwdriver#3051]
**What happened**:

We have 2 screwdriver templates:

The first template has one parameter called `parameter-1`:

```yaml
---
namespace: MyTeam
name: template1
version: '1.0.0'
description: "1st template"
maintainer: me@gmail.com
config:
  image: buildpack-deps:22.04-scm
  parameters:
    parameter-1:
      value: "foo"
  steps:
    - setup-jdk: ...
```

A second template composes with the first template and adds an extra parameter called `parameter-2`:

```yaml
---
namespace: MyTeam
name: template2
version: '1.0.0'
description: "2nd template"
maintainer: me@gmail.com
config:
  template: MyTeam/template1
  order: [setup-jdk, install-maven]
  parameters:
    parameter-2:
      value: "bar"
  steps:
    - install-maven: ...
```

We we have a `screwdriver.yaml` that uses `template2`:

```yaml
---
jobs:
  main:
    requires: [~pr, ~commit]
    template: MyTeam/template2@latest
```

When we were asked to enter the parameter values on UI before triggering the pipeline defined by `screwdriver.yaml`, **we only saw the `parameter-1` showed up in the "Are you sure to start?" popup window, but not both `parameter-1` and `parameter-2`**

**What you expected to happen**:

The [documentation on template composition](https://docs.screwdriver.cd/user-guide/templates#template-composition) doesn't define the behavior of parameter composition, so we are expecting both `parameter-1` and `parameter-2` to show up.
