### ISSUE TITLE
Add support for cache settings in pipeline templates

### ISSUE THREAD

**Issue by JWFGit** [screwdriver-cd/screwdriver#3058]
**What happened**:
Trying to migrate parent pipeline like
```

---
version: 4

cache:
  event:
    - $SD_SOURCE_DIR/target
    - $SD_SOURCE_DIR/build
    - $SD_SOURCE_DIR/kubernetes_generated/all_buckets
  job:
    build: [ ~/.m2, ~/.gradle ]
    build-pr: [ ~/.m2, ~/.gradle ]

shared:
  environment:
    SD_SETTING_SD_PR_COMMENTS: 'yes'

  annotations:
    screwdriver.cd/mergeSharedSteps: true
    init-component: &init-component |
      export COMPONENT=$(meta get COMPONENT)
      export DOCKER_NAME=$COMPONENT
      meta set JOB_START `date +%s%3N`
  settings:
    slack:
      channels: [ a-channel ]
      statuses: [ FAILURE ]
      minimized: true
  steps:
    - postsetup-metric: *init-component
    - postinit: *init-component

annotations:
  screwdriver.cd/chainPR: true

  kickoff-step: &kickoff-step |
    VERSION=$(meta get Version)
    ID=$(meta get ID)
    COMPONENT=$(meta get Component)
    PARAMETERS=$(meta get Parameters)
    echo "Kicking off release:"
    echo "    Component: ${COMPONENT}"
    echo "      Version: ${VERSION}"
    echo "   Release ID: ${ID}"
    echo "   Parameters: ${PARAMETERS}"

  notification-settings: &notification-settings
    settings:
      email:
        addresses:
          - 'pe_advserving_pbp@yahooprod.opsgenie.net'
        statuses:
          - FAILURE
          - SUCCESS
jobs:

  tag:
    requires: [ ~commit ]
    environment:
      SEMVER_TASK: tag
    template: simple-semantic-version@stable

  build-pr:
    image: docker.com:4443/my/ops:1-stable
    <<: *notification-settings
    steps:
      - kickoff: *kickoff-step
  build:
    image: docker.com:4443/my/ops:1-stable
    <<: *notification-settings
    steps:
      - kickoff: *kickoff-step
```

But it looks like the cache settings are not supported

`"config.cache" is not allowed`

**What you expected to happen**:

Support all valid configuration settings from screwdriver.yaml in pipeline templates

**How to reproduce it**:
Try to validate the above example
