### ISSUE TITLE
Implement modification to flatten pipeline template config by eliminating shared config during parser 

### ISSUE THREAD

**Issue by VonnyJap** [screwdriver-cd/screwdriver#3068]
## Functionality
Flatten template config to eliminate shared config during parser

## Component
config-parser

## Details

Refer to [the document for details](https://github.com/screwdriver-cd/screwdriver/blob/wip-design/design/pipeline-template.md#flatten-template-config-to-eliminate-shared-config-during-parser). 

Example config
```
shared:
  image: node:10
  environment:
    VAR1: "one"
    VAR2: "two"
  steps:
    - init: npm install
    - test: npm test
jobs:
  main:
    requires: [~pr, ~commit]
  second:
    requires: [main]
```
It should be stored as below, eliminating the shared config and flattening it into the jobs.
```
jobs:
  main:
    requires: [~pr, ~commit]
    image: node:10
    environment:
      VAR1: "one"
      VAR2: "two"
    steps:
      - init: npm install
      - test: npm test
  second:
    requires: [main]
    image: node:10
    environment:
      VAR1: "one"
      VAR2: "two"
    steps:
      - init: npm install
      - test: npm test
```

After the flattening, [the shared field](https://github.com/screwdriver-cd/data-schema/blob/54a8ab5985dbe76b456f07e1dc2e75dabbfc1dbb/config/pipelineTemplate.js#L13) in the pipelineTemplate config will be eliminated, and the data from shared in screwdriver.yaml should be stored in [jobs field](https://github.com/screwdriver-cd/data-schema/blob/54a8ab5985dbe76b456f07e1dc2e75dabbfc1dbb/config/pipelineTemplate.js#L12). 

Steps might be a shared config that needs special treatment, i.e. when `screwdriver.cd/mergeSharedSteps` annotation is set to false for a specific job, then the shared steps will not be flattened into the jobs. 

This particular task can be completed in two steps: 

- flatten all shared data without considering the special treatment for steps
- flatten the shared steps
