### ISSUE TITLE
Workflow graph - Non stage jobs overlap into the stage in the UI

### ISSUE THREAD

**Issue by sagar1312** [screwdriver-cd/screwdriver#3098]
**What happened**:
Non stage jobs are being positioned under stage on the workflow graph in the UI giving a false impression that those jobs are part of the stage.

Example:
<img width="791" alt="image" src="https://github.com/screwdriver-cd/screwdriver/assets/2124590/c317df97-bdfd-47b7-92ad-260a1bfac1c4">

Pipeline config (screwdriver.yaml)
```
shared:
    image: node:20
    steps:
        - init: echo 'init'
jobs:
    triggering-stage:
        requires: [~pr, ~commit]
    non-stage-job-alpha:
        requires: [triggering-stage]
    ci-deploy:
        requires: [ ]
    ci-test-batch-1:
        requires: [ ci-deploy ]
    ci-test-batch-2:
        requires: [ ci-deploy ]
    ci-certify:
        requires: [ ci-test-batch-1, ci-test-batch-2 ]
    triggered-by-stage:
        requires: [ ~stage@integration ]

stages:
    integration:
        requires: [triggering-stage]
        jobs: [ci-deploy, ci-test-batch-1, ci-test-batch-2, ci-certify]
        description: "This stage will deploy the latest application to CI environment and certifies it after the tests are passed."
``` 

**What you expected to happen**:
Non stage jobs should be positioned outside stage jobs

**How to reproduce it**:
Create a pipeline with above screwdriver.yaml config.
