### ISSUE TITLE
Flatten shared steps to jobs in the pipeline template

### ISSUE THREAD

**Issue by VonnyJap** [screwdriver-cd/screwdriver#3105]
**What happened**:

The default action for flattening shared steps is overwriting, which means that steps in the job configuration will overwrite those defined in the shared steps. See the current implementation according to https://github.com/screwdriver-cd/template-validator/pull/39/files

**What you expected to happen**:

When `screwdriver.cd/mergeSharedSteps` is set to true, either from the job or shared configuration, the steps are merged between the shared configuration and those defined in the job template configuration.

Given an example of a pipeline template using job template and annotation `screwdriver.cd/mergeSharedSteps` with the configuration below.

```
namespace: sd-test
name: example-template
version: '1.0.0'
description: An example pipeline template for testing golang files
maintainer: foo@bar.com
config:
  shared:
    annotations:
      screwdriver.cd/mergeSharedSteps: true
    steps:
       - premotd: echo build
  jobs:
    main:
      template: python/package_rpm@latest
      requires: [~pr, ~commit]
      steps:
        - preinit_os: echo replace
        - begin: echo begin
```

The resulting configuration after flattening would be
```
jobs:
  main:
    steps:
      - begin: echo begin
      - premotd: echo build
      - motd: cat << EOF
          This job will generate rpm packages, check them repository.
        EOF
      - preinit_os: echo replace
      - init_os: sd-cmd exec python/python_bootstrap@stable
        source /tmp/python_bootstrap.env
...
```
