### ISSUE TITLE
Enable users utilizing pipeline templates to customize image, settings, environment, and requires within the job configuration

### ISSUE THREAD

**Issue by VonnyJap** [screwdriver-cd/screwdriver#3106]
**What happened**:

At present, users utilizing a pipeline template are restricted from making any modifications within the job configuration.

**What you expected to happen**:

Enable users to customize the customize image, settings, environment, and requires within the job configuration of pipelines that are using a template.

Given a pipeline template below:
```
shared:
  image: node:10
  environment:
    VAR1: "one"
    VAR2: "two"
  steps:
    - init: npm install
    - test: npm test
  settings:
    email: [test@email.com, test2@email.com]
    slack: 'mychannel'

jobs:
  main:
    requires: [~pr, ~commit]
  second:
    requires: [main]
```

And user defined pipeline:
```
template: sd-test/example-template@latest
jobs:
  main:
    requires: [~commit]
    image: node:20
    settings:
      email: [test@email.com, test3@email.com]
    environment:
      VAR3: "three"
      VAR1: "empty"
```

Final config should be:
```
jobs:
  main:
    	requires: [~commit]
        image: node:20
        steps:
            - init: npm install
            - test: npm test
        environment:
            VAR1: "empty"
            VAR2: "two"
            VAR3: "three"
        settings:
      	    email: [test@email.com, test3@email.com]
      	    slack: 'mychannel'
  second:
    	requires: [main]
        image: node:10
        steps:
            - init: npm install
            - test: npm test
        environment:
            VAR1: "one"
            VAR2: "two"
        settings:
            email: [test@email.com, test2@email.com]
            slack: 'mychannel'
   ```
