### ISSUE TITLE
Config parse error for validator on pipeline extending a pipeline template

### ISSUE THREAD

**Issue by VonnyJap** [screwdriver-cd/screwdriver#3109]
**What happened**:

Observed config parse error when validating a pipeline that utilizes a pipeline template 
 
<img width="1892" alt="Screenshot 2024-05-02 at 4 16 53 PM" src="https://github.com/screwdriver-cd/screwdriver/assets/7771180/f8c58a80-f2b8-42d8-93f5-7c7fdcb49aaf">

**What you expected to happen**:

Validator should not show an error for pipeline that utilizes a pipeline template 

**How to reproduce it**:

Paste this pipeline into a validator to reproduce. 

```
template: sd-test/example-template@latest
shared:
  environment: 
    FOO: bar
jobs:
  main:
    image: node:lts
```
