### ISSUE TITLE
Show pipeline level config for pipeline template in the validator

### ISSUE THREAD

**Issue by VonnyJap** [screwdriver-cd/screwdriver#3110]
**What happened**:

The validator does not display pipeline level configuration when validating a pipeline template.

<img width="1913" alt="Screenshot 2024-05-02 at 4 32 00 PM" src="https://github.com/screwdriver-cd/screwdriver/assets/7771180/fc551354-f179-4c64-a1ae-c09f1fbccdb9">

**What you expected to happen**:

The validator should also display all pipeline-level configurations.

**How to reproduce it**:

Paste this config into the validator
```
namespace: sd-test
name: example-template
version: '1.0.0'
description: An example pipeline template for testing golang files
maintainer: foo@bar.com
config:
  parameters:
    nameA: "value1"
  annotations:
    screwdriver.cd/restrictPR: none
    screwdriver.cd/chainPR: false
  cache:
    event: [$SD_SOURCE_DIR/node_modules]
  subscribe:
    scmUrls:
      - git@github.com:supra08/functional-workflow.git: ['~commit', '~pr']
  shared:
    image: golang
    environment:
        FOO: "Bar"
  jobs:
    main:
      steps:
        - name: echo "pipeline template test"
```
