### ISSUE TITLE
Inheritance methods of Metadata is not intuitive

### ISSUE THREAD

**Issue by yakanechi** [screwdriver-cd/screwdriver#3125]
**What happened**:
If there are multiple trigger sources for the current metadata, the value of the job that completed first takes precedence.
In the following example, the value is set in job1 and then reset in job3, but job2 is completed before job3, so the value of x is 1 in job4.
It seems strange that values set later are not used.

**What you expected to happen**:
Consider adding a timestamp-like feature for each metadata, with the newly added ones taking precedence.

**How to reproduce it**:
```
jobs:
  Job1:
    requires: [ ~commit ]
    steps:
      - meta set x "1"

  Job2:
    requires: [ ~Job1 ]
    steps:
      - echo "nothing"

  Job3:
    requires: [ ~Job1 ]
    steps:
      - sleep 60
      - meta set x "2"

  Job4:
    requires: [ Job2, Job3 ]
    steps:
      - echo $(meta get x)

```

**Comment by VonnyJap** [comment]
@sagar1312 @tkyi - do you guys have any thoughts on how to solve this issue? Basically this looks like a bug, `x` should be seen as `2` in `Job4`, but users are seeing the old value `1` returned.

**Comment by tkyi** [comment]
Yeah that sounds like a bug. Should be the more recently finished build that takes precedence.

**Comment by VonnyJap** [comment]
@yakanechi - I was able to reproduce this issue. 
https://cd.screwdriver.cd/pipelines/15511/events/823582
https://github.com/VonnyJap/screwdriver-config/blob/main/test-meta/screwdriver.yaml

I believe this can be fixed with this implementation below:
Sort by build endtime is performed prior to [the merge of all parent builds metadata](https://github.com/screwdriver-cd/launcher/blob/4321ca459c39220e374f7cbad84d687585071c78/launch.go#L501-L511). 

Will your side be able to make a launcher change on this?

**Comment by yakanechi** [comment]
@VonnyJap 
Yes, we plan to fix this in the near future.

**Comment by kumada626** [comment]
Only sort parent builds by build endtime not solve below case.
```
jobs:
  Job1:
    requires: [ ~commit ]
    steps:
      - meta set x "1"

  Job2:
    requires: [ ~Job1 ]
    steps:
      - meta set x "2"

  Job3:
    requires: [ ~Job1 ]
    steps:
      - sleep 60
      - echo "nothing"

  Job4:
    requires: [ Job2, Job3 ]
    steps:
      - echo $(meta get x)
```
In that case, `x` should be seen as `2` in Job4, but users are seeing the old value `1` returned.
Because `x` is set in Job1 and is carried over to Job3, when the meta of Job3 is merged, `x` is also overwritten with the value of Job3.
I think that something like a timestamp per metadata key might be needed to solve this problem.
