### ISSUE TITLE
RemoteJoin is not triggered on restart in specific cases

### ISSUE THREAD

**Issue by yakanechi** [screwdriver-cd/screwdriver#3133]
**What happened**:
If a RemoteJoin job has `requires: [sd@2:a. sd@2:b]` and a and b jobs failed, it will not be triggered even if both jobs succeed on restart.
If one of the jobs is successful, it will be triggered by Restart correctly.

First start
<- Upstream, Downstream ->
<img src=https://github.com/screwdriver-cd/screwdriver/assets/138551445/501569d5-d3d8-4023-997c-40c0d34de423 width="50%" /><img src=https://github.com/screwdriver-cd/screwdriver/assets/138551445/0fdfc8ae-5f85-497f-965a-9650d23cf469 width="50%" />

Restart from the downstream hub and success jobs
<- Upstream, Downstream ->
<img src=https://github.com/screwdriver-cd/screwdriver/assets/138551445/bae1b373-187c-470a-b9d8-9a5ca3292958 width="50%" /><img src=https://github.com/screwdriver-cd/screwdriver/assets/138551445/2201d216-5300-4f5c-b083-2c94dd4203a0 width="50%" />

**What you expected to happen**:
Triggered remote join job if downstream jobs succeed on restart even if both failed

**How to reproduce it**:
Minimum configuration is as follows

Upstream
```yaml
shared:
  image: node:20
  steps:
    - test: echo 'test'
    
jobs:
  hub:
    requires: [ ~commit, ~pr ]
  target:
    requires: [ sd@2:a, sd@2:b]
```

Downstream
```yaml
shared:
  image: node:20
  steps:
    - test: echo 'test'
    
parameters:
  success: [' ', 'true', 'false']

jobs:
  hub:
    requires: [ ~sd@1:hub ]
  a:
    requires: [ ~hub ]
    steps:
      - metadata: |
          if [ "$(meta get parameters.success.value)" != 'true' ]; then
            exit 1
          fi
  b:
    requires: [ ~hub ]
    steps:
      - metadata: |
          if [ "$(meta get parameters.success.value)" != 'true' ]; then
            exit 1
          fi

```
