### ISSUE TITLE
Validator is not showing the stages when rendering workflowgraph for pipeline template

### ISSUE THREAD

**Issue by VonnyJap** [screwdriver-cd/screwdriver#3160]
**What happened**:

Stages is not being rendered in an enclosed section when pipeline template is being validated in a validator. Please see the screenshot. 

<img width="1707" alt="Screenshot 2024-07-31 at 11 27 10 PM" src="https://github.com/user-attachments/assets/13f94662-ba21-44df-bb8f-efa1e7f67296">

**What you expected to happen**:

Stages should be rendered as an enclosed section when validating pipeline template in a validator. 

**How to reproduce it**:
Use the yaml below
```
namespace: sd-test
name: example-template
version: '1.0.0'
description: An example pipeline template for testing golang files
maintainer: foo@bar.com
config:
  ## Stages by grouping
  shared:
    image: node:14
    steps:
      - init: echo 'init'
  jobs:
    # triggering-stage:
    #   requires: [~pr, ~commit]
    ci-deploy:
      requires: []
    ci-test:
      requires: [ci-deploy]
    ci-certify:
      requires: [ci-test]
    triggered-by-stage:
      requires: [~stage@integration]

  stages:
    integration:
      requires: [~commit]
      jobs: [ci-deploy, ci-test, ci-certify]
      description: "This stage will deploy the latest application to the CI environment and certify it after the tests have passed."
```
and put into the validator
