### ISSUE TITLE
Stages - teardown job is triggered even if all other jobs are not finished

### ISSUE THREAD

**Issue by kumada626** [screwdriver-cd/screwdriver#3176]
**What happened**:
Stage teardown job is triggered soon after one of a last job in the stage is finished even if there is a running job in that stage.
In the following pipeline, `stage@sandbox:teardown` job is triggered after `sandbox-e2e-test` finishes while `sandbox-test` is still running.
![スクリーンショット 2024-08-23 14 06 28](https://github.com/user-attachments/assets/0e57c13e-2f4e-40cd-a1de-fef8a3261b26)

**What you expected to happen**:
Teardown job should be triggered after all other jobs in the stage are finished.

**How to reproduce it**:
1. provide a pipeline that has following screwdriver.yaml.
```
shared:
  image: node:20
  steps:
    - test: echo 'test'
 
stages:
  sandbox:
    requires: [ ~commit ]
    description: Deploy sandbox and test
    jobs: [ sandbox-deploy, sandbox-e2e-test, sandbox-test ]
    teardown:
      steps:
        - init: echo 'sandbox teardown'
 
jobs:
  sandbox-deploy:
    description: empty
  sandbox-e2e-test:
    requires: [ sandbox-deploy ]
  sandbox-test:
    requires: [ sandbox-deploy ]
    steps:
      - sleep: sleep 60
```
2. start this pipeline.
3. `stage@sandbox:teardown` job is triggered before `sandbox-test` job is finished.
