### ISSUE TITLE
Remote join jobs are not triggered correctly on restart

### ISSUE THREAD

**Issue by yakanechi** [screwdriver-cd/screwdriver#3177]
**What happened**:
Remote join may not be triggered correctly when restarting an event containing a remote join job.
Specifically, it is triggered as a remote trigger and executed on a different event than the group event on restart.
Also, an empty event is created for the number of downstream jobs in the trigger condition.

This especially occurs when all trigger conditions are remote jobs.
On the other hand, if there is at least one job in the same pipeline in the trigger condition, there is no problem.
(See second job in the screenshot below).

**What you expected to happen**:
Remote join job is triggered successfully on restart event.

**How to reproduce it**:
1. Run with the following configuration
2. Restart from first job

```
jobs:
  first:
    requires: [ ~commit, ~pr ]

  first2:
    requires: [ ~first ]

  second:
    requires: [ first2, sd@23:component, sd@35:component, sd@36:component ]

  third:
    requires: [ sd@23:first, sd@23:second, sd@23:third, sd@35:first, sd@35:second, sd@35:third, sd@36:first, sd@36:second, sd@36:third ]
```

Start
![start](https://github.com/user-attachments/assets/b93ba277-3a41-4d1f-bc33-29b00a46b963)
Restart event
![restart1](https://github.com/user-attachments/assets/d06e58fb-e39d-41de-86fc-90ad742c4727)
Last remote join job event
![restart2](https://github.com/user-attachments/assets/96d08b12-2c49-457f-9809-9ed3e688cebd)
