### ISSUE TITLE
Past status of diabled jobs is referenced on restart

### ISSUE THREAD

**Issue by yakanechi** [screwdriver-cd/screwdriver#3183]
**What happened**:
For example, the following pipeline is executed once
After that, "first2" is disabled and restarted from "first1".

In the current specification, "second" is triggered by reference to the past status of "first2", despite first2 being disabled.

This specification seems a bit strange to me.
The user should assume that "second" jobs and subsequent jobs that have "second" job as a trigger will also not be triggered because of the fact that it is disabled.

**What you expected to happen**:
Do not refer to the past status of disabled job.

**How to reproduce it**:
<- Start, Resart ->
<img src="https://github.com/user-attachments/assets/19b39a40-3454-44c0-82eb-f5fd7047edd3" width="30%"> <img src="https://github.com/user-attachments/assets/431841e7-597c-4615-aeb1-867cfa1547f2" width="30%">

```
jobs:
  first1:
    requires: [ ~commit ]
  first2:
    requires: [ ~commit ]
  second:
    requires: [ first1, first2 ]
```
