### ISSUE TITLE
screwdriver.cd/displayName is parsed as numeric value

### ISSUE THREAD

**Issue by y-oksaku** [screwdriver-cd/screwdriver#3190]
**What happened**:

`screwdriver.cd/displayName` is parsed as Numeric value when it is not enclosed double quote.
Then the value converts exponential form if it is huge value.

<img width="1311" alt="ex" src="https://github.com/user-attachments/assets/e6fb64ee-0b40-4737-bc12-3bfd15ec4630">

```yaml
jobs:
  test:
    image: node:18
    requires: [ ~commit, ~pr ]
    steps:
      - test: echo "foo"
    annotations:
      screwdriver.cd/displayName: 123456789012345678901234567890
```

**What you expected to happen**:

`displayName` value is always parsed as String.

**How to reproduce it**:

Set numeric value into `displayName`. (e.g. `12345`, `0.12345` NOT `"123"`)
