### ISSUE TITLE
Build Details View: Differentiate Visual Representation of Virtual Job from Normal Job

### ISSUE THREAD

**Issue by VonnyJap** [screwdriver-cd/screwdriver#3211]
**What happened**:

The virtual job's build console log indicated that sd-setup-init was encountering an error.

<img width="1700" alt="Screenshot 2024-09-29 at 12 11 27 AM" src="https://github.com/user-attachments/assets/eb779de0-56b3-4696-ba95-46d1fe0c03d7">

**What you expected to happen**:

The virtual job build log should not display a build page and should be highlighted with a different color or indicator in the workflow graph.

**How to reproduce it**:

Use this sample of screwdriver config
```
shared:
  image: node:14
  steps:
    - init: echo 'init'

jobs:
  triggering-ci:
    requires: [ ~pr, ~commit ]
  ci-setup-virtual:
    requires: [ ~triggering-ci ]
    annotations:
      screwdriver.cd/virtualJob: true
  ci-deploy:
    requires: [ ~ci-setup-virtual ]
  ci-test:
    requires: [ ci-deploy ]
  ci-certify:
    requires: [ ci-test ]
  ci-teardown-virtual:
    requires: [ ci-certify ]
    annotations:
      screwdriver.cd/virtualJob: true
  triggered-after-ci:
    requires: [ ~ci-teardown-virtual ]
```
