### ISSUE TITLE
Virtual Job should not need a step

### ISSUE THREAD

**Issue by VonnyJap** [screwdriver-cd/screwdriver#3218]
**What happened**:

Having a validation error when virtual job does not contain a step. See below.

<img width="1904" alt="Screenshot 2024-10-03 at 5 01 36 PM" src="https://github.com/user-attachments/assets/ae653106-ed74-4b02-94ed-2fdd46a081ec">

**What you expected to happen**:

Virtual job should not need a step since it is a no-op and execution is skipped. 

**How to reproduce it**:

```
shared:
  image: node:14


jobs:
  triggering-ci:
    requires: [ ~pr, ~commit ]
    steps:
        - init: echo 'init'
  ci-setup-virtual:
    requires: [ ~triggering-ci ]
    annotations:
      screwdriver.cd/virtualJob: true
```
Paste the config above in validator.
