### ISSUE TITLE
Missing GH status when running virtual job on PR

### ISSUE THREAD

**Issue by VonnyJap** [screwdriver-cd/screwdriver#3228]
**What happened**:

Opened a PR to run a job as virtual. 
https://github.com/VonnyJap/screwdriver-config/pull/2/files

[Job](https://cd.screwdriver.cd/pipelines/14895/pulls) showed success. 
![Screenshot 2024-10-18 at 11 31 04 PM](https://github.com/user-attachments/assets/c25d34a3-a6f7-48f2-ae8d-faabd4d2200f)

But GH status is pending.
![Screenshot 2024-10-18 at 11 31 42 PM](https://github.com/user-attachments/assets/29b5926b-302a-441b-949a-ebdc216612ac)

**What you expected to happen**:
GH status should be updated with success build on PR job.

**How to reproduce it**:

Use config below to test out.

```
shared:
  image: node:14
  steps:
    - init: echo 'init'

jobs:
  triggering-ci:
    requires: [ ~pr, ~commit ]
    annotations:
      screwdriver.cd/virtualJob: true
  ci-setup-virtual:
    requires: [ ~triggering-ci ]
    annotations:
      screwdriver.cd/virtualJob: true
  ci-deploy:
    requires: [ ~ci-setup-virtual ]
```
