### ISSUE TITLE
The display of virtual job icon is broken

### ISSUE THREAD

**Issue by yakanechi** [screwdriver-cd/screwdriver#3247]
**What happened**:
After the build starts and then stops, the display of virtual job icon becomes huge and the SUCCESS icon appears as shown in the following image.
The same applies to event cards.
<img src="https://github.com/user-attachments/assets/651dea3e-c63b-412b-9677-feb9dd83809a"/><img src="https://github.com/user-attachments/assets/386f77e9-119b-4bde-beb1-6eb453ee2cdd"/><img src="https://github.com/user-attachments/assets/13a3bf67-fee6-4f0a-b231-8e2c7be9ca55"/>

If you move to another event or reload, it will be displayed normally.
<img src="https://github.com/user-attachments/assets/ae0ef6b6-ba0d-4cb0-a341-574f57a5d8da"/>

**What you expected to happen**:
Icons are always displayed correctly

**How to reproduce it**:
Start build and immediately stop.
```
shared:
  image: centos:centos7
  steps:
    - echo "Hello"

jobs:
  normal:
    requires: [ ~commit, ~pr ]
  virtual:
    annotations:
      screwdriver.cd/virtualJob: true
  build1:
    requires: [ virtual ]
  build2:
    requires: [ virtual ]
```
