### ISSUE TITLE
Enable sourcePaths to be used in stages

### ISSUE THREAD

**Issue by yakanechi** [screwdriver-cd/screwdriver#3271]
**What happened**:
Cannot use sourcePaths for jobs in stage.
Jobs in stage are triggered ignoring sourcePaths.

**What you expected to happen**:
Jobs in a stage can control triggers with sourcePaths.

**How to reproduce it**:
Assigned sourcePaths to jobs in a stage
All jobs in the stage are triggered.

**Comment by yk634** [comment]
**Why sourcePaths are ignored in stage:**

The sourcePaths works on the first job of the event triggered by webhook.
However, when using stage, the first job is a setup job. This is true even if the user has not defined a setup job.

Therefore, setting sourcePaths to the first normal job in a stage does not work.

```yaml
jobs:
    first:
        requires: []
        sourcePaths: "directory/" # does not work
        ...
    second:
        requires: [ ~first ]
        ...
stages:
    foo:
        requires: [ ~commit ]
        jobs: [ first, second ]
```

**Enhancement Idea:**

I would like to be able to set sourcePaths as config for stage as follows.

```yaml
jobs:
    first:
        requires: []
        ...
    second:
        requires: [ ~first ]
        ...
stages:
    foo:
        requires: [ ~commit ]
        jobs: [ first, second ]
        sourcePaths: "directory/" # set here
```

**Comment by minghay** [comment]
I am not aware of any potential problems with adding `sourcePaths` to the stage configuration.  The configuration schema validation would be updated to enforce `sourcePaths` not appearing for jobs that are part of a stage?

**Comment by VonnyJap** [comment]
@yk634 - that will be the direction that I will take as well for implementing the sourcePaths on the stage, though sourcePaths should be a list instead of a string, this is aligned with the [current design](https://docs.screwdriver.cd/user-guide/configuration/sourcePaths.html). Additionally, I propose that behind the scene, the sourcePaths at the stage is actually going to be implemented technically on the setup job as the first job in the stage. 

@sagar1312 - do you have any other input?

**Comment by sagar1312** [comment]
Yes @VonnyJap that is exactly the approach I had in mind. The `sourcePaths` on the stage should should exactly follow the same schema as the `sourcePaths` on job. 

Behind the scene the `sourcePaths` configured on the stage should be copied as the `sourcePaths` on the stage `setup` job. This is similar to how we copy `requires` configured for a stage to its `setup` job.

That said we should also address the scenario where `sourcePaths` is configured for a stage as well as it is configured for the `setup` job
Ex
```
jobs:
    first:
        ...
    second:
        requires: [ ~first ]
        ...
stages:
    foo:
        requires: [ ~commit ]
        jobs: [ first, second ]
        sourcePaths: ["directory/"] # set here
        setup:
            sourcePaths: ["directory/"] # set here
```
I think we should let the `sourcePaths` configured at `setup` override the `sourcePaths` configured for that stage. In short, the stage `sourcePaths` would be ignored in this case.
