### ISSUE TITLE
Metadata cannot be preferentially inherited from virtual jobs

### ISSUE THREAD

**Issue by yakanechi** [screwdriver-cd/screwdriver#3287]
**What happened**:
related #3235

In the following workflow, `target` cannot get the metadata of a in priority.
Therefore, `target` may take over `b`'s metadata instead of `a`'s metadata.

```
shared:
  image: node:22

jobs: 
  a:
    requires: [ ~commit ]
    steps:
      - meta set x "a"

  b:
    requires: [ ~commit ]
    steps:
      - meta set x "b"

  virtual:
    requires: [ ~a ]
    steps:
      - meta set x "a"
    annotations:
      screwdriver.cd/virtualJob: true

  target:
    requires: [ ~virtual ]
    blockedBy: [ ~b ]
    steps:
      - check_meta: test "a" = `meta get "x"`
```

**What you expected to happen**:
The metadata of `a` can be preferentially inherited.

**How to reproduce it**:

**Comment by yakanechi** [comment]
Basically, the following PRs will fix the problem.
https://github.com/screwdriver-cd/screwdriver/pull/3288

However, if a Virtual Job is triggered "AND" triggered by multiple jobs, and if those jobs complete at about the same time, the bug may occur.

For example, if `a` and `b` are completed almost simultaneously in the following workflow
1. After the completion of `a`, the trigger process of virtual is performed and the meta of `a` is transferred to `virtual`.
2. At this time, if the status of `b` is SUCCESS, virtual is executed without waiting for the trigger process from `b`.
3.`target` is triggered immediately from `virtual`
4. After that, `b`'s trigger process is performed and `virtual` inherits b's meta, but `target` cannot inherit b's meta because `target`'s build has already been started.
```
shared:
    image: node:22
    steps:
        - echo: echo "test"

jobs:
    hub:
        requires: [ ~commit, ~pr ]
        annotations:
            screwdriver.cd/virtualJob: true

    a:
        requires: [ ~hub ]
        steps:
            - set: meta set foo.bar "success"

    b:
        requires: [ ~hub ]
        steps:
            - set: meta set foo.baz "success"

    c:
        requires: [ ~hub ]
        steps:
            - set: meta set foo.bar "error"

    d:
        requires: [ ~hub ]
        steps:
            - set: meta set foo.baz "error"

    virtual:
        requires: [ a, b ]
        annotations:
            screwdriver.cd/virtualJob: true

    target:
        requires: [ ~virtual ]
        blockedBy: [ ~c, ~d ]
        steps:
            - print: meta get "foo"
            - check_meta: |
                  test "success" = `meta get "foo.bar"`
                  test "success" = `meta get "foo.baz"`
```
