### ISSUE TITLE
Vertical position of stages is changed when collapse/expand a stage

### ISSUE THREAD

**Issue by y-oksaku** [screwdriver-cd/screwdriver#3324]
**What happened**:

Stages move vertically when we collapse or expand the stages on the same depth.

**What you expected to happen**:

Keep the original position if we collapse/expand stages.

**How to reproduce it**:

1. Create a pipeline with the following sd.yaml
2. Collapse the `bar` stage

```yaml
shared:
  image: node:20
  steps:
    - hello: echo 'hello'

jobs:
  main:
    requires: [ ~commit, ~pr ]
  job1:
    requires: []
  job2:
    requires: []
  job3:
    requires: []
  target-job-with-long-name:
    requires: [ stage@foo, stage@bar, stage@baz]

stages:
  foo:
    requires: [ ~main ]
    jobs: [ job1 ]
  bar:
    requires: [ ~main ]
    jobs: [ job2 ]
  baz:
    requires: [ ~main ]
    jobs: [ job3 ]
```
