### ISSUE TITLE
Bug that allows builds to be started on non-existent stages

### ISSUE THREAD

**Issue by yakanechi** [screwdriver-cd/screwdriver#3334]
**What happened**:
There is no error, e.g. with validator, even if there is a job with a non-existent stage specified as requires.

Therefore, the build can be started. 
However, no jobs are displayed in the UI.

![Image](https://github.com/user-attachments/assets/24a835e3-d05b-4ddf-87c9-12da81dde291)

**What you expected to happen**:
Errors occur in jobs where a non-existent stage is specified in validator (config-parser).

**How to reproduce it**:
https://cd.screwdriver.cd/pipelines/15710/events/830613

```YAML
jobs:
  ci-deploy:
    requires: []
  ci-test:
    requires: [ci-deploy]
  ci-certify:
    requires: [ci-test]
  triggered-by-stage:
    requires: [~stage@integration2] # <- Caused by

stages:
  integration:
    requires: [~commit]
    jobs: [ci-deploy, ci-test, ci-certify]
    description: "This stage will deploy the latest application to the CI environment and certify it after the tests have passed."
```
