### ISSUE TITLE
Cannot overwrite settings from job in pipeline template

### ISSUE THREAD

**Issue by yakanechi** [screwdriver-cd/screwdriver#3343]
**What happened**:
Cannot overwrite "settings" from job to empty when using pipeline template and shared.

It also behaves differently when settings are originally defined in the pipeline template 
- If settings are defined in shared, the settings in shared are set to the job.
- If settings are defined in job, the result is a deepMerge of the pipeline template and the job's settings.
-- For example, if "slack.minimized" is set in the pipeline template, setting "channels" and "statuses" in the job will apply "channels", "statuses" and "minimized".

**What you expected to happen**:
- The job can override the settings to empty.
- Shared and job overwrite methods are aligned when using pipeline templates.

**How to reproduce it**:
Define settings in"shared" and empty settings in "job" as follows

```
template: screwdriver-cd-test/test-pipeline-template@1.0.1

shared:
  settings:
    slack:
      channels:
        - group:foo
      statuses:
        - FAILURE

jobs:
  main:
    settings: {}
```
