### ISSUE TITLE
Ability to use multiple scms

### ISSUE THREAD

**Issue by catto** [screwdriver-cd/screwdriver#365]
It would be nice if we could use multiple scms such as GitHub.com and GitHub Enterprise.
Do you have any plan to achieve it?

**Comment by d2lam** [comment]
@catto  This should be already working. To use GHE, you need to add `SCM_GITHUB_GHE_HOST` environment variable. Does this documentation help: http://screwdriver.cd/getting-started/plugins/#source-control

**Comment by stjohnjohnson** [comment]
@d2lam I think @catto is looking for the ability to support multiple SCMs at one time.

**Comment by catto** [comment]
Ah, yes, I meant to say about the ability to use the scms at one time like below
```yaml
scms:
    - github.com:
      plugin: github
      oauthClientId: githubclientid
      oauthClientSecret: githubclientsecret
      secret: githubsecret
    - ghe:
      plugin: github
      oauthClientId: gheclientid
      oauthClientSecret: gheclientsecret
      gheHost: github.mysite.org
      secret: ghesecret
```

**Comment by stjohnjohnson** [comment]
Right now our recommendation is going to be to run multiple clusters.  However, we'd be open to hear any ideas you have around how to make this kind of change (as it would touch all parts of SD).

**Comment by catto** [comment]
@stjohnjohnson Thank you, I got it. I'll think about it and let you know if I find the way how to achieve it.

**Comment by catto** [comment]
I had think about this feature, and I came up with one idea.
It uses an authentication context and switches the context completely between multiple scms.

The abstract is as follows.
* Cluster admin configures multiple scms to their cluster, like [this](https://github.com/screwdriver-cd/screwdriver/issues/365#issuecomment-262134135).
* Screwdriver shows multiple login buttons for each scm in the login page.
* When an authentication is completed, Screwdriver issues a session cookie for a user with an auth context.
    * This can be "github.com:catto" or "my-ghe:catto"
    * It is better to show a user name with an auth context in the header.
* If a user wants to use other scm, the user need to re-login to the desired scm.

This method would require major changes to the user model, but it seems that other ones don't need to do so much.

**Comment by stjohnjohnson** [comment]
I like this @catto. How do we want to detect which scm_url works for which scm module?

**Comment by catto** [comment]
@stjohnjohnson How about this Façade-like design?
* Implement and expose a function such as `canHandle` which can determine if it can handle the specified scm_url or hostname, in each scm module. Or, implement a detector directly into `scm-base`.
  * Every functions in `scm-base` has scmUri, checkoutUrl or hostname param, so we can switch the module using hostname.
* `scm-base` consumes scm config array from around [here](https://github.com/screwdriver-cd/screwdriver/blob/10fbdf48a8e6a1763b78546684ad8de4017b32e4/bin/server#L42-L47), and instanciate modules using the config.
* Each function in scm-base get the desired module by calling `canHandle` in each module or the detector, and calls the concrete function in it.

**Comment by catto** [comment]
I talked with @stjohnjohnson about this, and we decided to implement it.
Please let me know if you have any concerns.

### Rules
* Cluster admins can specify two or more scm modules at the same time
* Users can login to specified scm
* Pipelines and users should be discriminable by a scm context
* User can handle their pipeline if scmContext matches


### First pass
Change scm modules, api and ui to support multiple scm config and module at the same time.
We would support both current `scm` and new `scms` config. Use "default" context for backward compatibility if a name for `scm` config is not set.
User can see only the first scm via UI at this time and can use Screwdriver as they have so far.

The new `scms` config format is as below:
```yaml
scms:
    - name: my-git
      plugin: github
      config: 
        oauthClientId: foo
        oauthClientSecret: bar
        ...
    - name: super-gitlab
      plugin: gitlab
      config:
        ...
```

Changes:
- [ ] data-schema
- [ ] models
- [ ] scm modules (create scm-router like executor-router?)
- [ ] api
- [ ] ui


### Second pass
Change UI to provide multiple scm environment to users. This might include an adjustment of the 
UI design.
Such as
* Show username with scmContext in the header
    * e.g. `my-git:catto`, `github:catto`
* Show multiple login buttons for each scm
* Show scmContext for each search result of pipelines
    * e.g. `my-git:catto/models`, `github:screwdriver-cd/models`

**Comment by nkatzman** [comment]
Would love to have this feature 👍  👍

**Comment by s-yoshika** [comment]
## Details for first pass
We dug the details for the first pass.

### data-schema and model
We add `scmContext` for the schema of user and pipeline.
`scmContext` represents the scm which user or pipeline are belonging.

### scm modules
We create `scm-router` (like executor-router) which deregates the scm modules and selects appropriate module in every builds.
To select correct scm-module, `scm-router` call `canHandleUrl` function in each scm module.
`canHandleUrl` can determine if the scm module can handle the specified scm_url or hostname by itself.

And also every scm modules should return the itself context name.
The context name represents the hostname of the server which the scm service is hosted.
Because of  this, scm modules should also have `getContextName` function.

Summary:
* Create new scm-module: scm-router
* Add `canHandleUrl` and `getContextName` funcitons to all scm modules

### API

##### authorization
The users want to select scm context when they log-in. To do this, we have to change the API path of login.

Before: `/auth/login/{web?}`
After: `/auth/login/{scmContext?}/{web?}`

{scmContext} parameter specifies the scm by which user want to log-in.

##### handling models
The user and pipeline models will have `scmContext` as new field, so API should handle the models correctly.

##### settings
Also cluster settings will change. To support multiple SCMs, we add new setting `scms` like bellow.
```
scms:
    - displayName: my-git
      plugin: github
      config: 
        oauthClientId: foo
        oauthClientSecret: bar
        ...
    - displayName: super-gitlab
      plugin: gitlab
      config:
        ...
```
`scms` is array of `scm` settings, and each setting must have `displayName`.
`displayName` is like the nickname for the scm and is displayed as username(e.g. `my-git:catto`) and pipeline name(e.g. `my-git:catto/models`) in UI.

We'll update this if something is changed.
Please let me know if there is anything to worry about.

**Comment by s-yoshika** [comment]
This is breaking change, because the existing users have no `scmContext`, but the new users from this upgrade have `scmContext`.
It is difficult to ensure the compatibility between both users, so we need to migrate the database appropriately.
Currently, `datastor-sequelize` seems not to add a new column to existing tables automatically (https://github.com/screwdriver-cd/screwdriver/issues/633) .
Due to this, we have to `scmContext` column `users` table, and `pipelines` table manually.

ALTER TABLE `users` ADD COLUMN `scmContext` VARCHAR(128) NOT NULL DEFAULT “<the scm hostname>”;
ALTER TABLE `pipelines` ADD COLUMN `scmContext` VARCHAR(128) NOT NULL DEFAULT “<the scm hostname>”;

If `DEFAULT` attribute is set to column, the existing rows are also set with the default value.

**Comment by s-yoshika** [comment]
# SUMMARY 7/12/17

### API
Users want to select a scm to log-in, so the API such as `/auth/contexts` should return the list of `scmContext` and `displayName`.
The response schema of this API:
```
[
  {"context1" : "displayName1" },
  {"context2" : "displayName2" },
   ...
]
```

### scm modules
On the other hands, `scm-router` handles multiple scm modules internally and each scm module handles single scm. All modules inherit from `scm-base`, so it is better to use the same function signature.
Because of these, we have decided to change the function name from `getScmContext` to `getScmContexts` and implement it in form of "() => [strings]".
`router.getScmContexts` may return ["githubContext", bitbucketContext"] and github.getScmContext may return ["githubContext"]

The payload in webhook is different for each scm. We'll add `canHandleWebhook ((headers, payload) => boolean) ` function to each scm module so that scm-router can determine which scm module to use.

### settings
We move each `displayName` settings into `scms[].config`. so latest scms setting is like bellow.
```
scms:
    - plugin: github
      config: 
        displayName: github.com
    - plugin: github
      config:
        displayName: super-github
```
