### ISSUE TITLE
Automatic Changelogs

### ISSUE THREAD

**Issue by d2lam** [screwdriver-cd/screwdriver#373]
Acceptance criteria: we will no longer have to manually modify `CHANGELOG.md`. Breaking changes will be automatically detected and change log will be generated. 

Example: https://github.com/semantic-release/semantic-release

## SUMMARY

1. Add to package.json
```json
"scripts": {
    "semantic-release": "semantic-release pre && npm publish && semantic-release post"
  },
 "release": {
    "debug": false,
    "verifyConditions": {
      "path": "./node_modules/semantic-release/src/lib/plugin-noop.js"
    }
  },
  "devDependencies": {
    "semantic-release": "^6.3.2"
  }
```

2. In screwdriver.yaml, add 
```yaml
    publish:
        steps:
            - install: npm install
            - semantic-release: npm run semantic-release
        secrets:
            - GH_TOKEN
            - NPM_TOKEN
```

3. Add `GH_TOKEN`(github token) & `NPM_TOKEN` as secrets for the pipeline.

4. Commit your changes with the following format

- For patches: add `fix:` in front of commit message
- For minors: add `feat:` in front of commit message
- For majors: add `perf: BREAKING CHANGE:` in front of commit message. Note that package.json is not updated automatically, so we should change it manually in the PR
- **Note**: Adding `BREAKING CHANGE: ` after any tag mentioned above will cause a major version bump, e.g. `feat: add new stuff BREAKING CHANGE: break the world`

5. Your package will be bumped version automatically, published to npm and also github with the CHANGELOG.

## Example: 
- Pipeline using semantic-release: https://cd.screwdriver.cd/pipelines/2707e7cc74064f00937b0fad66568184ea4914ed
- Example PR to make pipeline use semantic-release:
https://github.com/screwdriver-cd/scm-bitbucket/pull/27/files
