### ISSUE TITLE
Email Notifications

### ISSUE THREAD

**Issue by d2lam** [screwdriver-cd/screwdriver#465]
> Users want to be able to be notified when their builds finish.

By default, only send when build fails
If status is specified, notifies based on the status. 

This should be configured per pipeline:
```yaml
shared:
   settings:
         email: foo@yahoo.com
```

Or per job:
```yaml
jobs: 
   component:
      settings:
             email: bar@yahoo.com
      steps: 
          ....
```

Email could be a string for simple configuration
```yaml
   email: bar@yahoo.com
```

or an object for more complicated configuration
```yaml
   email:
        addresses: 
              - foo@yahoo.com
              - bar@yahoo.com
        statuses:
              - success
              - failure
```

**Work:**
- [x] Data schema: accept `settings`: https://github.com/screwdriver-cd/data-schema/pull/107
- [x] Config-parser: to parse the new `settings` field inside `screwdriver.yaml`: https://github.com/screwdriver-cd/config-parser/pull/29
- [x] API: emits event when a build status updated
- [x] Notification Plugin: listens to the notify event, and sends email
- [x] Add documentation to the guide
- [x] Blog post
