### ISSUE TITLE
Bookends need aliases

### ISSUE THREAD

**Issue by stjohnjohnson** [screwdriver-cd/screwdriver#467]
Right now the bookend step names are very verbose.  Example:
![screen shot 2017-02-27 at 9 58 48 am](https://cloud.githubusercontent.com/assets/622065/23373164/8fbb9df4-fcd3-11e6-9b04-48caf4fad6eb.png)

It would be nice if we could rename them, something like:
```yaml
bookends:
    teardown:
        - screwdriver-artifact-bookend: artifacts
```
![screen shot 2017-02-27 at 9 59 03 am](https://cloud.githubusercontent.com/assets/622065/23373165/8fbc6086-fcd3-11e6-8ac6-217026665df5.png)
