### ISSUE TITLE
Job Templates

### ISSUE THREAD

**Issue by d2lam** [screwdriver-cd/screwdriver#470]
> As a template owner, I want to be able to publish a template for other people to use. 

Example `screwdriver-template.yaml`:
```yaml
name: test
version: 1.3
description: template for testing
maintainer: foo@bar.com
config:
  image: node:6
  steps:
    - install: npm install 
    - test: npm test
    - echo: echo $FOO
  environment:
    FOO: bar
  secrets:
     - NPM_TOKEN
```

To publish a template, I can edit the `screwdriver-template.yaml`, and run the pipeline to publish a new version.

Publishing a new version should do these steps:
- Validate the template
- Check if permission is good
- Publish the template

> As a user, I want to be able to reuse existing configuration for a job. 

In user's `screwdriver.yaml`:
```yaml
jobs:
   main:
      template: test@1.3
```

Would be translated to:
```yaml
jobs:
   main: 
        image: node:6
        steps:
          - install: npm install 
          - test: npm test
          - echo: echo $FOO
        environment:
           FOO: bar
        secrets:
          - NPM_TOKEN
```

# Implementation Details
## First pass: MVP

*Work to be done:*
### Template owner
- [x] Validate expected fields in a `screwdriver-template.yaml`
    - We have added validation into the data-schema repo for the required fields in a template.yaml
    - We have created a module for validating templates that will use the changes made in the data-schema
   - [x] Data schema (https://github.com/screwdriver-cd/data-schema/pull/109)
   - [x] Template validation module (https://github.com/screwdriver-cd/template-validator/pull/3)
   - [x] API new endpoint to validate template (screwdriver-cd/screwdriver#480)
- [x] Publish template (PR open, https://github.com/screwdriver-cd/template-main/pull/2)
- [x] Store template metadata in RDS
      2 new endpoints, GET and POST for getting and creating templates: name, version, description, maintainer, config, label, scmURI
    - `label` is an array. It could be anything like `['test', 'stable', 'v123']`
    - scmURI is there so that we could check if the correct pipeline is publishing the template
    - [x] Data-schema
    - [x] Models (https://github.com/screwdriver-cd/models/pull/149)
    - [x] API (https://github.com/screwdriver-cd/screwdriver/pull/475)

### Template user
- [x] Validate template syntax in a `screwdriver.yaml`
- [x] Merge into jobs

### Others
- [x] Cucumber feature file

## Second pass:

*Need more ideas/ architecture designs*
- Wrapping around the steps inside template. For example: pretest, posttest. 
Inside template:
```yaml
   steps: 
       test: echo test
       publish: echo publish
```

Inside user's screwdriver.yaml:
```yaml
main:
   template: mytemplate@1
   steps: 
       pretest: echo hello
       posttest: echo goodbye
```

Translate into: 
```yaml
   steps:
       pretest: echo hello
       test: echo test
       posttest: echo goodbye
       publish: echo publish
```

- Override step:
```yaml
main:
   template: mytemplate@1
   steps: 
       publish: echo not publishing
```

Translate into:
```yaml
   steps:
       pretest: echo hello
       test: echo test
       posttest: echo goodbye
       publish: echo not publishing
```

- Namespacing. What should the name of templates be? `org/template` or `userid/template` or something else? 
- Lifespan for version
- Users (admin) can make API call
- Optimizing labels, versioning; labels vs tags
- Multiple templates per repo?
- Shared templates?
- [ ] Documentation in guide
- [ ] Blog post

**Comment by stjohnjohnson** [comment]
We need to document the pipeline, the permission model, and how we are handling versions.

**Comment by d2lam** [comment]
@stjohnjohnson I want to discuss with @petey about the lifespan for version. What are the pros and cons and if we'd like to implement it, how we should design that. 

For your 2nd point, do you mean if the **template** was removed, what happens to the jobs using it? 

The automatically generate PRs is nice, but maybe we can put it in Gold Bar.

**Comment by FenrirUnbound** [comment]
The idea of version lifespans was to add support limitations to template versions. A support model that other projects use is to define a set of dates where a particular version is considered supported/in maintenance/unsupported. [NodeJS](https://github.com/nodejs/LTS) is a good example of what projects follow this model.

The alternative suggestion was to give a published version a kind of TTL: a particular version is officially supported for 6 months (or some other arbitrary length of time) when it's published. After that time has elapsed, the template owners are no longer are obligated to support that version and users should expect a limited level of support. This helps limit what a template owner needs to support and gives users an incentive to keep up with the template updates.

The idea behind the alternative suggestion can be taken from how NodeJS modules are treated.  The [vogels](https://github.com/ryanfitz/vogels) module hasn't been updated in over a year and is most likely abandoned or not implementing new features. As a user, it's not clear whether to expect any kind of support from the maintainer. With the alternative lifespan idea, there's a defined deadline behind whether a particular template is considered supported.

I would consider it a nice-to-have, and not a hard requirement for this feature.

**Comment by d2lam** [comment]
**For building and publishing templates:**
Here are some ideas @minz1027  and I came up with:

We will have 2 templates that people can use:
**template/main:**
```yaml
  steps:
    - validate: call validation with screwdriver-template.yaml
    - build: echo user-override-this-step
    - test: echo user-override-this-step
```
**template/publish:**
```yaml
  steps:
    - publish-to-test: store all the metadata and screwdriver-template.yaml to `test` branch
    - functional-test: echo user-can-pull-the-test-template-to-functionally-test
    - publish-to-stable: change `test` to `stable`
```

When template owner wants to build and publish their templates, in their screwdriver.yaml they can have:

```yaml
jobs: 
    main:
        template: template/main
    publish: 
        template: template/publish
```

**Comment by stjohnjohnson** [comment]
Couple points of feedback:
 - Version number should be required (major version)
 - What are suggested images?
 - The config should mirror the possible contents of a `job`, it would be good to split it out as well:

```yaml
name: test
version: 1.3
description: template for testing
maintainer: foo@bar.com
config:
  image: node:6
  steps:
    - install: npm install 
    - test: npm test
    - echo: echo $FOO
  environment:
    FOO: bar
  secrets:
     - NPM_TOKEN
```

**Comment by minz1027** [comment]
@stjohnjohnson 
`My question about permissions is, project 1234 built test/foo template. I delete project 1234 and make project 1235. How can 1235 update the test/foo template?`

We store the `scmUri` together with template in the RDS. 1235 should still be able to update the template since the `scmUri` will be the same for 1235 as long as the repository stays the same.

**Comment by d2lam** [comment]
@stjohnjohnson  
You want to include the `branch` in the template.yaml? We were thinking in `publish-to-test`: would store all the metadata and screwdriver-template.yaml to `test` branch. And `publish-to-stable` would basically change that flag to `stable`

**Comment by stjohnjohnson** [comment]
@minz1027 What if you change repos?

@d2lam I wouldn't store the branch in there.

**Comment by d2lam** [comment]
@stjohnjohnson  You mean you wouldn't store the branch info in RDS? Wouldn't RDS be faster/easier to retrieve?
Where should we store it?

**Comment by minz1027** [comment]
@stjohnjohnson if the owner moves or deletes the repo, he will need to create a new template. If the template is not tied to the repo, then what we should tie it to for permission control?

**Comment by catto** [comment]
What about adding `kind: build` field to the template schema? Other kind of template such as "pipeline template" might be added in the future.

**Comment by stjohnjohnson** [comment]
@d2lam my reply was in reference to your question. I wouldn't store branch in the template.yaml, but yes store it in RDS.
@minz1027 Permission control is fine for pipeline ID, but there should be a way for admins to change permission. AtheNZ would be useful here.
@catto Good idea.  We could even have `build` `publish` `deploy` types if we wanted to.  Then it would be interesting to chain them together.  Something like:

```yaml
jobs:
  main:
    template:
      - node/build@1
      - packer/build@1
      - aws/publish@1
      - aws/deploy-ec2@1
```

Obviously, that's a bad yaml, but it's an interesting concept (maybe tackle it later).

**Comment by d2lam** [comment]
@stjohnjohnson Yes, that is what we were trying to say. Store the branch in RDS. :)

**Comment by petey** [comment]
We need to store the json representation of the template configuration in RDS, not a pointer to the yaml.

In addition to a version number (semver), templates need to support one or more labels. We do not want to enforce any specific branch or maturity strategy [test, stable], as that will cause issues down the line. Labels should be user configured. When we do lookups against a label, we find the highest version of the requested template with the given label. Labels should be assigned by api call, not a part of the yaml config.

Having multiple templates active for one job is going to cause us headaches unless we document really well how things are merged. The biggest issue will be around merging steps, especially when two templates contain steps with the same name.

A version lifetime is a good idea, but needs to be user configurable, and needs to be able to be reset. We shouldn't remove data after the version lifetime is exceeded, just display a big warning about them running unsupported code. We probably want to make a default lifetime to warn users when the `@latest` version of a template hasn't been updated in a long time.

We should really consider the ability to publish more than one template from a repo, and possibly multiple templates in one build. This would drastically reduce support overhead for people maintaining all templates for a platform.

We need to be really careful about how templates are named/name spaced as we can get into areas where people could squat on template names, or name templates something overly generic causing confusion.

**Comment by d2lam** [comment]
I've edited the original issue to address some of the comments made here. Please read the original issue.

**Comment by d2lam** [comment]
**SUMMARY 3/3/17** 
- Template validator (https://github.com/screwdriver-cd/template-validator) is published. We need to have new API end points that call this. This new endpoint would be called before building the template. 
- Storing the RDS is still in progress. The data-schema PR is merged. We continued working on the models and API today. The PRs are ready to be reviewed.

**Comment by d2lam** [comment]
## **SUMMARY 3/6/17**

### Storing template in RDS
- Model PR gets merged. 
- API: there were a couple issues but it's working now. Using this command inside the build:  
```
'curl -H "Authorization: Bearer $SD_TOKEN" -H "Content-Type: application/json" -d "{\"name\": \"screwdriver/publish\",\"version\": \"1.0.0\",\"labels\": [\"test\"],\"description\": \"this is a template\",\"maintainer\": \"foo@bar.com\",\"config\": {\"steps\": [{\"echo\": \"echo hello\"}]}}" -X POST http://192.168.1.101:9001/v4/templates'
```

Tested these scenarios locally and it worked:
1. Template does not exist: create a new entry
2. Template with same name, new version: create a new entry
3. Template with same name, same version: update the labels
4. Bad permission: will return 401.

**Comment by d2lam** [comment]
## **SUMMARY 3/7/17**
### Template validator

### Storing template in RDS
- API: Addressed a couple comments. Still in PR: https://github.com/screwdriver-cd/screwdriver/pull/475

### Using template
- Data-schema: allow template field: https://github.com/screwdriver-cd/data-schema/pull/113
- Retrieving template: discussed high level with @petey and @minz1027. Will have this done inside the config-parser and possibly pass in `templateFactory`, so it can do lookup of templates

**Comment by d2lam** [comment]
## **SUMMARY 3/8/17**
### Template validator
- [ ] API: **in PR** https://github.com/screwdriver-cd/screwdriver/pull/480

### Storing template in RDS
- [ ] API: **in PR** https://github.com/screwdriver-cd/screwdriver/pull/475

### Using templates
- [ ] Data schema: **MERGED** https://github.com/screwdriver-cd/data-schema/pull/113
- [ ] Config-parser: Merge template into jobs. **[WIP]** https://github.com/screwdriver-cd/config-parser/compare/flattenTemplates?expand=1
- [ ] API: Get templates by name and version

**Comment by d2lam** [comment]
## **SUMMARY 3/8/17**
### Template validator
- API: **MERGED** https://github.com/screwdriver-cd/screwdriver/pull/480
- Functional Test: **WIP** https://github.com/screwdriver-cd/screwdriver/pull/490

### Storing template in RDS
- API: **in PR** https://github.com/screwdriver-cd/screwdriver/pull/475

### Using templates
- Data schema: **MERGED** https://github.com/screwdriver-cd/data-schema/pull/113
- Config-parser:  **in PR** https://github.com/screwdriver-cd/config-parser/pull/32/files
- **TODO** API: Get templates by name and version

**Comment by d2lam** [comment]
## **SUMMARY 3/10/17**
### Template validator
- Functional Test: **in PR** https://github.com/screwdriver-cd/screwdriver/pull/490

### Storing template in RDS
- API: **in PR** https://github.com/screwdriver-cd/screwdriver/pull/475
Need to discuss further about `labels` and versioning.

### Template to publish templates
- TODO

### Using templates
- Config-parser:  **in PR** https://github.com/screwdriver-cd/config-parser/pull/32
Made a couple changes to the PR. We no longer pass in API URL, but the templateFactory directly to do the look up of templates.

**Comment by jerryzhang222** [comment]
## **SUMMARY 3/13/17**
### Getting template using models

- Added `getTemplate` within `templateFactory` in the `models` repo to get the most recent template version that matches a template name and label. Uses npm package: [compare-versions](https://www.npmjs.com/package/compare-versions)

**Comment by tkyi** [comment]
## **SUMMARY 3/15/17**
No work is being done on job templates at the moment besides any open PRs.

**Comment by d2lam** [comment]
Posting templates and merging template to user job config is working:
Template:
```
{
id: 7,
labels: ["test"],
config: {
  steps: [
    { echo: "echo Hello" },
    { stuff: "echo I am using the new template test!!!!" }
  ]},
name: "screwdriver/testtemplate",
version: "1.0.4",
description: "this is a template to test templates",
maintainer: "daolam112@gmail.com",
scmUri: "github.com:82863190:master"
},
```
screwdriver.yaml:
```
shared:
    image: node:6
jobs:
    main:
        template: screwdriver/testtemplate@1-test
```

<img width="658" alt="screen shot 2017-03-21 at 4 17 06 pm" src="https://cloud.githubusercontent.com/assets/3401924/24175158/e4b23338-0e51-11e7-89a3-afc4e69d622b.png">
