### ISSUE TITLE
Progressive Display or Prompt breaks UI

### ISSUE THREAD

**Issue by stjohnjohnson** [screwdriver-cd/screwdriver#488]
# Problem
During a build, if the script is prompted for input, then nothing shows up in the UI.  This causes much confusion as to why it's stuck.

# Code to Reproduce

```yaml
jobs:
  main:
    image: node:6
    steps:
      - test: ssh git@github.com hostname
```

# Expected Output
```
ssh git@github.com hostname
The authenticity of host 'github.com (192.30.253.112)' can't be established.
RSA key fingerprint is 16:27:ac:a5:76:28:2d:36:63:1b:56:4d:eb:df:a6:48.
Are you sure you want to continue connecting (yes/no)?
```

# Current Output
![screen shot 2017-03-07 at 11 50 21 am](https://cloud.githubusercontent.com/assets/622065/23674878/43305cf4-032c-11e7-990f-035f0486521e.png)

# Notes

This is also the case for progressive display (like a progress bar).
