### ISSUE TITLE
Support Escaped Parameters for Steps

### ISSUE THREAD

**Issue by stjohnjohnson** [screwdriver-cd/screwdriver#498]
Right now we can provide steps like:
```yaml
shared:
  steps:
    - foo: make foo bar
```

But I may need some escaping to happen:
```yaml
shared:
  steps:
    - foo:
      - make
      - foo
      - bar
```

Same way that Docker provides either string or array for command execution.  https://docs.docker.com/engine/reference/builder/#cmd
