### ISSUE TITLE
Don't require main to be defined

### ISSUE THREAD

**Issue by jer** [screwdriver-cd/screwdriver#513]
It would be convenient, and possibly less confusing, if we didn't have to define a main job. Perhaps the solution is just to make people put main into workflow as a standard job. This would make the pipeline much more explicit for use cases like this:

```yaml
workflow:
  - staging
  - prod

shared:
  image: jer/mycustomkubectl:latest
  steps:
  - setup-k8s: source ci/setup_k8s.sh
  - deploy: kubectl apply -l env=$SD_JOB -f myapp
```
