### ISSUE TITLE
Settings should be namespaced

### ISSUE THREAD

**Issue by stjohnjohnson** [screwdriver-cd/screwdriver#534]
Right now we have settings like:

```yaml
shared:
  settings:
    email: foo@example.com
```

But this is actually referring to a notify plugin.  Should we be namespacing them?

```yaml
shared:
  settings:
    notify/email: foo@example.com
```

This allows us to specify configuration for bookends (build plugins?), notify plugins, workflow plugins, screwdriver feature flags, and more.

```yaml
shared:
  settings:
    notify/email: foo@example.com
    screwdriver/analytics:
      statsd: statsd.example.com
    screwdriver/debug:
      level: verbose
    executor/resource: 
      - XCODE8
      - OSX-SIERRA
    workflow/cron: 45 23 * * 6
    bookend/scm:
      target_dir: /go/src/github.com/screwdriver-cd/launcher
```
