### ISSUE TITLE
Please make it easier to use YAML anchors for de-duplication

### ISSUE THREAD

**Issue by jer** [screwdriver-cd/screwdriver#552]
I would really love to be able to do this:

```yaml
workflow:
  - stg
  - prod1
  - prod2

anchors:
  deploy: &deployanchor
  - setup-k8s: source ci/setup_k8s.sh $CLUSTER
  - deploy-operator: kubectl apply -f prometheus-operator
  - deploy-state-metrics: kubectl apply -f kube-state-metrics
  - deploy-node-exporter: kubectl apply -f node-exporter
  - deploy-prometheus-k8s: kubectl apply -f prometheus
  - deploy-alertmanager-main: kubectl apply -f alertmanager
  - deploy-grafana-main: |
      sed -i.bak "s/%CLUSTER%/$CLUSTER/g" grafana/ingress.yaml && \
      kubectl apply -f grafana

shared:
  image: jer/kubectl:latest

jobs:
  stg:
    steps: *deployanchor
    environment:
      CLUSTER: my.stg.cluster

  prod1:
    steps: *deployanchor
    environment:
      CLUSTER: my.prod1.cluster

  prod2:
    steps: *deployanchor
    environment:
      CLUSTER: my.prod2.cluster

```

The & and * stuff are YAML anchors, which work really well. The problem is that the validator barfs on the anchors section above. It would be convenient for this workflow to have some top-level field that isn't validated by the validator, or perhaps one purposely there for using anchors.

**Comment by stjohnjohnson** [comment]
I really like this idea.  I'm glad it already works, but you're right it needs to be cleaner.

I don't want to tie to the YAML implementation, maybe we could support a top-level field called `annotations` which can have any key/value combination.

**Comment by tkyi** [comment]
@jer This functionality is available now with the addition of the `annotations` feature. You can define key/value pairs under there and the validator does not complain.

screwdriver.yaml:
```
workflow:
  - prod1
  - prod2

annotations:
  anchors:
    deploy: &deployanchor
    - setup-k8s: source ci/setup_k8s.sh $CLUSTER
    - deploy-operator: kubectl apply -f prometheus-operator
    - deploy-state-metrics: kubectl apply -f kube-state-metrics
    - deploy-node-exporter: kubectl apply -f node-exporter
    - deploy-prometheus-k8s: kubectl apply -f prometheus
    - deploy-alertmanager-main: kubectl apply -f alertmanager
    - deploy-grafana-main: |
        sed -i.bak "s/%CLUSTER%/$CLUSTER/g" grafana/ingress.yaml && \
        kubectl apply -f grafana

shared:
  image: jer/kubectl:latest

jobs:
  main:
    steps: *deployanchor
    environment:
      CLUSTER: my.stg.cluster

  prod1:
    steps: *deployanchor
    environment:
      CLUSTER: my.prod1.cluster

  prod2:
    steps: *deployanchor
    environment:
      CLUSTER: my.prod2.cluster
```

Validator results (truncated):
<img width="679" alt="screen shot 2017-09-28 at 3 30 54 pm" src="https://user-images.githubusercontent.com/3230529/30993106-24e257ac-a462-11e7-9d3d-f60e13060e75.png">
