### ISSUE TITLE
Labels for pipelines

### ISSUE THREAD

**Issue by stjohnjohnson** [screwdriver-cd/screwdriver#571]
Stealing directly from [kubernetes](https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/), we should have support for labels in the screwdriver.yaml.

Something like:
```yaml
workflow:
 - main

labels:
 language: node.js
 my-team-name/system: frontend
```

That way we can build dashboards that are simply label selectors like:
`language=node.js NOT pipeline=14823`
