### ISSUE TITLE
Support Annotations for Feature Configuration

### ISSUE THREAD

**Issue by stjohnjohnson** [screwdriver-cd/screwdriver#580]
If we supported a mutli-level annotation feature like [k8s](https://kubernetes.io/docs/reference/labels-annotations-taints/), then we could use that to configure feature flags.  Example:

```yaml
workflow:
 - main
 - prod

# Pipeline level
annotations:
  beta.screwdriver.cd/auto_pr_builds: fork-only

shared:
  # Jobs-level
  annotations:
    screwdriver.cd/notify.email: foo@example.com

jobs:
  prod:
    # Job level
    annotations:
      screwdriver.cd/executor.resource:
        - XCODE8
        - OSX-SIERRA
```

This is kinda related to https://github.com/screwdriver-cd/screwdriver/issues/534 and https://github.com/screwdriver-cd/screwdriver/issues/552
