### ISSUE TITLE
SSO Error "unable to verify the first certificate"

### ISSUE THREAD

**Issue by fukusukei** [screwdriver-cd/screwdriver#592]
Hello.

I tried to Login to local hosted Screwdriver using the GHE(GitHub Enterprise) account.
at the first, I pressed "Login with SCMP Provider", I could access GitHub Authorize application page.
But, when I pressed "Authorize application" button, Another Web browser window opens and the following error message was displayed.

```
statusCode	401
error	"Unauthorized"
message	"Authentication failed due to: Client request error: unable to verify the first certificate"
````

I think that the cause of this problem is that GHE uses SSL certificate of "SHA - 1 + self - signed"*1.
Would you tell me the necessary setting or where the logs are useful for analysis.

*1 This cannot be changed because the company's designated certificate.

Supplement:
Screwdriver is started with following docker-compose file.

--------------------docker-compose.yaml------------------
```
version: '2'
services:
    api:
        image: screwdrivercd/screwdriver:stable
        ports:
            - 8001:80
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:rw
            - ./data/:/tmp/sd-data/:rw
        environment:
            PORT: 80
            URI: http://*******************************:8001
            ECOSYSTEM_UI: http://*******************************:8000
            ECOSYSTEM_STORE: http://*******************************:8002
            SCM_PLUGIN: github
            DATASTORE_PLUGIN: sequelize
            DATASTORE_SEQUELIZE_DIALECT: sqlite
            DATASTORE_SEQUELIZE_STORAGE: /tmp/sd-data/storage.db
            EXECUTOR_PLUGIN: docker
            SECRET_WHITELIST: "[]"
            EXECUTOR_DOCKER_DOCKER: |
                {
                    "socketPath": "/var/run/docker.sock"
                }
            SCM_GITHUB_GHE_HOST: *********************************
            SECRET_OAUTH_CLIENT_ID: *********************************
            SECRET_OAUTH_CLIENT_SECRET: *********************************
    ui:
        image: screwdrivercd/ui:stable
        ports:
            - 8000:80
        environment:
            ECOSYSTEM_API: http://*******************************:8001
            ECOSYSTEM_STORE: http://*******************************:8002

    store:
        image: screwdrivercd/store:stable
        ports:
            - 8002:80
        environment:
            ECOSYSTEM_UI: http://*******************************:8000
            URI: http://*******************************:8002
```
