### ISSUE TITLE
Kubernetes Pod template for supporting VMs

### ISSUE THREAD

**Issue by FenrirUnbound** [screwdriver-cd/screwdriver#597]
For supporting the effort in having VMs available to builds in Kubernetes, we need to re-visit our Pod template structure. The current pod template for `executor-k8s` can be [found here](https://github.com/screwdriver-cd/executor-k8s/blob/master/config/pod.yaml.tim). 

For VMs, we plan on using [Hypercontainer](https://hypercontainer.io/) for allocating VMs in a Kubernetes cluster.

Based on the current PoC, this is what the template would look similar to:

```
spec:
  privileged: true
  container:
    command: hyperctl -a --rm --name build123 <other arguments> -p pod.yaml
  resources:
    - 10GB
    # 2CPUs in micro-CPU
    - 2000m  
```

Hyperctl references a `pod.yaml` for defining what is running within the VM environment. Based on what we have today, this is a draft of what it may look like:

```
spec:
  containers:
    - name: build
      image: <user_defined_container>
      command: <launcher command>
    - name: docker
      command: dockerd -Htcp://<host_ip>:<port>
    # might not need this one
    - name: logservice
      image: ...
      command: ...
```

## Reference

* [K8s pod templates](https://kubernetes.io/docs/concepts/workloads/pods/pod-overview/#pod-templates)
* [Hypercontainer](https://hypercontainer.io/)
   * [Hyperctl run command](https://docs.hypercontainer.io/reference/run.html)
   * [Hyperctl pod spec](https://docs.hypercontainer.io/reference/podfile.html)
* Switching Log Service implementation -- #598
