### ISSUE TITLE
Templates - Second Pass

### ISSUE THREAD

**Issue by petey** [screwdriver-cd/screwdriver#616]
*Background* See https://github.com/screwdriver-cd/screwdriver/issues/470

- [x] Wrapping around the steps inside template. For example: pretest, posttest. (https://github.com/screwdriver-cd/config-parser/pull/39)
Inside template:
```yaml
   steps: 
       - test: echo test
       - publish: echo publish
```

Inside user's screwdriver.yaml:
```yaml
main:
   template: mytemplate@1
   steps: 
       - pretest: echo hello
       - posttest: echo goodbye
```

Translates into: 
```yaml
   steps:
       - pretest: echo hello
       - test: echo test
       - posttest: echo goodbye
       - publish: echo publish
```

- [x] Override step: (https://github.com/screwdriver-cd/config-parser/pull/40)
```yaml
main:
   template: mytemplate@1
   steps: 
       - publish: echo not publishing
```

Translate into:
```yaml
   steps:
       - test: echo test
       - publish: echo not publishing
```

- [x] [Version tags](https://github.com/screwdriver-cd/screwdriver/issues/616#issuecomment-314568245) (__WIP__): crud api for tagging template versions, e.g. npm's `dist_tags` allow fetch on template version by tag. `mytemplate@latest` (https://github.com/screwdriver-cd/data-schema/pull/157, https://github.com/screwdriver-cd/data-schema/pull/158, https://github.com/screwdriver-cd/models/pull/179, https://github.com/screwdriver-cd/config-parser/pull/41, https://github.com/screwdriver-cd/screwdriver/pull/646, https://github.com/screwdriver-cd/screwdriver/pull/647)
- [ ] Restrict API calls for template writes to admins, and template owners
- [ ] Version Lifespan: After a set period of time [configurable: default 6 months], a given version of a template should display a warning message in the build that the template is no longer being updated/maintained. (https://github.com/screwdriver-cd/screwdriver/issues/1490)
- [x] [Template namespaces](https://github.com/screwdriver-cd/screwdriver/issues/926) (e.g.: chef/publish, screwdriver/checkout, etc) 
- [ ] Template keywords: Listed in annotations of template.yaml, e.g. `language:node.js`, `publishing`, `aws`. Primarily to allow discovery of templates by searching by keyword. Keywords should apply to all versions of a template.
- Documentation in guide:
   - [x] create, validate, and publish (https://github.com/screwdriver-cd/guide/pull/90)
   - [x] wrapping around steps (https://github.com/screwdriver-cd/guide/pull/95)
   - [x] overriding steps (https://github.com/screwdriver-cd/guide/pull/96)
   - [x] tagging (https://github.com/screwdriver-cd/template-main/pull/8, https://github.com/screwdriver-cd/template-main/pull/9, https://github.com/screwdriver-cd/template-main/pull/10, https://github.com/screwdriver-cd/guide/pull/105)
   - [ ] lifespan
   - [x] namespaces
   - [ ] keywords
- [ ] Blog post

Nice to have:
- [x] Publish multiple templates from one repo

### 2017-7-6
- Added PR link for wrapping steps

### 2017-7-10
- Added PR link for create, validate, and publish documentation
- Added documentation requirements for wrapping and overriding steps

### 2017-7-13
- Added PR links for data schema and models for tagging

### 2017-7-14
- Added PR link for tagging API, tags in config-parser

### 2017-7-24
- Added checkbox for template namespacing

### 2017-7-28
- Added links to template tagging module and documentation PRs

### 2018-3-19
- Added link to template namespace issue
