### ISSUE TITLE
EADDRNOTAVAIL

### ISSUE THREAD

**Issue by jarvan4dev** [screwdriver-cd/screwdriver#639]
env: centos7.3 screwdriver:master

I have override default configuration in a local.yaml file

```
httpd:
    # Port to listen on
    port: 8080
    # Host to listen on (set to localhost to only accept connections from this machine)
    host: 139.196.99.72
    # Externally routable URI (usually your load balancer or CNAME)
    uri: http://139.196.99.72:8080
    # SSL Support
    tls: false
        # If you want SSL, you can easily add it by replacing `tls: false` with an object that
        # provides the options required by `tls.createServer`
        # https://nodejs.org/api/tls.html#tls_tls_createserver_options_secureconnectionlistener
        # key: |
        #     PRIVATE KEY HERE
        # cert: |
        #     YOUR CERT HERE
```

when I execute `npm start` , an error occured

```
error:  Error: listen EADDRNOTAVAIL 139.196.99.72:8080
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at Server._listen2 (net.js:1245:19)
    at listen (net.js:1294:10)
    at net.js:1404:9
    at _combinedTickCallback (internal/process/next_tick.js:83:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

I can not understand it, what should I do next? I just would like to visit the screwdriver application from external network.
