### ISSUE TITLE
Add notification plugin for slack

### ISSUE THREAD

**Issue by petey** [screwdriver-cd/screwdriver#687]
Context
========
As a user,
I would like to get [slack] notifications when things happen in my pipeline(s),
so i can react when a pipeline fails, or deploys code successfully.

Objective
-----------
Add a notification plugin that can be configured by user annotations to send messages to a channel of their choice for certain pipeline events.

~Caveat: Screwdriver is a multi-tenant system, which means that a global configuration for slack, e.g. service tokens, may not be reasonable. This means that notifications plugins, e.g. slack, may need to take in secrets from an individual pipeline for the purposes of providing notifications to their service endpoints.~

- [ ] Spike: Notification Configuration and Security
    - [ ] Refactor notification plugins
- [ ] Slack plugin
    - [ ] Pipeline/Build start event
    - [x] Pipeline/Build finished event
    - [x] Configurable channel(s) for success/failure
    - [ ] Configurable access token [secrets]/server

Stretch:
- [ ] meta.notifications.slack entry to post additional info during event (e.g. test results)

**Comment by d2lam** [comment]
For reference: https://github.com/d2lam/notifications-slack

**Comment by minz1027** [comment]
## Summary 01/16

According to the meeting, we will go with global configuration for now. We will have a bot user and use its slack `token` to post message to slack channels. Users who want slack notification need to invite the bot to their channel first.

### Interface
in `screwdriver.yaml`
```
settings:
        slack: channel_A
```
```
settings:
        slack: [channel_A, channel_B]
```
```
settings:
        slack: 
            channels: 
               - channel_A
               - channel_B
           statuses:
               - SUCCESS
               - FAILURE
               - ABORTED
               - QUEUED
               - RUNNING
```

### TO DO:
- [ ] slack notification plugin - in progress
- [ ] add bot token to config in API and pass it to slack notification plugin
