### ISSUE TITLE
New workflow still requires a `main`?

### ISSUE THREAD

**Issue by petey** [screwdriver-cd/screwdriver#792]
**What happened**:
In the validator UI, using the following yaml:

```
jobs:
  testing:
    image: node:6
    steps:
        - greeting: echo hello
    requires:
        - ~commit
        - ~pr
```
The API returns a 500 error.

Changing the job name from `testing` to `main` resolves the issue.

**What you expected to happen**:
The validator UI/API displays my pipeline
