### ISSUE TITLE
Feature request: sorted jobs list

### ISSUE THREAD

**Issue by catto** [screwdriver-cd/screwdriver#799]
**What happened**:
Jobs listed in options tab are not sorted, so it is hard to find a job that I want to turn off if there are many jobs in a pipeline.

**What you expected to happen**:
Jobs listed in options tab are sorted alphabetically or triggered order.

**How to reproduce it**:
Put screwdriver.yaml like below to your repository and create a pipeline.
```yaml
jobs:
  A:
    template: docker/build
    requires: [~pr]
  B:
    template: docker/build
    requires: [A]
  C:
    template: docker/build
    requires: [B]
  D:
    template: docker/build
    requires: [C]
  E:
    template: docker/build
    requires: [D]
  F:
    template: docker/build
    requires: [E]
    
  main:
...
```
![image](https://user-images.githubusercontent.com/1608595/32880520-50100306-caf1-11e7-82c2-c52504f4f9ba.png)
