### ISSUE TITLE
Build fails if calls meta get before meta set

### ISSUE THREAD

**Issue by d2lam** [screwdriver-cd/screwdriver#808]
**What happened**:
- If we call `meta get doesnotexist` before `meta set hello bye`, the step will fail with error `meta.json: no such file or directory` . 
- However, if we swap the order, the step will pass and return `null`

This is because `setupDir` is inside `meta set`: https://github.com/screwdriver-cd/meta-cli/blob/master/meta.go#L160. So if we call `meta get` first, the file does not exist. 

<img width="1425" alt="screen shot 2017-11-29 at 5 02 08 pm" src="https://user-images.githubusercontent.com/3401924/33407633-1f484efa-d527-11e7-8799-1bcf1558ca12.png">

<img width="1394" alt="screen shot 2017-11-29 at 5 01 58 pm" src="https://user-images.githubusercontent.com/3401924/33407637-23aa5704-d527-11e7-9183-271e29fe488d.png">

**What you expected to happen**:
It should return `null` in both cases. The order of steps should not affect the build results. 

**How to reproduce it**:
```
shared:
  image: node:6
jobs:
  main:
    steps:
      - metaget2: meta get doesnotexist
      - metaset: meta set hello bye
   requires:
      - ~commit
```
