### ISSUE TITLE
Cannot use "shared.steps" and "jobs.individual_job.steps" at the same time 

### ISSUE THREAD

**Issue by tk3fftk** [screwdriver-cd/screwdriver#857]
**What happened**:
When we use two templates which have common steps `verify`. Then we want to overwrite `verify` step in test job and publish job. We also want to wrap publish step by adding `prepublish` step. The `verify` step of `test` job is overwrote but the `verify` step of `publish` job is not overwrote and `publish` job has `prepublish` step.

The example yaml is here:
```
shared:
  steps:
    - verify: echo "Nothing"
jobs:
  test:
    requires: [~pr]
    template: foo/test
  publish:
    requires: [~commit]
    template: foo/publish
    steps:
       - prepublish: echo "pre publish"
```

**What you expected to happen**:
`publish` job has `prepublish` step and overwritten `verify` step.

**How to reproduce it**:
Set shared.steps and jobs.individual_job.steps both in `screwdriver.yaml`.

I think shared steps object is overwrote (not merged) individual step object at [these lines](https://github.com/screwdriver-cd/config-parser/blob/d569e62fd3245d531b8fad0630364a4ee88fe163/lib/phase/flatten.js#L94-L98).
