### ISSUE TITLE
Send Slack notifications when a change in build status occurs

### ISSUE THREAD

**Issue by ScottyFillups** [screwdriver-cd/screwdriver#867]
# Context

Currently Screwdriver Slack notifications are sent whenever a build returns a status specified in the user's `screwdriver.yaml`:

```yaml
settings:
        slack: 
            channels: 
               - channel_A
               - channel_B
           statuses:
               - SUCCESS
               - FAILURE
               - ABORTED
               - QUEUED
               - RUNNING
```

It would be convenient if users could configure `screwdriver.yaml` to send a notification whenever a _change_ in build status occurs.

# Objective

Add a feature that allows users to get notifications based on a _change_ in build status by modifying `screwdriver.yaml`.

Suggestion: Users can pass a list of statuses; Screwdriver will keep track of the most recent occurrence of the statuses listed in `delta`. Each time the build updates its status, we check:

1. Whether the new status is different from the most recent occurrence
2. The new status is listed in `delta`

If both conditions are true, the user will get a notification. Example:

```yaml
settings:
        slack: 
            channels: 
               - channel_A
               - channel_B
           delta: 
               - SUCCESS
               - FAILURE
               - ABORTED
```

Consider the following status changes:

`RUNNING -> FAILURE -> RUNNING -> FAILURE -> RUNNING -> FAILURE -> RUNNING -> ABORTED -> RUNNING -> SUCCESS -> RUNNING -> SUCCESS`

The user would get notifications in this order: `FAILURE -> ABORTED -> SUCCESS`
