### ISSUE TITLE
config-parse-error for options in screwdriver.yaml

### ISSUE THREAD

**Issue by prakashgula** [screwdriver-cd/screwdriver#897]
**What happened**:
Installed screwdriver-box locally. Connected GitHub to local screwdriver via OAuth application.

options:
  jenkins:
    host: http://jenkins.local
    port: 8080
    username: jenkinsuser
    password: jenkinspassword
Steps:
config-parse-error: echo "ValidationError: "options" is not allowed"; exit 1

Got following error when tried to validate in "Validate Screwdriver Configuration" in screwdriver UI 

Steps:
config-parse-error: echo "ValidationError: "options" is not allowed"; exit 1

I am trying to add Jenkins options in screwdriver.yaml file as below. This needs to invoke our own Jenkins as we have some limitations right now to migrate to use executor-jenkins provided by screwdriver.

**What you expected to happen**:
Config parser has to allow to define options for Jenkins configurations

**How to reproduce it**:
Define options in screwdriver.yaml

**Comment by tkyi** [comment]
The validator is for user [screwdriver.yamls](https://github.com/screwdriver-cd/screwdriver/blob/master/screwdriver.yaml), not for the [cluster configuration yaml file](https://github.com/screwdriver-cd/screwdriver/blob/master/config/default.yaml).
Unfortunately, we don't have a validator for the cluster configuration file, which is where the Jenkins options you mentioned belong.

**Comment by pgulanetsk** [comment]
Thats fine if the validator is only for screwdriver.yaml. Is there any sample configs reference to define external Jenkins CI that needs to be called from cluster configuration yaml file

**Comment by d2lam** [comment]
@prakashgula  @pgulanetsk Our team doesn't use the Jenkins executor, so we have limited knowledge. Maybe @catto or @tk3fftk  can give better examples/guidance on how to use the Jenkins executor since they built & use it.

**Comment by catto** [comment]
@prakashgula @pgulanetsk You can see docker-compose.yml in your work directory after in-a-box setup is completed, and that is the file you need to specify your jenkins cluster.
The settings available in the file are defined at [config-env mapping](https://github.com/screwdriver-cd/screwdriver/blob/master/config/custom-environment-variables.yaml#L139-L168).

I use the Jenkins executor with Kubernetes runtime not Docker compose, so I show you just a minimum example of Jenkins executor config for in-a-box.
```yaml
services:
    api:
        image: screwdrivercd/screwdriver:stable
        # entrypoint and command are needed during beta period.
        # Once Jenkins executor is generally available, you can remove these
        entrypoint: /bin/sh
        command: ["-c", "npm install screwdriver-executor-jenkins && npm start"]
        environment:
            #  (snip other vars)
            EXECUTOR_PLUGIN: jenkins   # You may want to set this var so that you don't have to specify a config to use jenkins cluster every time in your screwdriver.yaml
            EXECUTOR_JENKINS_ENABLED: "true" # note: env vars are string
            EXECUTOR_JENKINS_HOST: your-jenkins-host
            EXECUTOR_JENKINS_PORT: "8080"
            EXECUTOR_JENKINS_USERNAME: your-username
            EXECUTOR_JENKINS_PASSWORD: your-password
            EXECUTOR_JENKINS_NODE_LABEL: your-custom-node-label-to-run-sd-builds # default: screwdriver
```
You can also set other variables to docker-compose.yml, such as a path of docker-compose, timeout and setup script.
Additionally, you need to install docker-compose and docker to your Jenkins because Screwdriver.cd uses docker-compose to run builds.

Hope this helps 🐈
