### ISSUE TITLE
Detached workflow graph is a little confusing

### ISSUE THREAD

**Issue by petey** [screwdriver-cd/screwdriver#907]
**What happened**:
The workflow graph always tries to bubble each build to the bottom of the it's respective column. This can cause detached workflows to flow confusingly into the primary workflow.

![](https://user-images.githubusercontent.com/78533/36818499-1e69196e-1c9a-11e8-83e7-473750fc5866.png)

**What you expected to happen**:
It might be easier to read if the baseline row for each pipeline is set with respect to the node that starts the flow. So a detached workflow pipeline will always start from the same "row" as the first job, and not "flow up" for successive jobs.

Example:
![](https://user-images.githubusercontent.com/78533/36819782-a55708c8-1c9f-11e8-8d36-35455b045028.png)

**How to reproduce**:
```
shared:
    image: node:8
    steps:
        - greet: echo hello

jobs:
    main:
        requires: 
            - ~commit
            - ~pr
            - ~sd@2:main
    two:
        requires:
            - main

    three:
        requires:
            - main
    four: 
        requires:
            - two
            - three

    detached-one: {}
    detached-two:
        requires:
            - detached-one
    detached-three:
        requires:
            - detached-two
```
