### ISSUE TITLE
Control job trigger based on source path

### ISSUE THREAD

**Issue by jithin1987** [screwdriver-cd/screwdriver#911]
## Context

Today screwdriver listens to any changes in the SCM repo on `commit` and `pr` and runs builds for jobs which have `requires` on them. This is not ideal for SCM repositories following monorepo pattern, where individual sub directories need to be built by themselves. 

## Objective

A job configuration should support an annotation to specify paths within the SCM repo which should trigger it. 

```
jobs:
  buildPathA:
    requires: [~commit, ~pr]
    image: node:8
    sourcePaths: [src/A, src/AConfig]
    steps:
      - buildA: make build
```

Above configuration should run a build for job `buildPathA` on `commit` or `pr` if and only if the SCM commit change include files under path `src/A` or `src/AConfig`

This along with supporting `meta` at event level will allow SCMs following a monorepo source pattern to build multiple parallel pipeline workflows to build various parts of the repo.

## References 
Subdirectory Feature -  https://github.com/screwdriver-cd/screwdriver/issues/471
Meta at event level - https://github.com/screwdriver-cd/screwdriver/issues/904

## Updates
* 3/8/18 Moved config from annotations to settings 
* 3/9/18 Moved config to job config, settings was wrong place to put

**Comment by jithin1987** [comment]
@stjohnjohnson  I plan to use this to support sub directories #471  Thoughts ?

**Comment by stjohnjohnson** [comment]
@jithin1987 Seems like a good approach.  I'd love to see more things like this in the future.  Although we should probably implement a generic method in the models to access annotations easier (with defaults) from the pipeline and job level.

**Comment by jithin1987** [comment]
## *Update 3/8/2018*

Rather than putting the source config in `annotations` we have decided to put the config under `settings` since this is a permanent setting. Update config for this feature will look like

```
jobs:
  buildPathA:
    requires: [~commit, ~pr]
    image: node:8
    settings:
      sourcePaths: [src/A, src/AConfig]
    steps:
      - buildA: make build
```
