### ISSUE TITLE
Parent meta from external trigger job

### ISSUE THREAD

**Issue by jithin1987** [screwdriver-cd/screwdriver#922]
## Context

Jobs which have large number of external triggers it's helpful to refer the external trigger pipeline's job by a simple keyword called `parent`.

For example consider a job config like the following (which is infact a real build pipeline a user have) 

```
jobs:
    parameterizedBuild:
    requires: [~sd@1:commit, ~sd@2:commit, ~sd@3:commit, ~sd@4:commit, ~sd@5:commit, ~sd@6:commit, ~sd@7:commit, ..., ~sd@160:commit]
    steps:
        checkout: echo "checking out source code for parent" 
        build: echo "building parent"
```
Also each parent sets `meta` of the same structure
```
{
  source: github.com/org/source1

}
```
With the above job config it's extremely tedious for the `parameterizedBuild` job to pull out meta data from the triggering job since current syntax (`meta get --external sd@pipelineId:jobName key`) requires prior knowledge of external pipeline `Id` and `jobName`. Having an easier way to refer to the current external parent job who is triggering job `parameterizedBuild` will simplify the usage of `meta`.

## Objective

1. Expose `meta get --external sd@parent key` where parent is an alias to current `pipelineId:jobName`.
1. meta get --external sd@parent parentId` should return `pipelineId:jobName`
1. meta get --external sd@parent key` should fail if job was run manually using `Start` button in `UI`

## References
External meta https://github.com/screwdriver-cd/screwdriver/issues/771
