### ISSUE TITLE
Screwdriver stops the build on exit0

### ISSUE THREAD

**Issue by yoshwata** [screwdriver-cd/screwdriver#927]
**What happened**:
Screwdriver loads a screwdriver.yaml like below, then starts the build.
```
jobs:
    main:
        image: centos
        requires: [~pr, ~commit]
        steps:
          - echo01: echo "foo"
          - exit01: echo "I am log.";exit 0
          - echo02: echo "bar"

```

Pipeline stops on step `echo02` without any logs.

**What you expected to happen**:
- Screwdriver does not stop the pipeline. `exit 0` is frequently use case of shell programming.
~~- Screwdriver shows the log on `exit01` step.~~
