### ISSUE TITLE
Pipelines for projects that use multiple Docker containers

### ISSUE THREAD

**Issue by marian-r** [screwdriver-cd/screwdriver#952]
Question: Is there any way, or what is the recommended approach to create pipeline for project which uses multiple docker containers? Those are for example projects that use a database in a separate container that the application code. How to set up pipelines for those?

**Comment by marian-r** [comment]
Thanks @d2lam, but unfortunately that does't solve our problem.

We have a Node.js app, which uses MySQL database. When we run tests, we would like to start the MySQL database using an official MySQL docker image. Tests need to run using Node.js. So ideally we would need to run 2 containers when running tests - 1 for MySQL database and one for actual test code. Do you see any solutions for this?

**Comment by d2lam** [comment]
I see. So you need 2 containers to run at the same time. We currently don't support this. 
@jithin1987  What do you think?

**Comment by jithin1987** [comment]
Build for job runs in privileged docker container. You could  do `docker run mysql_image` to bring up the mysql inside your build which can use a nodejs container.
Eg:
```
jobs:
   test:
      image: nodejs:8
      steps:
         - run_mysql: docker run my_app
         - run_test: npm run test
...
```
