### ISSUE TITLE
feature:  more flexible meta keys

### ISSUE THREAD

**Issue by drewfish** [screwdriver-cd/screwdriver#964]
**What happened**:
`meta set foo.bar-baz blix` fails with "ERROR: Meta key validation error"

**What you expected to happen**:
Would be nice if a richer syntax for meta keys is allowed. (This might be especially helpful for backwards compatibility with our company-internal Screwdriver v3.)

This appears to be the current limitation:
https://github.com/screwdriver-cd/meta-cli/blob/c5d5b4bd91547e6db43843262f649723412b4017/meta.go#L28

**How to reproduce it**:

**Comment by d2lam** [comment]
@catto  @tk3fftk  Can we make the regex more flexible to allow `-`? Any problems you guys can foresee?

**Comment by catto** [comment]
Make sense. We may have to fix keys handling though, I cannot see any concern about this change. Our team will work on it 🐈

**Comment by tkyi** [comment]
This issue is resolved. I ran a job with this yaml with success:
```
jobs:
    main:
        requires: [~pr, ~commit]
        image: node:8
        steps:
            - meta_set: meta set foo.bar-baz meow
            - meta_get: meta get foo.bar-baz
```
