### ISSUE TITLE
template-tag lags when building a template

### ISSUE THREAD

**Issue by drewfish** [screwdriver-cd/screwdriver#983]
**What happened**:
I'm building a template in this fashion:
```yaml
version: 4
jobs:
    main:
        image: node:8
        requires: [ ~pr, ~commit ]
        template: sd/template-verify@stable
    publish:
        image: node:8
        requires: [ main ]
        template: sd/template-publish@stable
        steps:
            - postsave_version: |
                ver=$(meta get template.template_publish.version)
                echo tagging ${ver} to test...
                template-tag --name MYTEMPLATE --version ${ver} --tag test
                sleep 20    # wait a little bit for the template-tag to propagate
    verify:
        requires: [ publish ]
        template: MYTEMPLATE@test
        steps:
            - postLAST-STEP-OF-TEMPLATE: node validate-test-build.js
    promote:
        image: node:8
        requires: [ verify ]
        steps:
            - install_binaries: npm i -g screwdriver-template-main
            - promote: |
                ver=$(meta get template.template_publish.version)
                echo tagging ${ver} to stable...
                template-tag --name MYTEMPLATE --version ${ver} --tag stable
```
(There are a couple placeholders, `MYTEMPLATE` and `LAST-STEP-OF-TEMPLATE` in the above.)

What I'm seeing is that the `verify` build is getting the **old** version of the template even though I'm specifying the just-tagged `test` version. (I even put a `sleep` after `template-tag` to give a chance for the tagging to propagate through the system.)

**What you expected to happen**:
When I tag a template, that updated tag gets propagated to all executors

**How to reproduce it**:
